<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>23. Linear and polynomial regression – Foundations to Deep Learning</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./24-pca.html" rel="next">
<link href="./22-what-is-ml.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-968ddd4980072ae063619731fc79ef1d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./22-what-is-ml.html">Part III — Machine Learning Foundations</a></li><li class="breadcrumb-item"><a href="./23-linear-polynomial-regression.html"><span class="chapter-title">23. Linear and polynomial regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundations to Deep Learning</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Foundations to Deep Learning</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Mathematical Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-sets-functions-preliminaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 1 — Sets, functions, and mathematical preliminaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-vectors-and-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2. Vectors and matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-linear-systems-determinants-inverses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3. Linear systems, determinants, inverses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-vector-spaces-four-subspaces.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4. Vector spaces and the four fundamental subspaces</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-orthogonality-projections-least-squares.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5. Orthogonality, projections, least squares</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-eigenvalues-eigenvectors-diagonalization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6. Eigenvalues, eigenvectors, diagonalization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-svd-positive-definite.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7. SVD and positive definite matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-single-variable-calculus.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8. Single-variable calculus: continuity, differentiability, derivatives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-multivariable-calculus.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9. Multivariable calculus: partial derivatives, gradients, Taylor series</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-unconstrained-optimization-gradient-descent.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10. Unconstrained optimization and gradient descent</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-constrained-optimization-lagrange.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11. Constrained optimization: Lagrange multipliers, projected gradient descent</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-convex-sets-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12. Convex sets and convex functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-duality-kkt.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13. Duality and KKT conditions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Probability and Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-probability-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14. Probability basics: experiments, sample spaces, Bayes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-discrete-random-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15. Discrete random variables and key distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-continuous-random-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16. Continuous random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-joint-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17. Joint distributions: two random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-joint-continuous-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18. Joint continuous distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-random-vectors-multivariate-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19. Random vectors and the multivariate normal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-estimation-mle-map.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20. Estimation: MLE and Bayesian/MAP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-inequalities-clt.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21. Inequalities and the central limit theorem</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III — Machine Learning Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-what-is-ml.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22. What is ML: data, models, tasks; supervised vs unsupervised</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-linear-polynomial-regression.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">23. Linear and polynomial regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-pca.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">24. PCA: variance maximization, eigendecomposition, kernel PCA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-gmm-em.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">25. GMMs and the EM algorithm</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV — Machine Learning Techniques</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-k-means.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26. K-means clustering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-kernel-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27. Kernel methods and kernel regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-regularization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28. Regularization: ridge and lasso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29-knn-trees.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">29. KNN and decision trees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-naive-bayes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30. Naive Bayes: generative vs discriminative models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-perceptron-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31. Perceptron and logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32-hard-margin-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 32: Hard-margin SVM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33-soft-margin-kernel-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 33: Soft-margin SVM and the kernel trick</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34-ensembles.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 34: Ensembles — bagging, boosting, AdaBoost</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./35-loss-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 35: Loss functions for classification</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Part V — Machine Learning in Practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./36-numpy-pandas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 36: NumPy and Pandas for ML</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./37-sklearn-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 37: scikit-learn: regression workflows</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./38-sklearn-classification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 38: scikit-learn: classification workflows</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./39-model-evaluation-cv.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 39: Model evaluation, cross-validation, hyperparameter tuning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40-end-to-end-debugging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 40: End-to-end model training and debugging</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Part VI — Bridge to Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41-neuron-mlp-scratch.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 41: The artificial neuron and MLPs from scratch</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42-backpropagation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 42: Backpropagation, worked end-to-end</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43-optimization-neural-nets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 43: Optimization for neural nets — SGD variants, init, normalization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./44-cnns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 44: CNNs — convolution, pooling, transfer learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./45-rnns-sequences-vanishing-gradients.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 45: RNNs — sequences and vanishing gradients</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./46-attention-and-transformers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 46: Attention and the transformer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./47-generative-models-gans-diffusion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 47: Generative models: GANs and diffusion</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-setup-data-model-loss" id="toc-the-setup-data-model-loss" class="nav-link active" data-scroll-target="#the-setup-data-model-loss">23.1 The setup: data, model, loss</a></li>
  <li><a href="#the-feature-matrix" id="toc-the-feature-matrix" class="nav-link" data-scroll-target="#the-feature-matrix">23.2 The feature matrix</a></li>
  <li><a href="#deriving-the-normal-equations-the-calculus-route" id="toc-deriving-the-normal-equations-the-calculus-route" class="nav-link" data-scroll-target="#deriving-the-normal-equations-the-calculus-route">23.3 Deriving the normal equations (the calculus route)</a></li>
  <li><a href="#the-same-equations-from-projections" id="toc-the-same-equations-from-projections" class="nav-link" data-scroll-target="#the-same-equations-from-projections">23.4 The same equations from projections</a></li>
  <li><a href="#the-closed-form-solution-and-the-full-rank-condition" id="toc-the-closed-form-solution-and-the-full-rank-condition" class="nav-link" data-scroll-target="#the-closed-form-solution-and-the-full-rank-condition">23.5 The closed-form solution and the full-rank condition</a></li>
  <li><a href="#why-squared-loss-is-right-the-gaussian-noise-story" id="toc-why-squared-loss-is-right-the-gaussian-noise-story" class="nav-link" data-scroll-target="#why-squared-loss-is-right-the-gaussian-noise-story">23.6 Why squared loss is right: the Gaussian-noise story</a></li>
  <li><a href="#worked-example-set" id="toc-worked-example-set" class="nav-link" data-scroll-target="#worked-example-set">23.7 Worked example set</a></li>
  <li><a href="#polynomial-regression-curved-fits-with-the-same-machine" id="toc-polynomial-regression-curved-fits-with-the-same-machine" class="nav-link" data-scroll-target="#polynomial-regression-curved-fits-with-the-same-machine">23.8 Polynomial regression: curved fits with the same machine</a></li>
  <li><a href="#more-capacity-is-not-always-better-overfitting-and-the-validation-discipline" id="toc-more-capacity-is-not-always-better-overfitting-and-the-validation-discipline" class="nav-link" data-scroll-target="#more-capacity-is-not-always-better-overfitting-and-the-validation-discipline">23.9 More capacity is not always better: overfitting, and the validation discipline</a></li>
  <li><a href="#the-lectures-remark-ridge-regularization-a-pointer" id="toc-the-lectures-remark-ridge-regularization-a-pointer" class="nav-link" data-scroll-target="#the-lectures-remark-ridge-regularization-a-pointer">23.10 The lecture’s remark: ridge regularization (a pointer)</a></li>
  <li><a href="#where-this-goes-next" id="toc-where-this-goes-next" class="nav-link" data-scroll-target="#where-this-goes-next">23.11 Where this goes next</a></li>
  <li><a href="#problem-set" id="toc-problem-set" class="nav-link" data-scroll-target="#problem-set">Problem set</a></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions">Solutions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./22-what-is-ml.html">Part III — Machine Learning Foundations</a></li><li class="breadcrumb-item"><a href="./23-linear-polynomial-regression.html"><span class="chapter-title">23. Linear and polynomial regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">23. Linear and polynomial regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Chapter 22 promised (§22.14): Chapter 23 finds the best regression model over <em>all</em> linear (and polynomial) models — not by comparing two hand-picked candidates, but by solving for the optimum over the entire infinite collection. This chapter is that solution. Everything here comes from the MLF Week 4 lecture “Linear and Polynomial Regression” (Prof.&nbsp;Prashanth L A, IIT Madras). The lecture’s headline idea: solving linear regression by taking derivatives gives <em>exactly</em> the system of equations you would get by projecting onto the column space — §5.8’s two routes to the normal equations, now wearing ML clothes. Polynomial regression turns out to need no new machinery at all: transform the features, then run the same machine.</p>
<section id="the-setup-data-model-loss" class="level2">
<h2 class="anchored" data-anchor-id="the-setup-data-model-loss">23.1 The setup: data, model, loss</h2>
<p><strong>Data.</strong> <span class="math inline">\(\{(x^1, y^1), (x^2, y^2), \ldots, (x^n, y^n)\}\)</span> with <span class="math inline">\(x^i \in \mathbb{R}^d\)</span>, <span class="math inline">\(y^i \in \mathbb{R}\)</span>. The superscript indexes the data point, the subscript (when needed) the coordinate — §22.6’s convention, kept through Part III.</p>
<p><strong>Model.</strong> A linear function of the input: <span class="math display">\[\boxed{f_\theta(x) = \theta^T x}, \qquad \theta \in \mathbb{R}^d.\]</span> The parameters <span class="math inline">\(\theta\)</span> are what the learning algorithm chooses (§22.5).</p>
<p><strong>Note (where is the bias <span class="math inline">\(b\)</span>?).</strong> Chapter 22 wrote the model as <span class="math inline">\(\mathbf{w}^T\mathbf{x} + b\)</span>. The lecture folds <span class="math inline">\(b\)</span> into <span class="math inline">\(\theta\)</span>: append a constant coordinate <span class="math inline">\(1\)</span> to every <span class="math inline">\(x\)</span> (so <span class="math inline">\(x = (1, x_1, \ldots, x_{d-1})^T\)</span>), and <span class="math inline">\(b\)</span> becomes <span class="math inline">\(\theta_0\)</span> (0-based indexing, used throughout this chapter). It is the same model — an intercept feature is just a feature that never changes.</p>
<p><strong>Loss.</strong> The squared-error objective the lecture minimizes: <span class="math display">\[\boxed{L(\theta) = \frac{1}{2}\sum_{i=1}^{n}\big(\theta^T x^i - y^i\big)^2}.\]</span></p>
<p><strong>Note (the <span class="math inline">\(\tfrac12\)</span> vs the <span class="math inline">\(\tfrac1n\)</span>).</strong> Chapter 22 wrote the loss as <span class="math inline">\(\frac1n\sum(\cdot)^2\)</span>; Sejal’s lecture notes and the deck write <span class="math inline">\(\frac12\sum(\cdot)^2\)</span>. The constant in front is a bookkeeping choice — <span class="math inline">\(\tfrac12\)</span> cancels the <span class="math inline">\(2\)</span> that differentiation produces — and it never changes the minimizer: <span class="math inline">\(\arg\min \frac12\sum = \arg\min \frac1n\sum\)</span>. The learning algorithm picks the <em>model</em>, not the number.</p>
<p><strong>Basically, …</strong> “How far is the line’s prediction from each answer? Square each miss, add up. Find the line with the smallest total.” That is the entire regression problem — §22.8’s curve-fitting, now with a plan to <em>find</em> the best curve.</p>
</section>
<section id="the-feature-matrix" class="level2">
<h2 class="anchored" data-anchor-id="the-feature-matrix">23.2 The feature matrix</h2>
<p>Stack the data into a matrix and the bookkeeping collapses. <strong>Def (feature matrix).</strong> <span class="math inline">\(A\)</span> is the <span class="math inline">\(n \times d\)</span> matrix whose rows are the data points as row vectors: <span class="math display">\[\boxed{A = \begin{pmatrix} (x^1)^T \\ (x^2)^T \\ \vdots \\ (x^n)^T \end{pmatrix}, \qquad Y = \begin{pmatrix} y^1 \\ y^2 \\ \vdots \\ y^n \end{pmatrix}}.\]</span> The lecture calls <span class="math inline">\(A\)</span> the <strong>feature matrix</strong>; <span class="math inline">\(Y\)</span> is the target vector.</p>
<ol type="i">
<li><strong><span class="math inline">\(A\theta\)</span> = all predictions at once.</strong> Row <span class="math inline">\(i\)</span> of <span class="math inline">\(A\theta\)</span> is <span class="math inline">\((x^i)^T\theta = \theta^T x^i = f_\theta(x^i)\)</span>.</li>
<li><strong><span class="math inline">\(A\theta - Y\)</span> = all residuals at once.</strong> A vector of the <span class="math inline">\(n\)</span> misses.</li>
<li><strong>The loss, in one line:</strong> <span class="math display">\[\boxed{L(\theta) = \frac{1}{2}(A\theta - Y)^T(A\theta - Y) = \frac{1}{2}\|A\theta - Y\|^2}.\]</span></li>
</ol>
<p><strong>Basically, …</strong> <span class="math inline">\(A\)</span> is the data table, <span class="math inline">\(Y\)</span> the answer column. Multiply the table by the parameters to get predictions; subtract the answers to get the misses; the loss is half the squared length of the miss vector.</p>
</section>
<section id="deriving-the-normal-equations-the-calculus-route" class="level2">
<h2 class="anchored" data-anchor-id="deriving-the-normal-equations-the-calculus-route">23.3 Deriving the normal equations (the calculus route)</h2>
<p>To minimize <span class="math inline">\(L\)</span>: set the gradient to zero (§10.1’s recipe). Write the loss with matrix entries: <span class="math display">\[L(\theta) = \frac{1}{2}\sum_{i=1}^{n}\left(\sum_{j=1}^{d}A_{ij}\theta_j - y^i\right)^2.\]</span> The partial derivative in <span class="math inline">\(\theta_k\)</span> (chain rule; the <span class="math inline">\(\tfrac12\)</span> cancels the <span class="math inline">\(2\)</span>): <span class="math display">\[\frac{\partial L}{\partial\theta_k} = \sum_{i=1}^{n}\underbrace{\left(\sum_{j=1}^{d}A_{ij}\theta_j - y^i\right)}_{\text{residual } i}\cdot \underbrace{A_{ik}}_{\text{column } k} = \sum_{i=1}^{n}A_{ik}\,(A\theta - Y)_i = \big[A^T(A\theta - Y)\big]_k.\]</span> So the gradient is <span class="math display">\[\boxed{\nabla_\theta L = A^T(A\theta - Y)}.\]</span> Setting it to zero and rearranging: <span class="math display">\[\boxed{A^TA\,\theta = A^TY} \qquad \text{(the \textbf{normal equations})}.\]</span> These are <span class="math inline">\(d\)</span> equations in the <span class="math inline">\(d\)</span> unknowns <span class="math inline">\(\theta\)</span> — the lecture’s entire linear-regression training step in one line.</p>
<p><strong>Note (why this is a minimum, not just a stationary point).</strong> The Hessian is <span class="math inline">\(\nabla^2 L = A^TA\)</span>. For any <span class="math inline">\(z\)</span>: <span class="math display">\[z^T(A^TA)z = (Az)^T(Az) = \|Az\|^2 \ge 0,\]</span> so the Hessian is positive semidefinite (§10.8’s interrogation). A convex quadratic’s stationary point is its global minimum (§12.9) — the normal equations don’t just find a candidate, they find <em>the</em> optimum.</p>
<p><strong>Basically, …</strong> Differentiate the total miss, set to zero, and the equations tidy themselves into <span class="math inline">\(A^TA\,\theta = A^TY\)</span>. The <span class="math inline">\(d\times d\)</span> system on the left is all the data, compressed into one matrix.</p>
</section>
<section id="the-same-equations-from-projections" class="level2">
<h2 class="anchored" data-anchor-id="the-same-equations-from-projections">23.4 The same equations from projections</h2>
<p>This is the lecture’s headline, and §5.8 already proved the mechanism:</p>
<ol type="i">
<li><strong>Calculus route</strong> (§23.3): differentiate <span class="math inline">\(L\)</span>, set <span class="math inline">\(\nabla L = 0\)</span> → <span class="math inline">\(A^TA\theta = A^TY\)</span>.</li>
<li><strong>Geometric route</strong> (§5.7): the predictions <span class="math inline">\(\mathbf{p} = A\hat\theta\)</span> are the closest point of the column space <span class="math inline">\(C(A)\)</span> to <span class="math inline">\(Y\)</span> — i.e.&nbsp;the orthogonal projection of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(C(A)\)</span>. The error <span class="math inline">\(Y - A\hat\theta\)</span> is orthogonal to <span class="math inline">\(C(A)\)</span>, which forces <span class="math inline">\(A^T(Y - A\hat\theta) = 0\)</span> — the same equations.</li>
</ol>
<p><strong>The lecture’s point.</strong> Two completely different arguments — “minimize the squared miss” and “drop <span class="math inline">\(Y\)</span> perpendicularly onto the column space” — land on the identical system. Least squares <strong>is</strong> projection; the ML loss <strong>is</strong> the geometry of §5.</p>
<p><strong>Basically, …</strong> “The best prediction vector is the shadow <span class="math inline">\(Y\)</span> casts on the column space” and “the parameters with the smallest squared error” are the same sentence in two languages.</p>
</section>
<section id="the-closed-form-solution-and-the-full-rank-condition" class="level2">
<h2 class="anchored" data-anchor-id="the-closed-form-solution-and-the-full-rank-condition">23.5 The closed-form solution and the full-rank condition</h2>
<p>If <span class="math inline">\(A\)</span> has <strong>full column rank</strong> (independent columns — §4.6), then <span class="math inline">\(A^TA\)</span> is invertible and the normal equations have one solution: <span class="math display">\[\boxed{\hat\theta = (A^TA)^{-1}A^TY}.\]</span></p>
<p><strong>Why full rank of <span class="math inline">\(A\)</span> ⇒ invertibility of <span class="math inline">\(A^TA\)</span></strong> (the lecture’s homework hint, worked out). It is enough to show the two matrices have the same null space (§4.7):</p>
<ol type="i">
<li><span class="math inline">\(Ax = 0 \;\Rightarrow\; A^TAx = A^T0 = 0\)</span>. Trivial direction: <span class="math inline">\(N(A) \subseteq N(A^TA)\)</span>.</li>
<li><span class="math inline">\(A^TAx = 0 \;\Rightarrow\; x^TA^TAx = 0 \;\Rightarrow\; (Ax)^T(Ax) = \|Ax\|^2 = 0 \;\Rightarrow\; Ax = 0\)</span>. So <span class="math inline">\(N(A^TA) \subseteq N(A)\)</span>.</li>
</ol>
<p>Same null space ⇒ same rank (rank–nullity, §4.8). If <span class="math inline">\(A\)</span> has full column rank <span class="math inline">\(d\)</span>, then <span class="math inline">\(A^TA\)</span> is a <span class="math inline">\(d\times d\)</span> matrix of rank <span class="math inline">\(d\)</span> — hence invertible.</p>
<p><strong>Note (dependent columns).</strong> If <span class="math inline">\(A\)</span>’s columns are dependent, the normal equations still <em>have</em> solutions — but infinitely many (§5.8 said the same): there are many least-squares <span class="math inline">\(\hat\theta\)</span>, and the closed form breaks because <span class="math inline">\((A^TA)^{-1}\)</span> doesn’t exist. §23.10 shows the lecture’s fix.</p>
<p><strong>Basically, …</strong> If every feature says something new (independent columns), there is exactly one best <span class="math inline">\(\theta\)</span>, given by one matrix inverse. If two features say the same thing, credit can’t be split uniquely — no single answer.</p>
</section>
<section id="why-squared-loss-is-right-the-gaussian-noise-story" class="level2">
<h2 class="anchored" data-anchor-id="why-squared-loss-is-right-the-gaussian-noise-story">23.6 Why squared loss is right: the Gaussian-noise story</h2>
<p>Why square the misses — why not absolute values, or something else? The lecture gives the probabilistic answer (the full machinery is §20.8; here is the meaning).</p>
<p><strong>The generative model.</strong> Suppose nature produces labels as <span class="math display">\[\boxed{y = \theta^Tx + \varepsilon}, \qquad \varepsilon \sim N(0,\, 1/\beta),\]</span> i.e.&nbsp;the truth is linear, plus <strong>Gaussian noise</strong> with precision <span class="math inline">\(\beta\)</span> (precision = <span class="math inline">\(1\)</span>/variance). The data <span class="math inline">\(\{(x^i, y^i)\}\)</span> are drawn independently from this model. Maximum likelihood asks: which <span class="math inline">\(\theta\)</span> makes the observed data most probable? The log-likelihood (dropping <span class="math inline">\(\theta\)</span>-free constants): <span class="math display">\[\ell(\theta) = -\frac{\beta}{2}\sum_{i=1}^{n}\big(y^i - \theta^Tx^i\big)^2 + \text{const}.\]</span> Maximizing <span class="math inline">\(\ell(\theta)\)</span> = minimizing <span class="math inline">\(\frac{\beta}{2}\sum(y^i - \theta^Tx^i)^2\)</span> = minimizing the least-squares objective of §23.1 (the <span class="math inline">\(\beta/2\)</span> is another harmless constant).</p>
<p><strong>The lecture’s message.</strong> “Least squares regression solves a maximum likelihood estimation problem under a linear model.” The noise model <em>chooses</em> the loss: <strong>Gaussian noise ⇒ squared error</strong>. This is §20.8 made concrete — the bridge from Part II’s probability to Part III’s algorithms.</p>
<p><strong>Basically, …</strong> If you believe the errors are bell-curved, squared error isn’t an arbitrary choice — it’s exactly what “the most likely explanation” works out to be.</p>
</section>
<section id="worked-example-set" class="level2">
<h2 class="anchored" data-anchor-id="worked-example-set">23.7 Worked example set</h2>
<p><strong>eg 1 (the normal equations on §22.8’s data — beating both hand-picked candidates).</strong> Data (with intercept feature): <span class="math inline">\((x^1,y^1) = (1,2.1)\)</span>, <span class="math inline">\((2,3.9)\)</span>, <span class="math inline">\((3,6.2)\)</span>, <span class="math inline">\((6,11.5)\)</span>, <span class="math inline">\((7,13.9)\)</span>. Chapter 22 compared <span class="math inline">\(f(x) = 2x\)</span> (<span class="math inline">\(L = 0.064\)</span>) with <span class="math inline">\(g(x) = x + 3\)</span> (<span class="math inline">\(L = 5.264\)</span>) — both guesses. Now solve over <em>all</em> lines <span class="math inline">\(f(x) = \theta_0 + \theta_1x\)</span>.</p>
<p>Step 1 — build <span class="math inline">\(A, Y\)</span>: <span class="math display">\[A = \begin{pmatrix} 1 &amp; 1 \\ 1 &amp; 2 \\ 1 &amp; 3 \\ 1 &amp; 6 \\ 1 &amp; 7 \end{pmatrix}, \qquad Y = \begin{pmatrix} 2.1 \\ 3.9 \\ 6.2 \\ 11.5 \\ 13.9 \end{pmatrix}.\]</span></p>
<p>Step 2 — compress into the normal equations: <span class="math display">\[A^TA = \begin{pmatrix} 5 &amp; 19 \\ 19 &amp; 99 \end{pmatrix}, \qquad A^TY = \begin{pmatrix} 37.6 \\ 194.8 \end{pmatrix}.\]</span> (Check a couple of entries: <span class="math inline">\((A^TA)_{22} = 1+4+9+36+49 = 99\)</span> ✓; <span class="math inline">\((A^TY)_2 = 2.1 + 2(3.9) + 3(6.2) + 6(11.5) + 7(13.9) = 2.1+7.8+18.6+69+97.3 = 194.8\)</span> ✓.)</p>
<p>Step 3 — invert. <span class="math inline">\(\det(A^TA) = 5\cdot 99 - 19^2 = 495 - 361 = 134 \ne 0\)</span> — the columns are independent, so the solution is unique (§23.5): <span class="math display">\[(A^TA)^{-1} = \frac{1}{134}\begin{pmatrix} 99 &amp; -19 \\ -19 &amp; 5 \end{pmatrix}, \qquad \hat\theta = \frac{1}{134}\begin{pmatrix} 99(37.6) - 19(194.8) \\ -19(37.6) + 5(194.8) \end{pmatrix} = \frac{1}{134}\begin{pmatrix} 21.2 \\ 259.6 \end{pmatrix}.\]</span> <span class="math display">\[\boxed{\hat\theta_0 \approx 0.158,\quad \hat\theta_1 \approx 1.937} \qquad \text{best line: } f(x) = 1.937x + 0.158.\]</span></p>
<p>Step 4 — verify it wins. Predictions: <span class="math inline">\(2.0955,\ 4.0328,\ 5.9701,\ 11.7821,\ 13.7194\)</span>. Residuals (pred − <span class="math inline">\(y\)</span>): <span class="math inline">\(-0.0045,\ 0.1328,\ -0.2299,\ 0.2821,\ -0.1806\)</span>. Squared sum <span class="math inline">\(= 0.1827\)</span>; in §22.8’s <span class="math inline">\(\tfrac1n\)</span> convention: <span class="math display">\[L(\hat\theta) = \frac{0.1827}{5} \approx \boxed{0.0365} &lt; 0.064 = L(f = 2x).\]</span> The algorithm didn’t pick between two candidates — it searched the whole infinite collection and found something strictly better than both.</p>
<!-- Original matplotlib illustration drawn for this chapter (not reused from any URL): the five data points of eg 1 with the optimal line f(x)=1.937x+0.158 and dashed residual segments -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/23-least-squares-fit.png" class="img-fluid figure-img"></p>
<figcaption>Scatter of the five points (1,2.1),(2,3.9),(3,6.2),(6,11.5),(7,13.9) with the green best-fit line f(x)=1.937x+0.158; short dashed red vertical segments join each point to the line, showing the minimized residuals.</figcaption>
</figure>
</div>
<p><strong>eg 2 (invertible vs singular <span class="math inline">\(A^TA\)</span>).</strong> (i) <span class="math inline">\(A = \begin{pmatrix} 1&amp;1 \\ 1&amp;2 \\ 1&amp;3 \end{pmatrix}\)</span>: columns independent, <span class="math display">\[A^TA = \begin{pmatrix} 3 &amp; 6 \\ 6 &amp; 14 \end{pmatrix}, \quad \det = 42 - 36 = 6 \ne 0 \;\Rightarrow\; (A^TA)^{-1} \text{ exists}.\]</span> (ii) <span class="math inline">\(B = \begin{pmatrix} 1&amp;2 \\ 1&amp;2 \\ 1&amp;2 \end{pmatrix}\)</span>: column 2 <span class="math inline">\(= 2 \times\)</span> column 1 (the “feature” says nothing new), <span class="math display">\[B^TB = \begin{pmatrix} 3 &amp; 6 \\ 6 &amp; 12 \end{pmatrix}, \quad \det = 36 - 36 = 0 \;\Rightarrow\; \text{no inverse}.\]</span> In (ii) the normal equations still have infinitely many solutions — every <span class="math inline">\(\theta\)</span> with <span class="math inline">\(\theta_0 + 2\theta_1\)</span> fixed gives the same predictions — but no unique <span class="math inline">\(\hat\theta\)</span>.</p>
<p><strong>eg 3 (quadratic regression by hand).</strong> Fit a degree-2 polynomial through <span class="math inline">\((0,1)\)</span>, <span class="math inline">\((1,3)\)</span>, <span class="math inline">\((2,7)\)</span>. Transformed features (§23.8): <span class="math inline">\(\phi(x) = (1, x, x^2)^T\)</span>: <span class="math display">\[A = \begin{pmatrix} 1 &amp; 0 &amp; 0 \\ 1 &amp; 1 &amp; 1 \\ 1 &amp; 2 &amp; 4 \end{pmatrix}, \qquad Y = \begin{pmatrix} 1 \\ 3 \\ 7 \end{pmatrix}.\]</span> Normal equations: <span class="math display">\[A^TA = \begin{pmatrix} 3 &amp; 3 &amp; 5 \\ 3 &amp; 5 &amp; 9 \\ 5 &amp; 9 &amp; 17 \end{pmatrix}, \qquad A^TY = \begin{pmatrix} 11 \\ 17 \\ 31 \end{pmatrix}, \quad\text{i.e.}\quad \begin{cases} 3\theta_0+3\theta_1+5\theta_2 = 11 \\ 3\theta_0+5\theta_1+9\theta_2 = 17 \\ 5\theta_0+9\theta_1+17\theta_2 = 31 \end{cases}.\]</span> <span class="math inline">\(A\)</span> is full rank (Vandermonde in disguise — distinct <span class="math inline">\(x\)</span>’s), so try <span class="math inline">\(\hat\theta = (1,1,1)^T\)</span>: <span class="math inline">\(3+3+5 = 11\)</span> ✓; <span class="math inline">\(3+5+9 = 17\)</span> ✓; <span class="math inline">\(5+9+17 = 31\)</span> ✓. Unique solution: <span class="math inline">\(\boxed{\hat y = 1 + x + x^2}\)</span> — and indeed <span class="math inline">\(1+0+0 = 1\)</span>, <span class="math inline">\(1+1+1 = 3\)</span>, <span class="math inline">\(1+2+4 = 7\)</span>: the parabola threads all three points, residuals <span class="math inline">\(0\)</span>. <strong>Note.</strong> With <span class="math inline">\(m = n-1\)</span> (degree 2, three points), the polynomial <em>can</em> hit every point exactly — training error <span class="math inline">\(0\)</span>. Whether that’s good is §23.9’s question.</p>
<p><strong>eg 4 (the degree ladder: train error falls, test error bends).</strong> Five training points near <span class="math inline">\(y = x^2\)</span> (mild noise): <span class="math inline">\(x = (-2,-1,0,1,2)\)</span>, <span class="math inline">\(y = (4.2, 0.9, -0.1, 1.2, 3.8)\)</span>. Three held-out test points: <span class="math inline">\((-1.5, 2.3)\)</span>, <span class="math inline">\((0.5, 0.3)\)</span>, <span class="math inline">\((1.5, 2.2)\)</span>. Fit polynomials of degree <span class="math inline">\(m = 1, 2, 4\)</span> (§23.8’s machine):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>degree <span class="math inline">\(m\)</span></th>
<th>train MSE</th>
<th>test MSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2.863</td>
<td>0.977</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.0229</td>
<td>0.0030</td>
</tr>
<tr class="odd">
<td>4</td>
<td>0.0000</td>
<td>0.0191</td>
</tr>
</tbody>
</table>
<p>Read it: <span class="math inline">\(m = 1\)</span> can’t bend (underfits — high train <em>and</em> test error). <span class="math inline">\(m = 2\)</span> nails the true shape (test error <span class="math inline">\(0.0030\)</span> — best). <span class="math inline">\(m = 4\)</span> has 5 parameters for 5 points, so it interpolates the training data exactly (train error <span class="math inline">\(0\)</span>) — yet its test error is <em>worse</em> than <span class="math inline">\(m = 2\)</span>’s: it wiggled between the training points to fit the noise. This is the overfitting curve; §23.9 turns it into a discipline.</p>
</section>
<section id="polynomial-regression-curved-fits-with-the-same-machine" class="level2">
<h2 class="anchored" data-anchor-id="polynomial-regression-curved-fits-with-the-same-machine">23.8 Polynomial regression: curved fits with the same machine</h2>
<p>The lecture’s generalization of last week’s line fitting: instead of a line, fit a degree-<span class="math inline">\(m\)</span> polynomial.</p>
<p><strong>Data.</strong> Now one-dimensional: <span class="math inline">\(\{(x^1, y^1), \ldots, (x^n, y^n)\}\)</span>, <span class="math inline">\(x^i, y^i \in \mathbb{R}\)</span>.</p>
<p><strong>Def (transformed features).</strong> For each input, build the vector of its powers: <span class="math display">\[\boxed{\phi(x) = \begin{pmatrix} 1 \\ x \\ x^2 \\ \vdots \\ x^m \end{pmatrix}}, \qquad \hat y(x) = \theta^T\phi(x) = \sum_{j=0}^{m}\theta_j x^j, \quad \theta = (\theta_0, \ldots, \theta_m)^T.\]</span></p>
<p><strong>The procedure.</strong> Assemble <span class="math inline">\(\tilde A\)</span> with rows <span class="math inline">\(\phi(x^i)^T\)</span> (same <span class="math inline">\(Y\)</span> as before) and solve the <em>same</em> normal equations: <span class="math display">\[\boxed{\tilde A^T\tilde A\,\theta = \tilde A^TY}.\]</span> “The only difference with respect to regular linear regression,” the lecture says, “is that we are transforming the features and then performing regression.” No new derivation is needed — §23.3’s algebra never assumed the features were raw.</p>
<p><strong>Note (“linear” = linear in <span class="math inline">\(\theta\)</span>).</strong> A parabola is curved in <span class="math inline">\(x\)</span> but linear in the parameters <span class="math inline">\((\theta_0, \theta_1, \theta_2)\)</span> — and least squares only ever sees the parameters. That is why the same machine fits curves.</p>
<p><strong>Basically, …</strong> Want a parabola? Square your <span class="math inline">\(x\)</span>’s yourself, hand the lecture’s machine the features <span class="math inline">\([1, x, x^2]\)</span>, and it fits the “line” in that taller space. Polynomial regression is linear regression in disguise.</p>
</section>
<section id="more-capacity-is-not-always-better-overfitting-and-the-validation-discipline" class="level2">
<h2 class="anchored" data-anchor-id="more-capacity-is-not-always-better-overfitting-and-the-validation-discipline">23.9 More capacity is not always better: overfitting, and the validation discipline</h2>
<p>Eg 4’s table is the whole story in miniature. Raising the degree <span class="math inline">\(m\)</span> always <em>can</em> lower the training error (a degree-4 polynomial contains every degree-2 one as a special case — set the extra <span class="math inline">\(\theta_j\)</span> to <span class="math inline">\(0\)</span>). But:</p>
<ol type="i">
<li><strong>Training error is optimistic.</strong> The <span class="math inline">\(m = 4\)</span> curve scored <span class="math inline">\(0.0000\)</span> on the data it was fitted to and <span class="math inline">\(0.0191\)</span> on data it wasn’t — the same trap as §22.10’s memorizer, now wearing a polynomial costume.</li>
<li><strong>Too simple is also bad.</strong> <span class="math inline">\(m = 1\)</span> underfits: it can’t express the U-shape, so even its training error (<span class="math inline">\(2.863\)</span>) is poor. Capacity too low ⇒ underfitting; capacity too high ⇒ overfitting.</li>
<li><strong>The discipline (§22.10).</strong> Fit each degree on the <em>training</em> data, compare degrees on held-out <em>validation</em> data, report the winner’s error on a third split — the <em>test</em> data. Choosing the degree is <strong>model selection</strong>: §22.10’s job (ii) — picking the collection, not the parameters. Eg 4’s verdict: <span class="math inline">\(m = 2\)</span> wins on the held-out data — here that data plays the <em>validation</em> role (<span class="math inline">\(0.0030\)</span>); a real deployment would then report on a third, untouched <em>test</em> split.</li>
</ol>
<!-- Original matplotlib illustration drawn for this chapter (not reused from any URL): training data with polynomial fits of degree 1 (dashed line), 2 (solid curve tracking the data), and 4 (dotted curve interpolating exactly but wiggling) -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/23-polynomial-overfit.png" class="img-fluid figure-img"></p>
<figcaption>Scatter of the five training points near y=x^2. A dashed red line (degree 1) cuts straight through; a solid green parabola (degree 2) tracks the points; a dotted purple degree-4 curve hits every point exactly but wiggles between them.</figcaption>
</figure>
</div>
<p><strong>Note (the lecture’s hint).</strong> The lecture mentions overfitting only to motivate its closing remark (§23.10): the regularization parameter <span class="math inline">\(\lambda\)</span> “controls overfitting — too small <span class="math inline">\(\lambda\)</span> could lead to a lot of overfitting, too large <span class="math inline">\(\lambda\)</span> leads to underfitting.” There are two cures for an over-ambitious polynomial: choose a smaller <span class="math inline">\(m\)</span> by validation (this section), or penalize large parameters directly (§23.10). The full story of the second cure is Chapter 28.</p>
<p><strong>Basically, …</strong> “The degree-4 curve aced the practice exam and flunked the real one.” Bigger model ≠ better model — judge capacity on data the model never saw during fitting.</p>
</section>
<section id="the-lectures-remark-ridge-regularization-a-pointer" class="level2">
<h2 class="anchored" data-anchor-id="the-lectures-remark-ridge-regularization-a-pointer">23.10 The lecture’s remark: ridge regularization (a pointer)</h2>
<p>The lecture ends with “a very short remark” — ridge regression — kept short here too, because it is Chapter 28’s subject. Instead of the plain least-squares objective, minimize the <strong>regularized</strong> version: <span class="math display">\[\boxed{\bar L(\theta) = \frac{1}{2}\sum_{i=1}^{n}\big((x^i)^T\theta - y^i\big)^2 + \lambda\|\theta\|^2}, \qquad \lambda &gt; 0.\]</span> The extra term penalizes large parameters. Repeating §23.3’s derivation, the gradient picks up <span class="math inline">\(2\lambda\theta\)</span>, so stationarity gives <span class="math inline">\((A^TA + 2\lambda I)\theta_{\text{reg}} = A^TY\)</span> — and since <span class="math inline">\(\lambda &gt; 0\)</span> is just a constant, absorbing the <span class="math inline">\(2\)</span> into it recovers the lecture’s compact form: <span class="math display">\[\boxed{(A^TA + \lambda I)\,\theta_{\text{reg}} = A^TY}, \qquad \hat\theta_{\text{reg}} = (A^TA + \lambda I)^{-1}A^TY.\]</span> <strong>Homework (the lecture’s).</strong> Show <span class="math inline">\(A^TA + \lambda I\)</span> is invertible <em>even when <span class="math inline">\(A\)</span> is not full rank</em>: for <span class="math inline">\(\lambda &gt; 0\)</span> and <span class="math inline">\(z \ne 0\)</span>, <span class="math display">\[z^T(A^TA + \lambda I)z = \|Az\|^2 + \lambda\|z\|^2 &gt; 0,\]</span> so the matrix is positive definite, hence invertible. The <span class="math inline">\(\lambda I\)</span> term is a purely algebraic fix — it guarantees a unique answer — that also happens to be the overfitting cure the lecture promises. Small <span class="math inline">\(\lambda\)</span> ⇒ near-ordinary least squares (overfitting risk stays); large <span class="math inline">\(\lambda\)</span> ⇒ parameters squeezed toward <span class="math inline">\(0\)</span> (underfitting). How to pick <span class="math inline">\(\lambda\)</span> in practice — by validation, §23.9’s discipline — and the lasso cousin belong to Chapter 28.</p>
<p><strong>Basically, …</strong> Add a penalty for big weights, and two things happen at once: the equations always have a unique solution, and the model stops chasing noise. The dial <span class="math inline">\(\lambda\)</span> trades overfitting against underfitting.</p>
</section>
<section id="where-this-goes-next" class="level2">
<h2 class="anchored" data-anchor-id="where-this-goes-next">23.11 Where this goes next</h2>
<ol type="i">
<li><strong>Projections return.</strong> The geometric reading of §23.4 — predictions as projections onto <span class="math inline">\(C(A)\)</span> — is the seed of Chapter 24 (PCA): there the “column space” is learned, not given.</li>
<li><strong>Regularization, properly.</strong> Chapter 28 takes §23.10’s remark and makes it a subject: ridge and lasso, the bias–variance trade-off, and choosing <span class="math inline">\(\lambda\)</span> by validation.</li>
<li><strong>The iterative alternative.</strong> Forming <span class="math inline">\(A^TA\)</span> costs <span class="math inline">\(O(nd^2)\)</span> and inverting it <span class="math inline">\(O(d^3)\)</span> — for enormous data that is too slow. Chapter 10 (§10.7, §10.9) gives the scalable route: gradient descent walks downhill on <span class="math inline">\(L(\theta)\)</span> directly, no inverse needed. Same optimum (§23.3’s convexity guarantees it), different engine.</li>
<li><strong>The atom of the neuron.</strong> <span class="math inline">\(f_\theta(x) = \theta^Tx\)</span> is the linear core inside every artificial neuron of Chapter 41 — this chapter is where the pattern “parameters × features, chosen by minimizing a loss” first appears in full.</li>
</ol>
</section>
<section id="problem-set" class="level2">
<h2 class="anchored" data-anchor-id="problem-set">Problem set</h2>
<ol type="1">
<li><p>For the 1-D data <span class="math inline">\((x^1,y^1) = (1,3)\)</span>, <span class="math inline">\((2,5)\)</span>, <span class="math inline">\((4,9)\)</span> with an intercept feature: (i) write <span class="math inline">\(A\)</span> and <span class="math inline">\(Y\)</span>; (ii) for <span class="math inline">\(\theta = (1,2)^T\)</span> (intercept <span class="math inline">\(1\)</span>, slope <span class="math inline">\(2\)</span>), compute <span class="math inline">\(A\theta\)</span> and <span class="math inline">\(A\theta - Y\)</span>; (iii) evaluate <span class="math inline">\(L(\theta) = \frac12\|A\theta - Y\|^2\)</span>. What does your answer say about the fit?</p></li>
<li><p>Scalar derivation (the lecture’s 1-D case). <span class="math inline">\(L(w, b) = \frac12\sum_{i=1}^n(wx^i + b - y^i)^2\)</span>. Compute <span class="math inline">\(\partial L/\partial w\)</span> and <span class="math inline">\(\partial L/\partial b\)</span> by hand, set both to zero, and show the result is the <span class="math inline">\(2\times 2\)</span> case of the normal equations.</p></li>
<li><p>Lecture homework, the hard direction: prove that if <span class="math inline">\(A^TAx = 0\)</span> then <span class="math inline">\(Ax = 0\)</span> (hence <span class="math inline">\(N(A^TA) \subseteq N(A)\)</span>). Hint: multiply by <span class="math inline">\(x^T\)</span>.</p></li>
<li><p>Fit the best line <span class="math inline">\(f(x) = \theta_0 + \theta_1x\)</span> through <span class="math inline">\((0,0)\)</span>, <span class="math inline">\((1,2)\)</span>, <span class="math inline">\((2,3)\)</span> via the normal equations, showing all steps. Compute the minimum squared error <span class="math inline">\(\|A\hat\theta - Y\|^2\)</span>.</p></li>
<li><p>Show the normal-equation solution is a <em>global</em> minimizer of <span class="math inline">\(L\)</span>: (i) compute the Hessian <span class="math inline">\(\nabla^2 L\)</span>; (ii) show it is positive semidefinite; (iii) conclude with §12.9.</p></li>
<li><p>Fit a quadratic <span class="math inline">\(\hat y = \theta_0 + \theta_1x + \theta_2x^2\)</span> through <span class="math inline">\((0,2)\)</span>, <span class="math inline">\((1,1)\)</span>, <span class="math inline">\((2,2)\)</span>: (i) write <span class="math inline">\(\tilde A\)</span> and <span class="math inline">\(Y\)</span>; (ii) write the <span class="math inline">\(3\times 3\)</span> normal equations; (iii) solve them (verify your answer satisfies all three equations); (iv) explain why the residual is exactly <span class="math inline">\(0\)</span>.</p></li>
<li><p>True or false, with one-line justification: (i) <span class="math inline">\(A^TA\)</span> is always symmetric. (ii) Full column rank of <span class="math inline">\(A\)</span> guarantees a unique <span class="math inline">\(\hat\theta\)</span>. (iii) Raising the polynomial degree never increases the training error. (iv) Raising the polynomial degree never increases the test error.</p></li>
<li><p>For each <span class="math inline">\(A\)</span>, say whether <span class="math inline">\((A^TA)^{-1}\)</span> exists and give the ML reason: (i) <span class="math inline">\(\begin{pmatrix} 1&amp;1 \\ 1&amp;2 \\ 1&amp;3 \end{pmatrix}\)</span>; (ii) <span class="math inline">\(\begin{pmatrix} 1&amp;2&amp;2 \\ 1&amp;3&amp;3 \\ 1&amp;4&amp;4 \end{pmatrix}\)</span> (features: intercept, <span class="math inline">\(x\)</span>, and a copy of <span class="math inline">\(x\)</span>); (iii) <span class="math inline">\(\begin{pmatrix} 1&amp;0 \\ 2&amp;0 \\ 3&amp;0 \end{pmatrix}\)</span> (features: <span class="math inline">\(x\)</span>, and an always-<span class="math inline">\(0\)</span> feature).</p></li>
<li><p>A colleague fits polynomials of degree <span class="math inline">\(1\)</span>–<span class="math inline">\(4\)</span> and reports:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(m\)</span></th>
<th>train MSE</th>
<th>validation MSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2.90</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.05</td>
<td>0.01</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.02</td>
<td>0.03</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.00</td>
<td>0.09</td>
</tr>
</tbody>
</table>
<ol type="i">
<li>Which degree should she pick, and on what data was that decision made? (ii) What phenomenon does <span class="math inline">\(m = 4\)</span> display? (iii) If she must quote one number as “the model’s error” to a user, which split’s number should it be, and why (§22.10)?</li>
</ol></li>
<li><p>Guided MLE→least squares (§20.8, §23.6). Data generated as <span class="math inline">\(y^i = \theta^Tx^i + \varepsilon^i\)</span> with <span class="math inline">\(\varepsilon^i \sim N(0,\sigma^2)\)</span> i.i.d. (i) Write the likelihood <span class="math inline">\(L(\theta)\)</span> as a product of Gaussian densities. (ii) Take the log and drop <span class="math inline">\(\theta\)</span>-free terms. (iii) Show the maximizer equals <span class="math inline">\(\arg\min_\theta \sum_i (y^i - \theta^Tx^i)^2\)</span>.</p></li>
</ol>
</section>
<section id="solutions" class="level2">
<h2 class="anchored" data-anchor-id="solutions">Solutions</h2>
<p>Attempt each problem first, then click a problem to reveal its worked solution.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 1 — i) Rows <span class="math inline">\((1, x^i)\)</span>:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1.</strong> (i) Rows <span class="math inline">\((1, x^i)\)</span>: <span class="math display">\[A = \begin{pmatrix} 1 &amp; 1 \\ 1 &amp; 2 \\ 1 &amp; 4 \end{pmatrix}, \qquad Y = \begin{pmatrix} 3 \\ 5 \\ 9 \end{pmatrix}.\]</span> (ii) <span class="math inline">\(A\theta = \begin{pmatrix} 1+2(1) \\ 1+2(2) \\ 1+2(4) \end{pmatrix} = \begin{pmatrix} 3 \\ 5 \\ 9 \end{pmatrix} = Y\)</span>, so <span class="math inline">\(A\theta - Y = (0,0,0)^T\)</span>. (iii) <span class="math inline">\(L(\theta) = \tfrac12\|0\|^2 = \boxed{0}\)</span>. The line <span class="math inline">\(f(x) = 2x + 1\)</span> passes exactly through all three points — the consistent case (§5.8): no least squares needed, the loss is already at its floor.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 2 — Differentiate term by term:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>2.</strong> Differentiate term by term: <span class="math display">\[\frac{\partial L}{\partial w} = \sum_{i=1}^{n}(wx^i + b - y^i)\cdot x^i, \qquad \frac{\partial L}{\partial b} = \sum_{i=1}^{n}(wx^i + b - y^i)\cdot 1.\]</span> Set both to zero: <span class="math display">\[\sum_i x^i(wx^i + b) = \sum_i x^iy^i, \qquad \sum_i (wx^i + b) = \sum_i y^i.\]</span> With <span class="math inline">\(A = \begin{pmatrix} 1 &amp; x^1 \\ \vdots &amp; \vdots \\ 1 &amp; x^n \end{pmatrix}\)</span> and <span class="math inline">\(\theta = (b, w)^T\)</span>, these are exactly <span class="math display">\[A^TA\theta = A^TY: \quad \begin{pmatrix} n &amp; \sum x^i \\ \sum x^i &amp; \sum (x^i)^2 \end{pmatrix}\!\begin{pmatrix} b \\ w \end{pmatrix} = \begin{pmatrix} \sum y^i \\ \sum x^iy^i \end{pmatrix},\]</span> the <span class="math inline">\(2\times 2\)</span> normal equations. (Check: <span class="math inline">\((A^TA)_{11} = n\)</span>, <span class="math inline">\((A^TA)_{12} = \sum x^i\)</span>, <span class="math inline">\((A^TA)_{22} = \sum (x^i)^2\)</span>; <span class="math inline">\((A^TY)_1 = \sum y^i\)</span>, <span class="math inline">\((A^TY)_2 = \sum x^iy^i\)</span> ✓.)</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 3 — Assume <span class="math inline">\(A^TAx = 0\)</span>. Multiply on the left by <span class="math inline">\(x^T\)</span>:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>3.</strong> Assume <span class="math inline">\(A^TAx = 0\)</span>. Multiply on the left by <span class="math inline">\(x^T\)</span>: <span class="math display">\[0 = x^T(A^TAx) = (x^TA^T)(Ax) = (Ax)^T(Ax) = \|Ax\|^2.\]</span> A vector of length <span class="math inline">\(0\)</span> is the zero vector, so <span class="math inline">\(Ax = 0\)</span>. Hence every <span class="math inline">\(x\)</span> killed by <span class="math inline">\(A^TA\)</span> is killed by <span class="math inline">\(A\)</span>: <span class="math inline">\(N(A^TA) \subseteq N(A)\)</span>. (The reverse inclusion is immediate: <span class="math inline">\(Ax = 0 \Rightarrow A^TAx = A^T0 = 0\)</span>.) The two null spaces are equal, so by rank–nullity (§4.8) <span class="math inline">\(A\)</span> and <span class="math inline">\(A^TA\)</span> have the same rank.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 4 — <span class="math display">\[A = \begin{pmatrix} 1 &amp; 0 \\ 1 &amp; 1 \\ 1 &amp; 2 \end{pmatrix}, \quad Y = \begin{pmatrix} 0 \\ 2 \\ 3 \end{pmatrix}, \quad A^TA = \begin{pmatrix} 3 &amp; 3 \\ 3 &amp; 5 \end{pmatrix}, \quad A^TY = \begin{pmatrix} 5 \\ 8 \end{pmatrix}.\]</span>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>4.</strong> <span class="math display">\[A = \begin{pmatrix} 1 &amp; 0 \\ 1 &amp; 1 \\ 1 &amp; 2 \end{pmatrix}, \quad Y = \begin{pmatrix} 0 \\ 2 \\ 3 \end{pmatrix}, \quad A^TA = \begin{pmatrix} 3 &amp; 3 \\ 3 &amp; 5 \end{pmatrix}, \quad A^TY = \begin{pmatrix} 5 \\ 8 \end{pmatrix}.\]</span> <span class="math inline">\(\det(A^TA) = 15 - 9 = 6 \ne 0\)</span> (independent columns — §23.5): <span class="math display">\[\hat\theta = \frac{1}{6}\begin{pmatrix} 5 &amp; -3 \\ -3 &amp; 3 \end{pmatrix}\!\begin{pmatrix} 5 \\ 8 \end{pmatrix} = \frac{1}{6}\begin{pmatrix} 25-24 \\ -15+24 \end{pmatrix} = \begin{pmatrix} 1/6 \\ 3/2 \end{pmatrix}.\]</span> <span class="math display">\[\boxed{f(x) = \tfrac32x + \tfrac16}.\]</span> Predictions: <span class="math inline">\(\tfrac16, \tfrac{10}{6}, \tfrac{19}{6}\)</span>; residuals (pred − <span class="math inline">\(y\)</span>): <span class="math inline">\(\tfrac16, -\tfrac13, \tfrac16\)</span>. Minimum squared error: <span class="math display">\[\|A\hat\theta - Y\|^2 = \frac{1}{36} + \frac{4}{36} + \frac{1}{36} = \frac{6}{36} = \boxed{\frac16}.\]</span> (And <span class="math inline">\(Y \notin C(A)\)</span> — no line hits all three points — so this is genuinely the least-squares compromise, §5.8.)</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 5 — i) From §23.3, <span class="math inline">\(\nabla L = A^T(A\theta - Y)\)</span>, which is linear in <span class="math inline">\(\theta\)</span>; differentiating once more:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>5.</strong> (i) From §23.3, <span class="math inline">\(\nabla L = A^T(A\theta - Y)\)</span>, which is linear in <span class="math inline">\(\theta\)</span>; differentiating once more: <span class="math display">\[\nabla^2 L = A^TA.\]</span> (ii) For any <span class="math inline">\(z\)</span>: <span class="math inline">\(z^T(A^TA)z = (Az)^T(Az) = \|Az\|^2 \ge 0\)</span> — positive semidefinite, so <span class="math inline">\(L\)</span> is convex (§12.7’s second-order test). (iii) A stationary point of a convex function is a global minimum (§12.9): the <span class="math inline">\(\hat\theta\)</span> solving the normal equations minimizes <span class="math inline">\(L\)</span> over all of <span class="math inline">\(\mathbb{R}^d\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 6 — i) <span class="math display">\[\tilde A = \begin{pmatrix} 1 &amp; 0 &amp; 0 \\ 1 &amp; 1 &amp; 1 \\ 1 &amp; 2 &amp; 4 \end{pmatrix}, \qquad Y = \begin{pmatrix} 2 \\ 1 \\ 2 \end{pmatrix}.\]</span>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>6.</strong> (i) <span class="math display">\[\tilde A = \begin{pmatrix} 1 &amp; 0 &amp; 0 \\ 1 &amp; 1 &amp; 1 \\ 1 &amp; 2 &amp; 4 \end{pmatrix}, \qquad Y = \begin{pmatrix} 2 \\ 1 \\ 2 \end{pmatrix}.\]</span> (ii) <span class="math inline">\(\tilde A^T\tilde A = \begin{pmatrix} 3&amp;3&amp;5 \\ 3&amp;5&amp;9 \\ 5&amp;9&amp;17 \end{pmatrix}\)</span>, <span class="math inline">\(\tilde A^TY = \begin{pmatrix} 5 \\ 5 \\ 9 \end{pmatrix}\)</span> (sums: <span class="math inline">\(2+1+2 = 5\)</span>; <span class="math inline">\(0+1+4 = 5\)</span>; <span class="math inline">\(0+1+8 = 9\)</span>): <span class="math display">\[\begin{cases} 3\theta_0+3\theta_1+5\theta_2 = 5 \\ 3\theta_0+5\theta_1+9\theta_2 = 5 \\ 5\theta_0+9\theta_1+17\theta_2 = 9 \end{cases}.\]</span> (iii) Try <span class="math inline">\(\theta = (2,-2,1)^T\)</span>: <span class="math inline">\(6-6+5 = 5\)</span> ✓; <span class="math inline">\(6-10+9 = 5\)</span> ✓; <span class="math inline">\(10-18+17 = 9\)</span> ✓. <span class="math inline">\(\tilde A\)</span> has distinct <span class="math inline">\(x\)</span>’s (Vandermonde — full rank), so the solution is unique: <span class="math inline">\(\boxed{\hat y = 2 - 2x + x^2}\)</span>. Check on the data: <span class="math inline">\(2-0+0 = 2\)</span> ✓; <span class="math inline">\(2-2+1 = 1\)</span> ✓; <span class="math inline">\(2-4+4 = 2\)</span> ✓. (iv) Three parameters, three points, full-rank design matrix — the quadratic interpolates exactly (eg 3’s lesson): <span class="math inline">\(m = n-1\)</span> can always thread every point, so the residual is <span class="math inline">\(0\)</span>. (Whether that’s wise is §23.9’s question.)</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 7 — i) <strong>True</strong>: <span class="math inline">\((A^TA)^T = A^T(A^T)^T = A^TA\)</span>. (ii) <strong>True</strong>: full column rank ⇒ <span class="math inline">\(A^TA\)</span> invertible (§23.5) ⇒ exactly one <span class="math inline">\(\hat\theta\)</span>. (iii) <strong>True</strong>: the degree-<span class="math inline">\(m\)</span> family contains the degree-<span class="math inline">\((m-1)\)</span> family (pad extra <span class="math inline">\(\theta_j = 0\)</span>), and minimizing over a bigger set can’t give a bigger minimum. (iv) <strong>False</strong>: eg 4 — test MSE rose <span class="math inline">\(0.0030 \to 0.0191\)</span> from <span class="math inline">\(m = 2\)</span> to <span class="math inline">\(m = 4\)</span>. That’s overfitting.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>7.</strong> (i) <strong>True</strong>: <span class="math inline">\((A^TA)^T = A^T(A^T)^T = A^TA\)</span>. (ii) <strong>True</strong>: full column rank ⇒ <span class="math inline">\(A^TA\)</span> invertible (§23.5) ⇒ exactly one <span class="math inline">\(\hat\theta\)</span>. (iii) <strong>True</strong>: the degree-<span class="math inline">\(m\)</span> family contains the degree-<span class="math inline">\((m-1)\)</span> family (pad extra <span class="math inline">\(\theta_j = 0\)</span>), and minimizing over a bigger set can’t give a bigger minimum. (iv) <strong>False</strong>: eg 4 — test MSE rose <span class="math inline">\(0.0030 \to 0.0191\)</span> from <span class="math inline">\(m = 2\)</span> to <span class="math inline">\(m = 4\)</span>. That’s overfitting.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 8 — i) <span class="math inline">\(A^TA = \begin{pmatrix} 3&amp;6 \\ 6&amp;14 \end{pmatrix}\)</span>, <span class="math inline">\(\det = 42-36 = 6 \ne 0\)</span> — <strong>exists</strong>. ML reading: intercept and <span class="math inline">\(x\)</span> are independent features; both coefficients are pinned down.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>8.</strong> (i) <span class="math inline">\(A^TA = \begin{pmatrix} 3&amp;6 \\ 6&amp;14 \end{pmatrix}\)</span>, <span class="math inline">\(\det = 42-36 = 6 \ne 0\)</span> — <strong>exists</strong>. ML reading: intercept and <span class="math inline">\(x\)</span> are independent features; both coefficients are pinned down. (ii) <span class="math inline">\(A^TA = \begin{pmatrix} 3&amp;9&amp;9 \\ 9&amp;29&amp;29 \\ 9&amp;29&amp;29 \end{pmatrix}\)</span> — columns 2 and 3 identical, rank <span class="math inline">\(\le 2 &lt; 3\)</span>, singular — <strong>no inverse</strong>. ML reading: the “feature” was duplicated; the model can’t decide how to split credit between <span class="math inline">\(\theta_2\)</span> and <span class="math inline">\(\theta_3\)</span> (any shift <span class="math inline">\(\theta_2 \to \theta_2 + t\)</span>, <span class="math inline">\(\theta_3 \to \theta_3 - t\)</span> gives identical predictions). (iii) <span class="math inline">\(A^TA = \begin{pmatrix} 14&amp;0 \\ 0&amp;0 \end{pmatrix}\)</span>, <span class="math inline">\(\det = 0\)</span> — <strong>no inverse</strong>. ML reading: the always-<span class="math inline">\(0\)</span> feature contributes nothing to any prediction, so its coefficient is completely free.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 9 — i) <strong><span class="math inline">\(m = 2\)</span></strong> — decided on the <strong>validation</strong> MSE (<span class="math inline">\(0.01\)</span>, the smallest column-3 entry). The training column was only for fitting; the degree is model selection (§23.9). (ii) <strong>Overfitting</strong>: train MSE <span class="math inline">\(0.00\)</span> (memorized) but validation MSE <span class="math inline">\(0.09\)</span> (worst of the four). (iii) The <strong>test</strong> split’s number — on data untouched by both fitting and selection. The validation number is already optimistic (it chose the winner); §22.10’s three-way split exists exactly so the reported number is honest.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>9.</strong> (i) <strong><span class="math inline">\(m = 2\)</span></strong> — decided on the <strong>validation</strong> MSE (<span class="math inline">\(0.01\)</span>, the smallest column-3 entry). The training column was only for fitting; the degree is model selection (§23.9). (ii) <strong>Overfitting</strong>: train MSE <span class="math inline">\(0.00\)</span> (memorized) but validation MSE <span class="math inline">\(0.09\)</span> (worst of the four). (iii) The <strong>test</strong> split’s number — on data untouched by both fitting and selection. The validation number is already optimistic (it chose the winner); §22.10’s three-way split exists exactly so the reported number is honest.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 10 — i) Each <span class="math inline">\(y^i \mid x^i \sim N(\theta^Tx^i, \sigma^2)\)</span>, independent:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>10.</strong> (i) Each <span class="math inline">\(y^i \mid x^i \sim N(\theta^Tx^i, \sigma^2)\)</span>, independent: <span class="math display">\[L(\theta) = \prod_{i=1}^{n}\frac{1}{\sqrt{2\pi\sigma^2}}\exp\!\left(-\frac{(y^i - \theta^Tx^i)^2}{2\sigma^2}\right).\]</span> (ii) <span class="math display">\[\ell(\theta) = \log L(\theta) = -\frac{n}{2}\log(2\pi\sigma^2) - \frac{1}{2\sigma^2}\sum_{i=1}^{n}(y^i - \theta^Tx^i)^2.\]</span> (iii) The first term doesn’t involve <span class="math inline">\(\theta\)</span>, and <span class="math inline">\(1/(2\sigma^2) &gt; 0\)</span>, so <span class="math display">\[\arg\max_\theta \ell(\theta) = \arg\min_\theta \sum_{i=1}^{n}(y^i - \theta^Tx^i)^2,\]</span> the least-squares objective (§23.1). Maximum likelihood under Gaussian noise <strong>is</strong> least squares — §20.8’s result, §23.6’s meaning.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./22-what-is-ml.html" class="pagination-link" aria-label="22. What is ML: data, models, tasks; supervised vs unsupervised">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">22. What is ML: data, models, tasks; supervised vs unsupervised</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./24-pca.html" class="pagination-link" aria-label="24. PCA: variance maximization, eigendecomposition, kernel PCA">
        <span class="nav-page-text"><span class="chapter-title">24. PCA: variance maximization, eigendecomposition, kernel PCA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>