<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>29. KNN and decision trees – Foundations to Deep Learning</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./30-naive-bayes.html" rel="next">
<link href="./28-regularization.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-968ddd4980072ae063619731fc79ef1d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./26-k-means.html">Part IV — Machine Learning Techniques</a></li><li class="breadcrumb-item"><a href="./29-knn-trees.html"><span class="chapter-title">29. KNN and decision trees</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundations to Deep Learning</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Foundations to Deep Learning</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Mathematical Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-sets-functions-preliminaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 1 — Sets, functions, and mathematical preliminaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-vectors-and-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2. Vectors and matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-linear-systems-determinants-inverses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3. Linear systems, determinants, inverses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-vector-spaces-four-subspaces.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4. Vector spaces and the four fundamental subspaces</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-orthogonality-projections-least-squares.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5. Orthogonality, projections, least squares</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-eigenvalues-eigenvectors-diagonalization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6. Eigenvalues, eigenvectors, diagonalization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-svd-positive-definite.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7. SVD and positive definite matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-single-variable-calculus.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8. Single-variable calculus: continuity, differentiability, derivatives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-multivariable-calculus.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9. Multivariable calculus: partial derivatives, gradients, Taylor series</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-unconstrained-optimization-gradient-descent.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10. Unconstrained optimization and gradient descent</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-constrained-optimization-lagrange.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11. Constrained optimization: Lagrange multipliers, projected gradient descent</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-convex-sets-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12. Convex sets and convex functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-duality-kkt.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13. Duality and KKT conditions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Probability and Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-probability-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14. Probability basics: experiments, sample spaces, Bayes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-discrete-random-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15. Discrete random variables and key distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-continuous-random-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16. Continuous random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-joint-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17. Joint distributions: two random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-joint-continuous-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18. Joint continuous distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-random-vectors-multivariate-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19. Random vectors and the multivariate normal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-estimation-mle-map.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20. Estimation: MLE and Bayesian/MAP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-inequalities-clt.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21. Inequalities and the central limit theorem</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III — Machine Learning Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-what-is-ml.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22. What is ML: data, models, tasks; supervised vs unsupervised</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-linear-polynomial-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">23. Linear and polynomial regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-pca.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">24. PCA: variance maximization, eigendecomposition, kernel PCA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-gmm-em.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">25. GMMs and the EM algorithm</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV — Machine Learning Techniques</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-k-means.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26. K-means clustering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-kernel-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27. Kernel methods and kernel regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-regularization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28. Regularization: ridge and lasso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29-knn-trees.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">29. KNN and decision trees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-naive-bayes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30. Naive Bayes: generative vs discriminative models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-perceptron-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31. Perceptron and logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32-hard-margin-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 32: Hard-margin SVM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33-soft-margin-kernel-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 33: Soft-margin SVM and the kernel trick</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34-ensembles.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 34: Ensembles — bagging, boosting, AdaBoost</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./35-loss-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 35: Loss functions for classification</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Part V — Machine Learning in Practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./36-numpy-pandas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 36: NumPy and Pandas for ML</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./37-sklearn-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 37: scikit-learn: regression workflows</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./38-sklearn-classification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 38: scikit-learn: classification workflows</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./39-model-evaluation-cv.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 39: Model evaluation, cross-validation, hyperparameter tuning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40-end-to-end-debugging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 40: End-to-end model training and debugging</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Part VI — Bridge to Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41-neuron-mlp-scratch.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 41: The artificial neuron and MLPs from scratch</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42-backpropagation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 42: Backpropagation, worked end-to-end</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43-optimization-neural-nets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 43: Optimization for neural nets — SGD variants, init, normalization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./44-cnns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 44: CNNs — convolution, pooling, transfer learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./45-rnns-sequences-vanishing-gradients.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 45: RNNs — sequences and vanishing gradients</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./46-attention-and-transformers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 46: Attention and the transformer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./47-generative-models-gans-diffusion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 47: Generative models: GANs and diffusion</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-task-both-solve-22.9-classification" id="toc-the-task-both-solve-22.9-classification" class="nav-link active" data-scroll-target="#the-task-both-solve-22.9-classification">29.1 The task both solve: §22.9 classification</a></li>
  <li><a href="#knn-the-algorithm-no-model-just-neighbours" id="toc-knn-the-algorithm-no-model-just-neighbours" class="nav-link" data-scroll-target="#knn-the-algorithm-no-model-just-neighbours">29.2 KNN: the algorithm — no model, just neighbours</a></li>
  <li><a href="#the-distance-metric-what-near-means" id="toc-the-distance-metric-what-near-means" class="nav-link" data-scroll-target="#the-distance-metric-what-near-means">29.3 The distance metric: what “near” means</a></li>
  <li><a href="#voting-classification-and-averaging-regression" id="toc-voting-classification-and-averaging-regression" class="nav-link" data-scroll-target="#voting-classification-and-averaging-regression">29.4 Voting (classification) and averaging (regression)</a></li>
  <li><a href="#worked-3-nn-on-seven-2-d-points" id="toc-worked-3-nn-on-seven-2-d-points" class="nav-link" data-scroll-target="#worked-3-nn-on-seven-2-d-points">29.5 Worked: 3-NN on seven 2-D points</a></li>
  <li><a href="#decision-boundaries-what-k-does-to-the-shape" id="toc-decision-boundaries-what-k-does-to-the-shape" class="nav-link" data-scroll-target="#decision-boundaries-what-k-does-to-the-shape">29.6 Decision boundaries: what <span class="math inline">\(k\)</span> does to the shape</a></li>
  <li><a href="#choosing-k-28.10s-discipline-reused" id="toc-choosing-k-28.10s-discipline-reused" class="nav-link" data-scroll-target="#choosing-k-28.10s-discipline-reused">29.7 Choosing <span class="math inline">\(k\)</span>: §28.10’s discipline, reused</a></li>
  <li><a href="#knn-strengths-and-limits-as-the-lecture-lists-them" id="toc-knn-strengths-and-limits-as-the-lecture-lists-them" class="nav-link" data-scroll-target="#knn-strengths-and-limits-as-the-lecture-lists-them">29.8 KNN: strengths and limits (as the lecture lists them)</a></li>
  <li><a href="#decision-trees-recursive-partitioning" id="toc-decision-trees-recursive-partitioning" class="nav-link" data-scroll-target="#decision-trees-recursive-partitioning">29.9 Decision trees: recursive partitioning</a></li>
  <li><a href="#id3-the-greedy-top-down-algorithm" id="toc-id3-the-greedy-top-down-algorithm" class="nav-link" data-scroll-target="#id3-the-greedy-top-down-algorithm">29.10 ID3: the greedy top-down algorithm</a></li>
  <li><a href="#measuring-impurity-how-mixed-is-this-node" id="toc-measuring-impurity-how-mixed-is-this-node" class="nav-link" data-scroll-target="#measuring-impurity-how-mixed-is-this-node">29.11 Measuring impurity: how mixed is this node?</a></li>
  <li><a href="#information-gain-the-splitting-score" id="toc-information-gain-the-splitting-score" class="nav-link" data-scroll-target="#information-gain-the-splitting-score">29.12 Information gain: the splitting score</a></li>
  <li><a href="#worked-one-full-split-computation-by-hand" id="toc-worked-one-full-split-computation-by-hand" class="nav-link" data-scroll-target="#worked-one-full-split-computation-by-hand">29.13 Worked: one full split computation by hand</a></li>
  <li><a href="#the-lectures-tennis-example-numbers-verified" id="toc-the-lectures-tennis-example-numbers-verified" class="nav-link" data-scroll-target="#the-lectures-tennis-example-numbers-verified">29.14 The lecture’s tennis example (numbers verified)</a></li>
  <li><a href="#cart-regression-trees-constants-per-region" id="toc-cart-regression-trees-constants-per-region" class="nav-link" data-scroll-target="#cart-regression-trees-constants-per-region">29.15 CART: regression trees — constants per region</a></li>
  <li><a href="#classification-trees-swap-the-loss-keep-the-growing" id="toc-classification-trees-swap-the-loss-keep-the-growing" class="nav-link" data-scroll-target="#classification-trees-swap-the-loss-keep-the-growing">29.16 Classification trees: swap the loss, keep the growing</a></li>
  <li><a href="#overfitting-deep-trees-memorize" id="toc-overfitting-deep-trees-memorize" class="nav-link" data-scroll-target="#overfitting-deep-trees-memorize">29.17 Overfitting: deep trees memorize</a></li>
  <li><a href="#pre-pruning-stop-before-it-overgrows" id="toc-pre-pruning-stop-before-it-overgrows" class="nav-link" data-scroll-target="#pre-pruning-stop-before-it-overgrows">29.18 Pre-pruning: stop before it overgrows</a></li>
  <li><a href="#post-pruning-grow-big-then-cut-back-cost-complexity" id="toc-post-pruning-grow-big-then-cut-back-cost-complexity" class="nav-link" data-scroll-target="#post-pruning-grow-big-then-cut-back-cost-complexity">29.19 Post-pruning: grow big, then cut back (cost-complexity)</a></li>
  <li><a href="#knn-vs-decision-trees" id="toc-knn-vs-decision-trees" class="nav-link" data-scroll-target="#knn-vs-decision-trees">29.20 KNN vs decision trees</a></li>
  <li><a href="#trees-advantages-and-disadvantages-as-the-lecture-lists-them" id="toc-trees-advantages-and-disadvantages-as-the-lecture-lists-them" class="nav-link" data-scroll-target="#trees-advantages-and-disadvantages-as-the-lecture-lists-them">29.21 Trees: advantages and disadvantages (as the lecture lists them)</a></li>
  <li><a href="#where-this-goes-next" id="toc-where-this-goes-next" class="nav-link" data-scroll-target="#where-this-goes-next">29.22 Where this goes next</a></li>
  <li><a href="#problem-set" id="toc-problem-set" class="nav-link" data-scroll-target="#problem-set">Problem set</a></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions">Solutions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./26-k-means.html">Part IV — Machine Learning Techniques</a></li><li class="breadcrumb-item"><a href="./29-knn-trees.html"><span class="chapter-title">29. KNN and decision trees</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">29. KNN and decision trees</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Two classifiers from the MLT lectures, and a study in opposites. KNN (Week 7 slides) never builds a model at all — it keeps the whole training set and decides each new point by asking its neighbours. Decision trees (Week 9 slides) do the reverse: they compress the training set into an explicit set of if-then rules — a partition of the feature space — and throw the data away at prediction time. Both are §22.9 classifiers (<span class="math inline">\(f: \mathbb{R}^d \to \{\text{classes}\}\)</span>), both handle regression too (the lectures say so for each), and both carry a complexity hyperparameter — <span class="math inline">\(k\)</span> for KNN, tree size/depth for trees — chosen by exactly the discipline §28.12(ii) promised would generalize: §28.10’s candidates → validation error → retrain → test, applied to every hyperparameter, not just <span class="math inline">\(\lambda\)</span>.</p>
<p>Everything in §§29.2–29.8 comes from the MLT Week 7 KNN slides; §§29.9–29.21 from the MLT Week 9 decision-tree slides (Dr.&nbsp;Ashish Tendulkar). The hand-worked examples in §§29.5 and 29.13 use the chapter’s own tiny datasets, with every number recomputed independently (review log); the lecture’s Play-Tennis numbers in §29.14 are verified, not copied blind.</p>
<p><strong>Notation.</strong> The lectures write the <span class="math inline">\(i\)</span>-th example as <span class="math inline">\(x^{(i)}\)</span> (superscript, §22’s convention) with label <span class="math inline">\(y^{(i)}\)</span>; <span class="math inline">\(x_j^{(i)}\)</span> is feature <span class="math inline">\(j\)</span> of example <span class="math inline">\(i\)</span>. <span class="math inline">\(D = \{(x^{(i)}, y^{(i)})\}_{i=1}^n\)</span> is the training set. A tree node covers a region <span class="math inline">\(R_i\)</span> holding <span class="math inline">\(N_i\)</span> samples.</p>
<section id="the-task-both-solve-22.9-classification" class="level2">
<h2 class="anchored" data-anchor-id="the-task-both-solve-22.9-classification">29.1 The task both solve: §22.9 classification</h2>
<p><strong>Setup.</strong> Same as §22.9: instances <span class="math inline">\(x^{(i)} \in \mathbb{R}^d\)</span>, but the labels are discrete — <span class="math inline">\(\boxed{y^{(i)} \in \{1, \ldots, K\}}\)</span> for <span class="math inline">\(K\)</span> classes (the tree lectures write it this way; §22.9’s <span class="math inline">\(\pm 1\)</span> is the <span class="math inline">\(K = 2\)</span> case). The algorithm outputs <span class="math inline">\(\boxed{f: \mathbb{R}^d \to \{1, \ldots, K\}}\)</span>.</p>
<ol type="i">
<li><strong>The loss is still §22.9’s.</strong> Misclassification fraction <span class="math inline">\(L(f) = \tfrac1n \sum_i \mathbf{1}(f(x^{(i)}) \ne y^{(i)})\)</span> — fraction wrong. KNN and trees just carve the input space into class regions differently than a linear separator does: not one straight cut (§22.9), but many small local decisions.</li>
<li><strong>Both also do regression.</strong> Each lecture says so explicitly: KNN averages neighbours’ outputs (§29.4), trees fit a constant per region (§29.15). The chapter leads with classification because both lectures do.</li>
</ol>
<p><strong>Basically, …</strong> “§22.9’s game — predict a discrete label, count your mistakes — played two new ways: KNN asks ‘who are this point’s neighbours?’, trees ask ‘which box does this point fall in?’.”</p>
</section>
<section id="knn-the-algorithm-no-model-just-neighbours" class="level2">
<h2 class="anchored" data-anchor-id="knn-the-algorithm-no-model-just-neighbours">29.2 KNN: the algorithm — no model, just neighbours</h2>
<p><strong>Def (k-nearest neighbours).</strong> KNN is a <strong>supervised</strong> algorithm for classification and regression. It is an <strong>instance-based</strong> learning technique: <strong>there is no explicit model</strong>. To label a new example, KNN compares it with the existing training examples, finds the <span class="math inline">\(k\)</span> <strong>nearest neighbours</strong>, and assigns an output based on those neighbours’ labels.</p>
<ol type="i">
<li><strong>The key insight</strong> (the lecture’s one-liner): <em>“An example is labeled by the company it keeps.”</em> A new point inherits the majority opinion of its neighbourhood.</li>
<li><strong>Two hyperparameters</strong> (the lecture names exactly two): <strong>how many neighbours (<span class="math inline">\(k\)</span>)</strong> to consult, and <strong>which distance metric</strong> to compare examples with (§29.3).</li>
<li><strong>Nothing is learned up front.</strong> Training = storing the dataset. All the work happens when a prediction is requested — the lecture’s limitation (i) in §29.8 is exactly this.</li>
</ol>
<p><strong>Basically, …</strong> “KNN doesn’t study for the exam — it brings the textbook into the hall. New point arrives, it measures distances to every stored point, takes a vote among the <span class="math inline">\(k\)</span> closest, done. The only decisions you make: how many voters (<span class="math inline">\(k\)</span>) and what ‘close’ means (the metric).”</p>
</section>
<section id="the-distance-metric-what-near-means" class="level2">
<h2 class="anchored" data-anchor-id="the-distance-metric-what-near-means">29.3 The distance metric: what “near” means</h2>
<p>Following the lecture, the two metrics used quite often, for points <span class="math inline">\(x^{(1)}, x^{(2)}\)</span> with <span class="math inline">\(m\)</span> features:</p>
<p><strong>Def (Euclidean distance).</strong> <span class="math display">\[\boxed{\delta(x^{(1)}, x^{(2)}) = \sqrt{(x_1^{(1)} - x_1^{(2)})^2 + \cdots + (x_m^{(1)} - x_m^{(2)})^2} = \left(\sum_{j=1}^{m} (x_j^{(1)} - x_j^{(2)})^2\right)^{\!1/2}}\]</span> Vectorized: <span class="math inline">\(\boxed{\delta = \big((x^{(1)} - x^{(2)})^T (x^{(1)} - x^{(2)})\big)^{1/2}}\)</span> — the ordinary straight-line distance, §2-style.</p>
<p><strong>Def (Manhattan distance).</strong> <span class="math display">\[\boxed{\delta(x^{(1)}, x^{(2)}) = |x_1^{(1)} - x_1^{(2)}| + \cdots + |x_m^{(1)} - x_m^{(2)}| = \sum_{j=1}^{m} |x_j^{(1)} - x_j^{(2)}|}\]</span> Vectorized (the lecture’s form): <span class="math inline">\(\boxed{\delta = \mathbf{1}_{1 \times m}^T\, |x^{(1)} - x^{(2)}|_{m \times 1}}\)</span> — sum of absolute per-feature gaps: the “city-block” walk, no diagonals.</p>
<ol type="i">
<li><strong>The metric is a hyperparameter</strong> (§29.2(ii)): the lecture lists it alongside <span class="math inline">\(k\)</span>, with no selection procedure given — in practice it joins <span class="math inline">\(k\)</span> in the §29.7 audition (Problem 2 shows it can flip a prediction).</li>
<li><strong>Every feature counts</strong> — which is also the sensitivity the lecture warns about (§29.8): all <span class="math inline">\(m\)</span> features enter the sum, relevant or not.</li>
</ol>
<p><strong>eg 1 (both metrics, one pair).</strong> <span class="math inline">\(x^{(1)} = (1, 2)\)</span>, <span class="math inline">\(x^{(2)} = (4, 6)\)</span>: Euclidean <span class="math inline">\(\sqrt{9 + 16} = \boxed{5}\)</span>; Manhattan <span class="math inline">\(|{-3}| + |{-4}| = \boxed{7}\)</span>.</p>
<p><strong>Basically, …</strong> “Euclidean = as the crow flies (square each gap, add, square-root). Manhattan = as the taxi drives (add the raw gaps). Both turn ‘how alike are these two examples?’ into one number — and that number is the whole algorithm’s raw material.”</p>
</section>
<section id="voting-classification-and-averaging-regression" class="level2">
<h2 class="anchored" data-anchor-id="voting-classification-and-averaging-regression">29.4 Voting (classification) and averaging (regression)</h2>
<p><strong>Classification.</strong> The <span class="math inline">\(k\)</span> neighbours take part in voting; <strong>the class that receives the highest number of votes is the predicted class</strong> (majority vote).</p>
<p><strong>Regression.</strong> The prediction is the <strong>average</strong> of the neighbours’ outputs: <span class="math display">\[\boxed{\hat y = \frac{1}{k}\sum_{i=1}^{k} y_i}.\]</span></p>
<p><strong>eg 2 (regression, by hand).</strong> A new house’s <span class="math inline">\(k = 3\)</span> nearest neighbours (by area, bedrooms, …) sold for <span class="math inline">\(2.0\)</span>, <span class="math inline">\(3.5\)</span>, <span class="math inline">\(6.5\)</span> (₹ crore): <span class="math inline">\(\hat y = \tfrac13(2.0 + 3.5 + 6.5) = \boxed{4.0}\)</span>.</p>
<ol type="i">
<li><strong>Vote for labels, average for numbers.</strong> Discrete <span class="math inline">\(y^{(i)}\)</span> → count; real <span class="math inline">\(y^{(i)}\)</span> → mean. Same neighbours, different aggregation.</li>
<li><strong>Ties are the lecture’s silence.</strong> With even <span class="math inline">\(k\)</span> (or <span class="math inline">\(k \to n\)</span> on balanced classes) the vote can tie; the slides prescribe no tie-break — flagged in the review log, and the chapter’s examples keep strict majorities.</li>
</ol>
<p><strong>Basically, …</strong> “Classification: the neighbours vote, majority wins. Regression: the neighbours’ numbers get averaged. That’s the entire ‘model’ — there isn’t one.”</p>
</section>
<section id="worked-3-nn-on-seven-2-d-points" class="level2">
<h2 class="anchored" data-anchor-id="worked-3-nn-on-seven-2-d-points">29.5 Worked: 3-NN on seven 2-D points</h2>
<p>Data (class <span class="math inline">\(A\)</span> = blue, <span class="math inline">\(B\)</span> = red), query points <span class="math inline">\(q = (2,2)\)</span>, <span class="math inline">\(q_2 = (4,2)\)</span>: <span class="math display">\[A_1=(0,0),\; A_2=(1,4),\; A_3=(3,1),\qquad B_1=(5,2),\; B_2=(4,5),\; B_3=(6,3),\; B_4=(7,2).\]</span> Euclidean distance, squared (comparing squares orders the same as roots):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>neighbour</th>
<th><span class="math inline">\(d^2(q, \cdot)\)</span></th>
<th><span class="math inline">\(d^2(q_2, \cdot)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(A_1\)</span></td>
<td><span class="math inline">\((2)^2+(2)^2 = 8\)</span></td>
<td><span class="math inline">\((4)^2+(2)^2 = 20\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(A_2\)</span></td>
<td><span class="math inline">\((1)^2+(2)^2 = 5\)</span></td>
<td><span class="math inline">\((3)^2+(2)^2 = 13\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(A_3\)</span></td>
<td><span class="math inline">\((1)^2+(1)^2 = 2\)</span></td>
<td><span class="math inline">\((1)^2+(1)^2 = 2\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(B_1\)</span></td>
<td><span class="math inline">\((3)^2+(0)^2 = 9\)</span></td>
<td><span class="math inline">\((1)^2+(0)^2 = 1\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(B_2\)</span></td>
<td><span class="math inline">\((2)^2+(3)^2 = 13\)</span></td>
<td><span class="math inline">\((0)^2+(3)^2 = 9\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(B_3\)</span></td>
<td><span class="math inline">\((4)^2+(1)^2 = 17\)</span></td>
<td><span class="math inline">\((2)^2+(1)^2 = 5\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(B_4\)</span></td>
<td><span class="math inline">\((5)^2+(0)^2 = 25\)</span></td>
<td><span class="math inline">\((3)^2+(0)^2 = 9\)</span></td>
</tr>
</tbody>
</table>
<p><strong>The <span class="math inline">\(k = 3\)</span> vote.</strong> For <span class="math inline">\(q\)</span>: nearest are <span class="math inline">\(A_3\)</span> (<span class="math inline">\(2\)</span>), <span class="math inline">\(A_2\)</span> (<span class="math inline">\(5\)</span>), <span class="math inline">\(A_1\)</span> (<span class="math inline">\(8\)</span>) — three <span class="math inline">\(A\)</span> votes → <span class="math inline">\(\boxed{\text{predict } A}\)</span>. For <span class="math inline">\(q_2\)</span>: nearest are <span class="math inline">\(B_1\)</span> (<span class="math inline">\(1\)</span>), <span class="math inline">\(A_3\)</span> (<span class="math inline">\(2\)</span>), <span class="math inline">\(B_3\)</span> (<span class="math inline">\(5\)</span>) — two <span class="math inline">\(B\)</span>, one <span class="math inline">\(A\)</span> → <span class="math inline">\(\boxed{\text{predict } B}\)</span>.</p>
<p><strong>Boundary reasoning.</strong> Every plane point gets the majority label of its 3 nearest training points, so the plane splits into an <span class="math inline">\(A\)</span>-region (around the blue cluster) and a <span class="math inline">\(B\)</span>-region (around the reds) — the shaded regions in the figure. <span class="math inline">\(q\)</span> sits inside <span class="math inline">\(A\)</span>’s region, <span class="math inline">\(q_2\)</span> inside <span class="math inline">\(B\)</span>’s; the boundary threads between them.</p>
<!-- Original matplotlib illustration drawn for this chapter (not reused from any URL): the seven training points of the worked example with 1-NN vs 5-NN decision regions, query points q and q2, and q's three nearest neighbours circled -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/29-knn-example.png" class="img-fluid figure-img"></p>
<figcaption>Two panels: 1-NN (left) and 5-NN (right) decision regions on the seven training points of the worked example (blue=A, red=B); query stars q=(2,2) in the blue region and q2=(4,2) in the red region; q’s three nearest neighbours (all A) circled with dashes. The 1-NN boundary is jagged and intricate; the 5-NN boundary is smoother.</figcaption>
</figure>
</div>
<p><strong>Basically, …</strong> “Measure seven distances, sort, take the top three, count the colours. <span class="math inline">\(q\)</span>’s three closest are all blue — lands in the blue zone. <span class="math inline">\(q_2\)</span>’s are two red, one blue — lands red. The coloured zones in the figure are just this vote repeated for every point of the plane.”</p>
</section>
<section id="decision-boundaries-what-k-does-to-the-shape" class="level2">
<h2 class="anchored" data-anchor-id="decision-boundaries-what-k-does-to-the-shape">29.6 Decision boundaries: what <span class="math inline">\(k\)</span> does to the shape</h2>
<p>Run the §29.5 vote at every plane point and the class regions emerge — the <strong>decision boundary</strong> is where the vote flips. The lecture’s panels (boundaries for <span class="math inline">\(k = 9, \ldots, 16\)</span> on its demo data) and the figure above agree on the pattern:</p>
<ol type="i">
<li><strong>Small <span class="math inline">\(k\)</span> (<span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span>): jagged, overfit.</strong> The model is <strong>sensitive to noise</strong> — it adjusts to tiny wiggles in the data, and the boundary turns very jagged (left panel above: each training point carves its own intricate cell).</li>
<li><strong>Large <span class="math inline">\(k\)</span>: smooth, underfit.</strong> The model gets <strong>biased</strong> — it ignores the underlying trend, and the boundary smooths out (right panel: one calm curve).</li>
<li><strong><span class="math inline">\(k \to n\)</span>: majority rules everything.</strong> As <span class="math inline">\(k\)</span> approaches the dataset size, the neighbourhood <em>is</em> the dataset, so the model predicts the <strong>majority class for every possible example</strong> — on §29.5’s data (<span class="math inline">\(3\)</span> <span class="math inline">\(A\)</span> vs <span class="math inline">\(4\)</span> <span class="math inline">\(B\)</span>), <span class="math inline">\(k = 7\)</span> labels the entire plane <span class="math inline">\(B\)</span>.</li>
</ol>
<p><strong>Note (the <span class="math inline">\(k = 1\)</span> boundary, the book’s own observation — not a lecture claim).</strong> With <span class="math inline">\(k = 1\)</span> each plane point takes the label of its single nearest training point, so the boundary is exactly the Voronoi tessellation of the training set: each point owns the cell of plane closest to it. “Voronoi-like” is this, softened for larger <span class="math inline">\(k\)</span> — every KNN boundary is <strong>piecewise</strong>, built from distance comparisons, never a single straight cut like §22.9’s separator.</p>
<p><strong>Basically, …</strong> “<span class="math inline">\(k\)</span> is a smoothness knob. Twist it to 1: the boundary hugs every training point, noise included — jagged memorization. Twist it up: the boundary relaxes into a smooth curve — and at the extreme it gives up and calls everything the majority class. Small <span class="math inline">\(k\)</span> overfits, large <span class="math inline">\(k\)</span> underfits: the same U-story as §28.9’s <span class="math inline">\(\lambda\)</span>.”</p>
</section>
<section id="choosing-k-28.10s-discipline-reused" class="level2">
<h2 class="anchored" data-anchor-id="choosing-k-28.10s-discipline-reused">29.7 Choosing <span class="math inline">\(k\)</span>: §28.10’s discipline, reused</h2>
<p><span class="math inline">\(k\)</span> is a hyperparameter (§29.2(ii)) — so §28.12(ii) applies verbatim: run §28.10’s four steps with <span class="math inline">\(k\)</span> in <span class="math inline">\(\lambda\)</span>’s seat:</p>
<ol type="1">
<li><strong>Candidates</strong> — a grid of <span class="math inline">\(k\)</span> values (<span class="math inline">\(1, 2, \ldots\)</span>).</li>
<li><strong>Validation error</strong> — train (store) on the training split, score each <span class="math inline">\(k\)</span> on held-out data; pick the <span class="math inline">\(k\)</span> with the <strong>least validation error</strong>.</li>
<li><strong>Retrain</strong> on the full training set with the winning <span class="math inline">\(k\)</span>.</li>
<li><strong>Report</strong> on the test set, untouched until now.</li>
</ol>
<ol type="i">
<li><strong>The lecture’s chart is this procedure’s output.</strong> Its “Error vs <span class="math inline">\(k\)</span>” plot (error rate against <span class="math inline">\(k = 1, \ldots, 16\)</span>) dips and rises; the lecture’s rule: <em>“The value <span class="math inline">\(k\)</span> that yields minimum test error is most suitable.”</em></li>
<li><strong>“Test” vs “validation” — a wording note.</strong> The slide says <em>test</em> error; the book’s standing discipline (§22.10, §28.10) selects on <em>validation</em> data and reserves the test set for the final report — selecting on the test set would spend it. The curve’s shape and the rule’s spirit are the lecture’s; the split hygiene is §28.10’s (flagged in the review log).</li>
</ol>
<p><strong>Basically, …</strong> “Don’t guess <span class="math inline">\(k\)</span> — audition <span class="math inline">\(1, 2, 3, \ldots\)</span> on held-out data and hire the one with the smallest error, exactly the §28.10 ritual from the <span class="math inline">\(\lambda\)</span> chapter. The error-vs-<span class="math inline">\(k\)</span> curve is the audition scorecard.”</p>
</section>
<section id="knn-strengths-and-limits-as-the-lecture-lists-them" class="level2">
<h2 class="anchored" data-anchor-id="knn-strengths-and-limits-as-the-lecture-lists-them">29.8 KNN: strengths and limits (as the lecture lists them)</h2>
<p><strong>Advantages.</strong> i) <strong>Easy to understand and implement</strong> — the whole algorithm is §29.2–§29.4. ii) <strong>Interpretable predictions</strong> — a prediction can be <em>explained by its neighbours</em> (“you’re class <span class="math inline">\(A\)</span> because your 3 nearest stored examples are <span class="math inline">\(A\)</span>”).</p>
<p><strong>Limitations.</strong> i) <strong>Slow at prediction time on large training sets</strong> — all computations are performed at runtime (§29.2(iii)): every query measures distance to every stored point. ii) <strong>Sensitive to redundant or irrelevant features</strong> — all <span class="math inline">\(m\)</span> features enter the distance sum (§29.3(ii)), so junk features vote as loudly as signal. iii) <strong>Outperformed on hard tasks</strong> — on significantly difficult problems it can lose to SVMs and neural networks (the lecture’s words).</p>
<p><strong>Basically, …</strong> “KNN’s pitch: trivial to build, and every answer comes with its receipts (the neighbours). KNN’s price: it does all its work at query time, it can’t tell signal features from noise, and on genuinely hard problems the heavy machinery wins.”</p>
</section>
<section id="decision-trees-recursive-partitioning" class="level2">
<h2 class="anchored" data-anchor-id="decision-trees-recursive-partitioning">29.9 Decision trees: recursive partitioning</h2>
<p><strong>Def.</strong> Decision trees are <strong>non-parametric supervised</strong> methods for classification and regression. <strong>Tree-based methods partition the feature space into a set of rectangles (or cuboids) and then fit a simple model (like a constant) in each one.</strong> Conceptually simple yet powerful; a <strong>binary</strong> tree splits into two branches at each node.</p>
<ol type="i">
<li><strong>Partition, then predict.</strong> The tree asks a sequence of yes/no questions about the features; each root-to-leaf path carves out one rectangle of feature space, and every point landing in the same leaf gets the same prediction (majority class, or region mean — §§29.13, 29.15).</li>
<li><strong>Non-parametric</strong> = no fixed parameter vector sized by the modeller: the tree’s shape <em>is</em> the model, and it grows with the data (contrast §23’s fixed <span class="math inline">\(w\)</span>).</li>
<li><strong>Three questions drive everything</strong> (the lecture poses them up front): <strong>which attribute</strong> to split on? <strong>what splitting criterion</strong>? <strong>what tree size</strong> is optimal? — §§29.10–29.12, §29.16, and §§29.17–29.19 answer them in order.</li>
</ol>
<p><strong>Basically, …</strong> “A decision tree plays twenty questions with the features: ‘is outlook sunny?’ → yes → ‘is humidity high?’ → … Each answer narrows down a rectangle of the feature space until the tree reaches a leaf and announces the verdict for everyone inside that box. The learning is choosing the questions.”</p>
</section>
<section id="id3-the-greedy-top-down-algorithm" class="level2">
<h2 class="anchored" data-anchor-id="id3-the-greedy-top-down-algorithm">29.10 ID3: the greedy top-down algorithm</h2>
<p>Most tree-learning algorithms are variations of one core algorithm, <strong>ID3</strong> (Iterative Dichotomizer 3). It employs a <strong>top-down, greedy search</strong> through the space of possible trees.</p>
<p><strong>The procedure.</strong> Start with the question <em>“which attribute should be tested at the root of the tree?”</em> — each attribute is evaluated with some measure of how well it alone classifies the training examples (§§29.11–29.12): 1. <strong>Select the best attribute</strong>, split at the root node. 2. <strong>Create one descendant per possible value</strong> of that attribute; send each training example to the matching descendant. 3. <strong>Repeat recursively</strong> on each descendant’s examples — pick the best attribute for <em>that</em> subset, split again.</p>
<ol type="i">
<li><strong>Greedy = never backtracks.</strong> Once an attribute is chosen at a node, the algorithm never reconsiders earlier choices — it takes the locally best split at every step and hopes the tree comes out acceptable.</li>
<li><strong>Stopping criterion</strong> — recursion on a subset stops when:</li>
</ol>
<ul>
<li>every element in the subset belongs to the <strong>same class</strong> → leaf, labelled with that class;</li>
<li><strong>no attributes remain</strong> but classes still mix → leaf, labelled with the <strong>most common class</strong> of the subset;</li>
<li>the subset is <strong>empty</strong> (no training example matched that attribute value).</li>
</ul>
<p><strong>Basically, …</strong> “ID3 builds the tree like you’d actually interrogate a dataset: at each node ask the single most revealing question (§29.12 scores ‘revealing’), branch on every possible answer, and repeat inside each branch. It never second-guesses an old question — greedy, one pass down. Stop when a branch is pure, out of questions, or empty.”</p>
</section>
<section id="measuring-impurity-how-mixed-is-this-node" class="level2">
<h2 class="anchored" data-anchor-id="measuring-impurity-how-mixed-is-this-node">29.11 Measuring impurity: how mixed is this node?</h2>
<p>Let <span class="math inline">\(p_{i,k}\)</span> be the <strong>proportion of data points in node <span class="math inline">\(i\)</span></strong> (region <span class="math inline">\(R_i\)</span>) <strong>assigned to class <span class="math inline">\(k\)</span></strong> (<span class="math inline">\(k = 1, \ldots, K\)</span>): <span class="math display">\[\boxed{p_{i,k} = \frac{1}{N_i}\sum_{x^{(i)} \in R_i} \mathbf{1}(y^{(i)} = k)}, \qquad N_i = \text{samples in } R_i.\]</span> Three ways to score a node’s impurity:</p>
<p><strong>Misclassification error.</strong> The fraction misclassified if the node predicts its majority class: <span class="math display">\[\boxed{Q_i(T) = 1 - p_{i,k(i)} = \frac{1}{N_i}\sum_{x^{(i)} \in R_i} \mathbf{1}(y^{(i)} \ne k(i))}, \qquad k(i) = \arg\max_k p_{i,k}.\]</span></p>
<p><strong>Gini index.</strong> <span class="math display">\[\boxed{G_i = \sum_{k=1}^{K} p_{i,k}(1 - p_{i,k})}\]</span> Two readings (both the lecture’s): (a) instead of predicting the majority class, predict class <span class="math inline">\(k\)</span> <strong>with probability</strong> <span class="math inline">\(p_{i,k}\)</span> — the training error rate of that randomized rule <em>is</em> the Gini index; (b) code each observation as <span class="math inline">\(1\)</span> for class <span class="math inline">\(k\)</span> and <span class="math inline">\(0\)</span> otherwise — the variance of that 0–1 response over the node is <span class="math inline">\(p_{i,k}(1 - p_{i,k})\)</span>, and summing over classes gives Gini again.</p>
<p><strong>Entropy.</strong> <span class="math display">\[\boxed{H_i = -\sum_{k=1}^{K} p_{i,k}\log_2 p_{i,k}}\]</span> <span class="math inline">\(0\)</span> for a pure node, maximal (<span class="math inline">\(\log_2 K\)</span>) for a perfectly mixed one.</p>
<ol type="i">
<li><strong>All three are <span class="math inline">\(0\)</span> iff the node is pure</strong> and grow as the mix evens out — they agree on “pure vs mixed”, differ in <em>how much</em> they care about shades of mixing (§29.16, Problem 7).</li>
<li><strong>ID3’s original choice is entropy</strong> (via §29.12); CART’s classification trees (§29.16) default to Gini.</li>
</ol>
<p><strong>eg 3 (all three, one node).</strong> Node with <span class="math inline">\(6\)</span> of class <span class="math inline">\(+\)</span> and <span class="math inline">\(2\)</span> of class <span class="math inline">\(-\)</span> (<span class="math inline">\(p = \tfrac34, \tfrac14\)</span>): misclassification <span class="math inline">\(1 - \tfrac34 = \boxed{\tfrac14}\)</span>; Gini <span class="math inline">\(\tfrac34\cdot\tfrac14 + \tfrac14\cdot\tfrac34 = \boxed{\tfrac38}\)</span>; entropy <span class="math inline">\(-\tfrac34\log_2\tfrac34 - \tfrac14\log_2\tfrac14 \approx \boxed{0.811}\)</span>.</p>
<p><strong>Basically, …</strong> “Impurity = ‘how mixed is the class soup in this node?’ Three thermometers: misclassification (‘fraction I’d get wrong betting the majority’), Gini (‘error rate if I guessed randomly <em>in proportion</em> to the mix’), entropy (‘the information-theory measure of mixed-up-ness’). Pure node → all read zero.”</p>
</section>
<section id="information-gain-the-splitting-score" class="level2">
<h2 class="anchored" data-anchor-id="information-gain-the-splitting-score">29.12 Information gain: the splitting score</h2>
<p><strong>Def.</strong> Information gain is the expected <strong>reduction in entropy</strong> from partitioning the examples by an attribute — how much the split un-mixes the soup: <span class="math display">\[\boxed{IG(S, A) = \mathrm{Entropy}(S) - \sum_{v \in \mathrm{Values}(A)} \frac{|S_v|}{|S|}\,\mathrm{Entropy}(S_v)},\]</span> where <span class="math inline">\(S_v\)</span> = the examples with <span class="math inline">\(A = v\)</span>. In words (the lecture’s): <span class="math inline">\(IG(\text{attr}) = \text{entropy of dataset} - \text{entropy of attribute}\)</span> — the weighted child entropy subtracted from the parent’s.</p>
<p><strong>ID3’s rule:</strong> compute <span class="math inline">\(IG\)</span> (equivalently, the child entropy) for each remaining attribute; <strong>split on the attribute with the largest information gain</strong> — equivalently, the smallest weighted child entropy.</p>
<ol type="i">
<li><strong>Gain <span class="math inline">\(\ge 0\)</span> always</strong>: a split can’t increase the weighted entropy — at worst it teaches nothing (<span class="math inline">\(IG = 0\)</span>).</li>
<li><strong>Why entropy and not misclassification for growing?</strong> Preview of §29.16: entropy/Gini react to <em>any</em> probability shift, misclassification only to majority flips — the growing phase wants the sensitive instrument.</li>
</ol>
<p><strong>Basically, …</strong> “Information gain = ‘how much less mixed-up do things get if I split on this attribute?’ Compute the parent’s entropy, subtract the size-weighted average of the children’s entropies. Biggest drop wins the split. It’s the scoreboard that answers ID3’s root question.”</p>
</section>
<section id="worked-one-full-split-computation-by-hand" class="level2">
<h2 class="anchored" data-anchor-id="worked-one-full-split-computation-by-hand">29.13 Worked: one full split computation by hand</h2>
<p>Ten labelled items (defective <span class="math inline">\(-\)</span> vs ok <span class="math inline">\(+\)</span> widgets), two categorical features:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>#</th>
<th>colour</th>
<th>size</th>
<th>label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1–3</td>
<td>red</td>
<td>big</td>
<td><span class="math inline">\(+,+,+\)</span></td>
</tr>
<tr class="even">
<td>4–5</td>
<td>red</td>
<td>small</td>
<td><span class="math inline">\(-,-\)</span></td>
</tr>
<tr class="odd">
<td>6</td>
<td>blue</td>
<td>big</td>
<td><span class="math inline">\(+\)</span></td>
</tr>
<tr class="even">
<td>7–8</td>
<td>blue</td>
<td>big</td>
<td><span class="math inline">\(-,-\)</span></td>
</tr>
<tr class="odd">
<td>9–10</td>
<td>blue</td>
<td>small</td>
<td><span class="math inline">\(-,-\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Parent entropy.</strong> <span class="math inline">\(4\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(6\)</span> <span class="math inline">\(-\)</span>: <span class="math display">\[H(S) = -\tfrac{4}{10}\log_2\tfrac{4}{10} - \tfrac{6}{10}\log_2\tfrac{6}{10} \approx 0.529 + 0.442 = \boxed{0.971}.\]</span></p>
<p><strong>Split on size.</strong> Big: <span class="math inline">\(4\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(2\)</span> <span class="math inline">\(-\)</span> → <span class="math inline">\(H = -\tfrac23\log_2\tfrac23 - \tfrac13\log_2\tfrac13 \approx 0.918\)</span>. Small: <span class="math inline">\(0\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(4\)</span> <span class="math inline">\(-\)</span> → <span class="math inline">\(H = 0\)</span> (pure). Weighted: <span class="math inline">\(\tfrac{6}{10}(0.918) + \tfrac{4}{10}(0) = 0.551\)</span>. <span class="math display">\[\boxed{IG(S, \text{size}) = 0.971 - 0.551 = 0.420}.\]</span></p>
<p><strong>Split on colour.</strong> Red: <span class="math inline">\(3\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(2\)</span> <span class="math inline">\(-\)</span> → <span class="math inline">\(H \approx 0.971\)</span>. Blue: <span class="math inline">\(1\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(4\)</span> <span class="math inline">\(-\)</span> → <span class="math inline">\(H = -\tfrac15\log_2\tfrac15 - \tfrac45\log_2\tfrac45 \approx 0.722\)</span>. Weighted: <span class="math inline">\(\tfrac{5}{10}(0.971) + \tfrac{5}{10}(0.722) = 0.846\)</span>. <span class="math display">\[\boxed{IG(S, \text{colour}) = 0.971 - 0.846 = 0.125}.\]</span></p>
<p>Size wins (<span class="math inline">\(0.420 &gt; 0.125\)</span>) → <strong>root splits on size</strong>. Small branch: pure <span class="math inline">\(-\)</span> → leaf “<span class="math inline">\(-\)</span>”. Big branch (<span class="math inline">\(4\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(2\)</span> <span class="math inline">\(-\)</span>, <span class="math inline">\(H = 0.918\)</span>): split on colour — red-big <span class="math inline">\(+,+,+\)</span> → leaf “<span class="math inline">\(+\)</span>”; blue-big <span class="math inline">\(+,-,-\)</span> → mixed, no attributes left → leaf with the most common class, <span class="math inline">\(\boxed{-}\)</span>. Final tree: size=small → <span class="math inline">\(-\)</span>; size=big → colour=red → <span class="math inline">\(+\)</span>, colour=blue → <span class="math inline">\(-\)</span>.</p>
<p><strong>Gini cross-check</strong> (same verdict): <span class="math inline">\(G(S) = 1 - 0.4^2 - 0.6^2 = 0.48\)</span>; size-split weighted Gini <span class="math inline">\(\tfrac{6}{10}\big(1 - (\tfrac46)^2 - (\tfrac26)^2\big) + 0 = 0.267\)</span>; Gini gain <span class="math inline">\(\boxed{0.213}\)</span> — again the biggest drop, so Gini would also pick size first.</p>
<p><strong>Basically, …</strong> “Score both questions: ‘split by size?’ un-mixes the soup by <span class="math inline">\(0.42\)</span> bits, ‘split by colour?’ by only <span class="math inline">\(0.125\)</span>. Ask the size question first. The small branch is pure — done. The big branch still mixes, so ask colour inside it; blue-and-big ends <span class="math inline">\(1\)</span>-to-<span class="math inline">\(2\)</span> against, so the leaf calls it <span class="math inline">\(-\)</span> by majority. Two questions, three leaves, every number above recomputed twice.”</p>
</section>
<section id="the-lectures-tennis-example-numbers-verified" class="level2">
<h2 class="anchored" data-anchor-id="the-lectures-tennis-example-numbers-verified">29.14 The lecture’s tennis example (numbers verified)</h2>
<p>The slides work ID3 on the classic Play-Tennis data: <span class="math inline">\(14\)</span> examples, <span class="math inline">\(9\)</span> “Yes” / <span class="math inline">\(5\)</span> “No”. Recomputed independently (review log) — the lecture’s rounded values check out:</p>
<p><span class="math display">\[H(S) = -\tfrac{9}{14}\log_2\tfrac{9}{14} - \tfrac{5}{14}\log_2\tfrac{5}{14} \approx \boxed{0.940}.\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>attribute</th>
<th>split counts</th>
<th><span class="math inline">\(IG\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Wind</td>
<td>weak <span class="math inline">\(6\)</span>Y/<span class="math inline">\(2\)</span>N (<span class="math inline">\(H=0.811\)</span>), strong <span class="math inline">\(3\)</span>Y/<span class="math inline">\(3\)</span>N (<span class="math inline">\(H=1\)</span>)</td>
<td><span class="math inline">\(0.940 - \tfrac{8}{14}(0.811) - \tfrac{6}{14}(1) = \boxed{0.048}\)</span></td>
</tr>
<tr class="even">
<td><strong>Outlook</strong></td>
<td>sunny <span class="math inline">\(2\)</span>Y/<span class="math inline">\(3\)</span>N (<span class="math inline">\(0.971\)</span>), overcast <span class="math inline">\(4\)</span>Y/<span class="math inline">\(0\)</span>N (<span class="math inline">\(0\)</span>), rain <span class="math inline">\(3\)</span>Y/<span class="math inline">\(2\)</span>N (<span class="math inline">\(0.971\)</span>)</td>
<td><span class="math inline">\(0.940 - \tfrac{5}{14}(0.971) - \tfrac{4}{14}(0) - \tfrac{5}{14}(0.971) = \boxed{0.246}\)</span></td>
</tr>
<tr class="odd">
<td>Temperature</td>
<td>cold <span class="math inline">\(3\)</span>Y/<span class="math inline">\(1\)</span>N (<span class="math inline">\(0.811\)</span>), mild <span class="math inline">\(4\)</span>Y/<span class="math inline">\(2\)</span>N (<span class="math inline">\(0.918\)</span>), hot <span class="math inline">\(2\)</span>Y/<span class="math inline">\(2\)</span>N (<span class="math inline">\(1\)</span>)</td>
<td><span class="math inline">\(\boxed{0.029}\)</span></td>
</tr>
<tr class="even">
<td>Humidity</td>
<td>high <span class="math inline">\(3\)</span>Y/<span class="math inline">\(4\)</span>N (<span class="math inline">\(0.985\)</span>), normal <span class="math inline">\(6\)</span>Y/<span class="math inline">\(1\)</span>N (<span class="math inline">\(0.593\)</span>)</td>
<td><span class="math inline">\(\boxed{0.151}\)</span></td>
</tr>
</tbody>
</table>
<p>Outlook’s <span class="math inline">\(0.246\)</span> is the largest → <strong>root = Outlook</strong>. Recursing the same way inside each branch gives the lecture’s final tree:</p>
<!-- Original matplotlib rendering drawn for this chapter of the lecture's final Play-Tennis tree (not reused from any URL): Outlook at root; Sunny->Humidity->(High: No, Normal: Yes); Overcast: Yes; Rain->Wind->(Strong: No, Weak: Yes) -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/29-tennis-tree.png" class="img-fluid figure-img"></p>
<figcaption>Decision tree: root Outlook; branch Sunny leads to Humidity, which splits into High -&gt; No and Normal -&gt; Yes; branch Overcast leads directly to leaf Yes; branch Rain leads to Wind, which splits into Strong -&gt; No and Weak -&gt; Yes.</figcaption>
</figure>
</div>
<p><strong>Basically, …</strong> “Four candidate questions, four scores: Outlook un-mixes the most (<span class="math inline">\(0.246\)</span> bits), so it goes at the top. Same scoring inside each branch grows the rest. The picture is the whole classifier — follow the answers down to a leaf.”</p>
</section>
<section id="cart-regression-trees-constants-per-region" class="level2">
<h2 class="anchored" data-anchor-id="cart-regression-trees-constants-per-region">29.15 CART: regression trees — constants per region</h2>
<p>CART models <strong>both</strong> regression and classification, learning classification trees very much like ID3 (§29.16). For regression, suppose the space is partitioned into <span class="math inline">\(M\)</span> regions <span class="math inline">\(R_1, \ldots, R_M\)</span>, with a <strong>constant</strong> <span class="math inline">\(c_i\)</span> predicted in each: <span class="math display">\[\boxed{\hat y = \sum_{i=1}^{M} c_i\,\mathbf{1}(x \in R_i)}\]</span> (<span class="math inline">\(\mathbf{1}(\cdot)\)</span> is the indicator). Learning = choosing the partition <em>and</em> the constants. Three sub-questions (the lecture’s): which variable splits each node? what threshold <span class="math inline">\(s\)</span>? what constant <span class="math inline">\(c_i\)</span> per region?</p>
<p><strong>The greedy answer.</strong> Fixing a partition and minimizing the sum-of-squares <span class="math inline">\(J = \sum_{i=1}^{n}(y^{(i)} - \hat y^{(i)})^2\)</span> is easy — but the <em>best binary partition</em> for minimum SSE is computationally infeasible, so CART goes greedy: start with all data, consider splitting variable <span class="math inline">\(j\)</span> at split point <span class="math inline">\(s\)</span> into half-planes <span class="math display">\[\boxed{R_1 = \{x \mid x_j \le s\},\qquad R_2 = \{x \mid x_j &gt; s\}}\]</span> and solve <span class="math display">\[\boxed{\min_{j,s}\left[\min_{c_1}\sum_{i:\,x^{(i)} \in R_1}(y^{(i)} - c_1)^2 + \min_{c_2}\sum_{i:\,x^{(i)} \in R_2}(y^{(i)} - c_2)^2\right]}.\]</span></p>
<p><strong>The inner minimum is the mean</strong> (differentiate <span class="math inline">\(\sum (y^{(i)} - c_1)^2\)</span> w.r.t. <span class="math inline">\(c_1\)</span>: <span class="math inline">\(-2\sum(y^{(i)} - c_1) = 0\)</span>): <span class="math display">\[\boxed{\hat c_1 = \frac{1}{N_1}\sum_{i:\,x^{(i)} \in R_1} y^{(i)}},\qquad \boxed{\hat c_2 = \frac{1}{N_2}\sum_{i:\,x^{(i)} \in R_2} y^{(i)}}\]</span> — the region averages, exactly k-means’ centroid logic (§26.3(i)) in new clothes. For each variable, the best <span class="math inline">\((j, s)\)</span> is found by scanning through the inputs; then partition, and <strong>repeat the splitting process on each resulting region</strong>.</p>
<ol type="i">
<li><strong>Variance reduction</strong> can replace SSE as the splitting score for regression trees (the lecture’s one-line alternative).</li>
<li><strong>ID3 vs CART splits.</strong> ID3 branches one-per-attribute-value (multiway, categorical); CART always splits <strong>binary</strong> on <span class="math inline">\(x_j \lessgtr s\)</span> — even categorical-looking splits become thresholded binaries.</li>
</ol>
<p><strong>eg 4 (region means).</strong> Region <span class="math inline">\(R_1\)</span> holds outputs <span class="math inline">\(\{2, 4, 6\}\)</span>: <span class="math inline">\(\hat c_1 = \tfrac{12}{3} = \boxed{4}\)</span> — the constant that minimizes that region’s SSE (check: <span class="math inline">\((2-4)^2 + 0 + (6-4)^2 = 8\)</span>; any other <span class="math inline">\(c\)</span> scores worse).</p>
<p><strong>Basically, …</strong> “CART for numbers: chop the space into boxes, predict each box’s average. To choose where to chop, try every variable and every cut point, score each by ‘sum of squared misses around the two boxes’ averages’, keep the best cut, repeat inside each box. The box’s prediction is just its average — calculus says so in one line.”</p>
</section>
<section id="classification-trees-swap-the-loss-keep-the-growing" class="level2">
<h2 class="anchored" data-anchor-id="classification-trees-swap-the-loss-keep-the-growing">29.16 Classification trees: swap the loss, keep the growing</h2>
<p>For classification, growing (and pruning) works the same — except SSE is replaced by a node-impurity measure. With <span class="math inline">\(p_{i,k}\)</span> from §29.11, classify node <span class="math inline">\(i\)</span>’s observations as class <span class="math inline">\(k\)</span> if <span class="math display">\[\boxed{p_{i,k} &gt; p_{i,j}\quad \forall\, j \ne k}\]</span> — the majority class, §29.10’s leaf rule in symbols.</p>
<p><strong>Which impurity <span class="math inline">\(Q_i(T)\)</span>?</strong> The lecture lists three — <strong>misclassification error, Gini index, cross-entropy</strong> — with a division of labour: i) <strong>For growing the tree: Gini or cross-entropy.</strong> Both are differentiable, hence more amenable to numerical optimization — and, more importantly, <strong>more sensitive to node probabilities</strong> than the misclassification rate (Problem 7 exhibits the gap: two splits with identical misclassification error but different Gini). ii) <strong>For pruning the tree: misclassification rate.</strong> Once the tree exists and the question is which branches to cut (§29.19), the plain error rate is the criterion.</p>
<p><strong>Basically, …</strong> “Classification CART = regression CART with the squared-error score swapped for an impurity score. Grow with the sensitive instruments (Gini/cross-entropy — they notice probability shifts the raw error rate sleeps through); prune with the honest one (plain misclassification). The leaf’s verdict is always the majority class.”</p>
</section>
<section id="overfitting-deep-trees-memorize" class="level2">
<h2 class="anchored" data-anchor-id="overfitting-deep-trees-memorize">29.17 Overfitting: deep trees memorize</h2>
<p><strong>The problem.</strong> Overfitting in trees = the tree is designed to <strong>perfectly fit all training samples</strong> — branches with strict rules and sparse data — which wrecks accuracy on test data. <strong>A very large tree might overfit; a small tree might not capture the important structure.</strong> Without depth control, the tree fits the noise too (the lecture’s figure: an uncontrolled tree’s boundary writhes around every stray point).</p>
<p><strong>Def (maximum depth).</strong> The length of the longest path from root to leaf; <strong>the root has depth <span class="math inline">\(0\)</span></strong>.</p>
<ol type="i">
<li><strong>Tree size is a tuning parameter</strong> — the lecture’s words. Like <span class="math inline">\(k\)</span> (§29.7) and <span class="math inline">\(\lambda\)</span> (§28.10), depth/max-depth is a hyperparameter: audition candidates by validation error (§28.12(ii)), not by training fit.</li>
<li><strong>Rectangles are the mechanism.</strong> Each extra level doubles down on axis-aligned boxes; deep enough, every training point gets its own tiny box — zero training error, pure memorization.</li>
</ol>
<!-- Original matplotlib illustration drawn for this chapter (not reused from any URL): schematic of a depth-2 tree's three big rectangular regions vs an unrestricted-depth tree carving tiny rectangles around two label-flipped noise points -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/29-tree-depth-overfit.png" class="img-fluid figure-img"></p>
<figcaption>Two panels on the same 2-D data with two label-flipped noise points (dashed boxes). Left: a depth-2 tree’s three big axis-aligned rectangles misclassify the noise but keep the structure. Right: an unrestricted-depth tree carves tiny rectangles around each noise point, fitting them exactly.</figcaption>
</figure>
</div>
<p><strong>Basically, …</strong> “Let the tree grow unchecked and it stops learning the pattern and starts memorizing the roster — one tiny box per training point, noise points included. The figure’s right panel is that pathology: perfect on training, clueless on anything new. Depth is the leash: too long, it memorizes; too short, it can’t see the structure.”</p>
</section>
<section id="pre-pruning-stop-before-it-overgrows" class="level2">
<h2 class="anchored" data-anchor-id="pre-pruning-stop-before-it-overgrows">29.18 Pre-pruning: stop before it overgrows</h2>
<p>One approach: <strong>stop the algorithm before it becomes a fully-grown tree</strong>. Stopping criteria (the lecture’s): - stop if the <strong>number of samples</strong> in a node is below some user-specified threshold; - stop if <strong>expanding the node does not improve impurity</strong>.</p>
<ol type="i">
<li><strong>Cheap and direct</strong> — no second phase; the tree simply never grows the dubious branches.</li>
<li><strong>But short-sighted.</strong> The lecture’s objection: <em>“a seemingly worthless split might lead to a very good split below it”</em> — refusing a split with zero immediate gain can block the split beneath it that would have paid off. Greedy stopping can’t see around the corner.</li>
</ol>
<p><strong>Basically, …</strong> “Pre-pruning = quit while you’re ahead: don’t split tiny nodes, don’t split when impurity won’t budge. Simple — but it can chicken out one level too early, killing a useless-looking split that was guarding a great one underneath.”</p>
</section>
<section id="post-pruning-grow-big-then-cut-back-cost-complexity" class="level2">
<h2 class="anchored" data-anchor-id="post-pruning-grow-big-then-cut-back-cost-complexity">29.19 Post-pruning: grow big, then cut back (cost-complexity)</h2>
<p>The lecture’s <strong>preferred strategy</strong>: grow a large tree <span class="math inline">\(T_0\)</span> — stopping the splitting only when some minimum node size is reached — then <strong>prune it back</strong>. Pruning balances residual error against model complexity.</p>
<p><strong>Setup.</strong> A <strong>subtree</strong> <span class="math inline">\(T \subset T_0\)</span> is any tree obtainable by pruning nodes off <span class="math inline">\(T_0\)</span>. For region <span class="math inline">\(R_i\)</span> the prediction is the mean <span class="math display">\[\boxed{c_i = \frac{1}{N_i}\sum_{x^{(i)} \in R_i} y^{(i)}},\]</span> with residual sum-of-squares contribution <span class="math display">\[\boxed{Q_i(T) = \sum_{x^{(i)} \in R_i}(y^{(i)} - c_i)^2}.\]</span></p>
<p><strong>The pruning criterion</strong> (cost-complexity): <span class="math display">\[\boxed{C(T) = \sum_{i=1}^{|T|} Q_i(T) + \alpha\,|T|},\]</span> <span class="math inline">\(|T|\)</span> = number of leaf nodes. The <strong>regularization parameter <span class="math inline">\(\alpha \ge 0\)</span></strong> trades residual error against complexity: <strong>large <span class="math inline">\(\alpha\)</span> → smaller trees</strong>, small <span class="math inline">\(\alpha\)</span> → larger trees — the same shape as §28’s <span class="math inline">\(\lambda\)</span> disciplining weights.</p>
<ol type="i">
<li><strong><span class="math inline">\(\alpha\)</span> is chosen by cross-validation</strong> — yet another hyperparameter joining the §28.12(ii) audition line (<span class="math inline">\(k\)</span>, depth, <span class="math inline">\(\alpha\)</span>).</li>
<li><strong>Post- beats pre-</strong> precisely because of §29.18(ii): growing past the “worthless” split lets the good split below it appear; pruning then removes only what the error-vs-complexity trade can’t justify (Problem 8 works the arithmetic).</li>
</ol>
<p><strong>Basically, …</strong> “Post-pruning = let the tree overgrow, then haircut it. Score every candidate haircut by ‘total squared miss + <span class="math inline">\(\alpha\)</span> × (number of leaves)’ and keep the cheapest. Big <span class="math inline">\(\alpha\)</span> = expensive leaves = severe haircut. <span class="math inline">\(\alpha\)</span> itself gets picked by cross-validation — hyperparameters all the way down.”</p>
</section>
<section id="knn-vs-decision-trees" class="level2">
<h2 class="anchored" data-anchor-id="knn-vs-decision-trees">29.20 KNN vs decision trees</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>KNN (§§29.2–29.8)</th>
<th>Decision trees (§§29.9–29.19)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Model built?</strong></td>
<td>No explicit model — the training set <em>is</em> the model</td>
<td>Explicit model: the partition + leaf constants, built at training time</td>
</tr>
<tr class="even">
<td><strong>Work happens…</strong></td>
<td>…at prediction time (all computation at runtime)</td>
<td>…at training time; prediction is a root-to-leaf walk (logarithmic cost, §29.21)</td>
</tr>
<tr class="odd">
<td><strong>Decision shape</strong></td>
<td>Piecewise, Voronoi-like neighbourhoods (§29.6)</td>
<td>Axis-aligned rectangles (§29.9)</td>
</tr>
<tr class="even">
<td><strong>Complexity knob</strong></td>
<td><span class="math inline">\(k\)</span> (small = jagged/overfit, large = smooth/underfit)</td>
<td>tree size / max depth (deep = memorize, shallow = underfit)</td>
</tr>
<tr class="odd">
<td><strong>Knob chosen by</strong></td>
<td>validation error (§29.7)</td>
<td>validation error (§29.17(i)); <span class="math inline">\(\alpha\)</span> by CV (§29.19)</td>
</tr>
<tr class="even">
<td><strong>Interpretability</strong></td>
<td>“your neighbours are…” (§29.8)</td>
<td>the tree visualizes directly (§29.21)</td>
</tr>
<tr class="odd">
<td><strong>Weakness</strong></td>
<td>slow queries; junk features pollute distances</td>
<td>high variance; overfits without pruning</td>
</tr>
</tbody>
</table>
<ol type="i">
<li><strong>Complementary pathologies.</strong> KNN’s risk is at <em>query</em> time (slow, distance-dominated); trees’ risk is at <em>training</em> time (variance, overfitting). §29.8(iii) and §29.21’s disadvantages say so respectively.</li>
<li><strong>The lecture never says “lazy” or “eager”</strong> — those textbook labels for this exact contrast are omitted here; the table uses the lectures’ own vocabulary (“no explicit model”, “computations performed at runtime”). Flagged in the review log.</li>
</ol>
<p><strong>Basically, …</strong> “KNN memorizes the data and thinks at query time; trees think at training time and memorize the <em>rules</em>. KNN’s boundary is drawn from neighbourhoods, the tree’s from boxes. Both have one complexity knob, both tune it on held-out data — and the lectures describe the contrast without ever saying ‘lazy’ or ‘eager’.”</p>
</section>
<section id="trees-advantages-and-disadvantages-as-the-lecture-lists-them" class="level2">
<h2 class="anchored" data-anchor-id="trees-advantages-and-disadvantages-as-the-lecture-lists-them">29.21 Trees: advantages and disadvantages (as the lecture lists them)</h2>
<p><strong>Advantages.</strong> i) <strong>Versatile</strong> — classification, regression, even multi-output tasks. ii) <strong>Simple to understand and interpret</strong> — trees can be visualized (§29.14’s picture <em>is</em> the model). iii) <strong>Little data preprocessing needed</strong> — splits are threshold comparisons, so scaling/monotonic transforms don’t matter. iv) <strong>Logarithmic prediction cost</strong> — using the tree costs <span class="math inline">\(\log\)</span> in the number of training samples (walk down, don’t scan).</p>
<p><strong>Disadvantages.</strong> i) <strong>Overly complex trees don’t generalize</strong> — pruning (§§29.18–29.19) is needed to address this. ii) <strong>High variance</strong> — small data changes can reshuffle the splits; mitigated by <strong>ensembles</strong> (Chapter 34’s topic — the “Where this goes next” pointer). iii) <strong>Piecewise-linear approximation, poor extrapolation</strong> — constant-per-box fits can’t extend trends beyond the training range.</p>
<p><strong>Basically, …</strong> “Trees: draw the model as a picture, predict by walking down it in log time, barely preprocess anything. The bill: they overfit unless pruned, they’re twitchy (high variance — ensembles calm them, Chapter 34), and boxes can’t extrapolate a trend.”</p>
</section>
<section id="where-this-goes-next" class="level2">
<h2 class="anchored" data-anchor-id="where-this-goes-next">29.22 Where this goes next</h2>
<ol type="i">
<li><strong>The toolbox continues.</strong> Next in §25.12(iv)‘s list: SVMs (Chapters 32–33) — the “heavy machinery” §29.8(iii) name-checks — then ensembles (Chapter 34), which directly attack trees’ high-variance weakness (§29.21(ii)): the variance-reduction story the tree lecture only gestures at.</li>
<li><strong>The hyperparameter discipline, fully generalized.</strong> §28.12(ii)’s promise is now visibly kept: <span class="math inline">\(\lambda\)</span> (§28.10), <span class="math inline">\(k\)</span> (§29.7), max depth (§29.17(i)), and the pruning parameter <span class="math inline">\(\alpha\)</span> (§29.19(i)) are all chosen the same way — candidates, validation error, retrain, test. One ritual, every knob.</li>
<li><strong>From here to deep learning.</strong> Trees partition with axis-aligned boxes and KNN with distance neighbourhoods — both are <em>fixed</em> geometries. The coming chapters (and Part V) replace the fixed geometry with <em>learned</em> ones: kernels (§27) already hinted at it; neural networks make the feature space itself trainable.</li>
</ol>
</section>
<section id="problem-set" class="level2">
<h2 class="anchored" data-anchor-id="problem-set">Problem set</h2>
<ol type="1">
<li><strong>3-NN vote, by hand.</strong> On §29.5’s seven points, for <span class="math inline">\(q_2 = (4, 2)\)</span>: (i) list the squared Euclidean distances to all seven points; (ii) name the <span class="math inline">\(3\)</span> nearest neighbours; (iii) give the vote and the predicted label. (iv) Repeat the vote for <span class="math inline">\(k = 5\)</span>.</li>
<li><strong>The metric can flip the answer.</strong> Query <span class="math inline">\(q = (0,0)\)</span>; training points <span class="math inline">\(a = (5,0)\)</span> labelled <span class="math inline">\(+\)</span>, <span class="math inline">\(b = (3,3)\)</span> labelled <span class="math inline">\(-\)</span>. With <span class="math inline">\(k = 1\)</span>: (i) which point is nearest under Euclidean distance, and what is predicted? (ii) Which under Manhattan distance, and what is predicted? (iii) One line: why does the lecture list the metric as a hyperparameter?</li>
<li><strong>KNN regression.</strong> A query’s <span class="math inline">\(k = 3\)</span> nearest neighbours have outputs <span class="math inline">\(2.0\)</span>, <span class="math inline">\(3.5\)</span>, <span class="math inline">\(6.5\)</span>. (i) Compute <span class="math inline">\(\hat y\)</span> from §29.4. (ii) In one line: why average here but vote for classification?</li>
<li><strong>The effect of <span class="math inline">\(k\)</span>.</strong> On §29.5’s data (<span class="math inline">\(3\)</span> <span class="math inline">\(A\)</span>, <span class="math inline">\(4\)</span> <span class="math inline">\(B\)</span>), query <span class="math inline">\(q = (2,2)\)</span>: (i) predict with <span class="math inline">\(k = 1\)</span>, <span class="math inline">\(3\)</span>, <span class="math inline">\(5\)</span>; (ii) predict with <span class="math inline">\(k = 7\)</span> and explain via the lecture’s “<span class="math inline">\(k\)</span> close to <span class="math inline">\(n\)</span>” claim; (iii) using the §29.5 figure, describe in two lines how the boundary changes from <span class="math inline">\(k = 1\)</span> to <span class="math inline">\(k = 5\)</span>.</li>
<li><strong>Verify the lecture’s Wind number.</strong> Given <span class="math inline">\(H(S) = 0.940\)</span>, <span class="math inline">\(H(S_{\text{weak}}) = 0.811\)</span> (<span class="math inline">\(8\)</span> examples), <span class="math inline">\(H(S_{\text{strong}}) = 1.0\)</span> (<span class="math inline">\(6\)</span> examples): recompute <span class="math inline">\(IG(S, \text{Wind})\)</span> from §29.12’s formula and confirm the lecture’s <span class="math inline">\(0.048\)</span>.</li>
<li><strong>Finish the §29.13 comparison.</strong> For the ten-widget dataset: (i) compute <span class="math inline">\(H\)</span> of the red branch (<span class="math inline">\(3\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(2\)</span> <span class="math inline">\(-\)</span>) and the blue branch (<span class="math inline">\(1\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(4\)</span> <span class="math inline">\(-\)</span>); (ii) compute <span class="math inline">\(IG(S, \text{colour})\)</span> and confirm it is <span class="math inline">\(\approx 0.125 &lt; IG(S, \text{size})\)</span>; (iii) state which attribute ID3 picks for the root.</li>
<li><strong>Why Gini beats misclassification for growing.</strong> Parent node: <span class="math inline">\(40\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(40\)</span> <span class="math inline">\(-\)</span>. Split A: children <span class="math inline">\((30+/10-)\)</span>, <span class="math inline">\((10+/30-)\)</span>. Split B: children <span class="math inline">\((20+/40-)\)</span>, <span class="math inline">\((20+/0-)\)</span>. (i) Compute the size-weighted misclassification error of each split. (ii) Compute the size-weighted Gini index of each split. (iii) Which split does Gini prefer, and in one line why is it the better split? (iv) Connect to the lecture’s “more sensitive to the node probabilities”.</li>
<li><strong>Cost-complexity arithmetic.</strong> A grown tree <span class="math inline">\(T_0\)</span> has <span class="math inline">\(|T_0| = 4\)</span> leaves with <span class="math inline">\(\sum Q_i(T_0) = 10\)</span>; pruning one branch gives <span class="math inline">\(T\)</span> with <span class="math inline">\(|T| = 2\)</span> leaves and <span class="math inline">\(\sum Q_i(T) = 14\)</span>. (i) Compute <span class="math inline">\(C(T_0)\)</span> and <span class="math inline">\(C(T)\)</span> for <span class="math inline">\(\alpha = 1\)</span> — which wins? (ii) Repeat for <span class="math inline">\(\alpha = 3\)</span>. (iii) State the general rule relating <span class="math inline">\(\alpha\)</span> to tree size.</li>
</ol>
</section>
<section id="solutions" class="level2">
<h2 class="anchored" data-anchor-id="solutions">Solutions</h2>
<p>Attempt each problem first, then click a problem to reveal its worked solution.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 1 — 3-NN vote, by hand (<span class="math inline">\(q_2 = (4,2)\)</span>)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="i">
<li>Squared Euclidean distances (from the §29.5 table):</li>
</ol>
<ul>
<li><span class="math inline">\(d^2(q_2, A_1) = (4-0)^2 + (2-0)^2 = 16 + 4 = 20\)</span></li>
<li><span class="math inline">\(d^2(q_2, A_2) = (4-1)^2 + (2-4)^2 = 9 + 4 = 13\)</span></li>
<li><span class="math inline">\(d^2(q_2, A_3) = (4-3)^2 + (2-1)^2 = 1 + 1 = 2\)</span></li>
<li><span class="math inline">\(d^2(q_2, B_1) = (4-5)^2 + (2-2)^2 = 1 + 0 = 1\)</span></li>
<li><span class="math inline">\(d^2(q_2, B_2) = (4-4)^2 + (2-5)^2 = 0 + 9 = 9\)</span></li>
<li><span class="math inline">\(d^2(q_2, B_3) = (4-6)^2 + (2-3)^2 = 4 + 1 = 5\)</span></li>
<li><span class="math inline">\(d^2(q_2, B_4) = (4-7)^2 + (2-2)^2 = 9 + 0 = 9\)</span></li>
</ul>
<ol start="2" type="i">
<li><p>Sorted: <span class="math inline">\(B_1 (1) &lt; A_3 (2) &lt; B_3 (5) &lt; B_2 (9) = B_4 (9) &lt; A_2 (13) &lt; A_1 (20)\)</span>. The <span class="math inline">\(3\)</span> nearest: <span class="math inline">\(\boxed{B_1, A_3, B_3}\)</span>.</p></li>
<li><p>Votes: <span class="math inline">\(B, A, B\)</span> → <span class="math inline">\(2\)</span> for <span class="math inline">\(B\)</span>, <span class="math inline">\(1\)</span> for <span class="math inline">\(A\)</span> → <span class="math inline">\(\boxed{\text{predict } B}\)</span>.</p></li>
<li><p><span class="math inline">\(k = 5\)</span>: neighbours <span class="math inline">\(B_1, A_3, B_3, B_2, B_4\)</span> (the <span class="math inline">\(9\)</span>-tie is between two <span class="math inline">\(B\)</span>’s, so the set is unaffected) → votes <span class="math inline">\(B,A,B,B,B\)</span> → <span class="math inline">\(4\)</span> vs <span class="math inline">\(1\)</span> → <span class="math inline">\(\boxed{\text{predict } B}\)</span>.</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 2 — The metric can flip the answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="i">
<li><p>Euclidean (squared): <span class="math inline">\(d^2(q,a) = 25 + 0 = 25\)</span>; <span class="math inline">\(d^2(q,b) = 9 + 9 = 18\)</span>. Nearest is <span class="math inline">\(\boxed{b}\)</span> → predict <span class="math inline">\(\boxed{-}\)</span>.</p></li>
<li><p>Manhattan: <span class="math inline">\(d_1(q,a) = 5 + 0 = 5\)</span>; <span class="math inline">\(d_1(q,b) = 3 + 3 = 6\)</span>. Nearest is <span class="math inline">\(\boxed{a}\)</span> → predict <span class="math inline">\(\boxed{+}\)</span>.</p></li>
<li><p>Because “nearest” — and hence the vote — depends on how distance is measured; the metric is a modelling choice with observable consequences, i.e.&nbsp;a hyperparameter (§29.2(ii), §29.3(i)).</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 3 — KNN regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="i">
<li><p><span class="math inline">\(\hat y = \tfrac13(2.0 + 3.5 + 6.5) = \tfrac{12.0}{3} = \boxed{4.0}\)</span>.</p></li>
<li><p>Classification labels are discrete — they can only be counted (voted); regression outputs are numbers, so they can be averaged — the mean is the central value of the neighbourhood’s outputs (§29.4(i)).</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 4 — The effect of <span class="math inline">\(k\)</span>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="i">
<li>From §29.5’s sorted <span class="math inline">\(d^2\)</span> for <span class="math inline">\(q = (2,2)\)</span>: <span class="math inline">\(A_3 (2), A_2 (5), A_1 (8), B_1 (9), B_2 (13), B_3 (17), B_4 (25)\)</span>.</li>
</ol>
<ul>
<li><span class="math inline">\(k=1\)</span>: <span class="math inline">\(\{A_3\}\)</span> → <span class="math inline">\(\boxed{A}\)</span>.</li>
<li><span class="math inline">\(k=3\)</span>: <span class="math inline">\(\{A_3, A_2, A_1\}\)</span> → <span class="math inline">\(3\)</span> <span class="math inline">\(A\)</span> → <span class="math inline">\(\boxed{A}\)</span>.</li>
<li><span class="math inline">\(k=5\)</span>: <span class="math inline">\(\{A_3, A_2, A_1, B_1, B_2\}\)</span> → <span class="math inline">\(3\)</span> <span class="math inline">\(A\)</span>, <span class="math inline">\(2\)</span> <span class="math inline">\(B\)</span> → <span class="math inline">\(\boxed{A}\)</span>.</li>
</ul>
<ol start="2" type="i">
<li><p><span class="math inline">\(k = 7\)</span>: the neighbourhood is all <span class="math inline">\(7\)</span> points → <span class="math inline">\(3\)</span> <span class="math inline">\(A\)</span> vs <span class="math inline">\(4\)</span> <span class="math inline">\(B\)</span> → <span class="math inline">\(\boxed{B}\)</span>. This is the lecture’s endpoint: as <span class="math inline">\(k \to n\)</span>, the vote is the dataset’s majority class (<span class="math inline">\(B\)</span>), so every query — <span class="math inline">\(q\)</span> included — is labelled <span class="math inline">\(B\)</span> (§29.6(iii)).</p></li>
<li><p>At <span class="math inline">\(k = 1\)</span> the boundary is jagged: each training point owns an intricate Voronoi-like cell, and the border weaves between nearby points. At <span class="math inline">\(k = 5\)</span> the border relaxes into one smooth curve separating the blue cluster from the reds — the local wiggles are voted out (§29.6(i)–(ii); see the §29.5 figure).</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 5 — Verify the lecture’s Wind number
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(IG(S, \text{Wind}) = H(S) - \sum_v \tfrac{|S_v|}{|S|}H(S_v)\)</span>: <span class="math display">\[IG = 0.940 - \frac{8}{14}(0.811) - \frac{6}{14}(1.0) = 0.940 - 0.4634 - 0.4286 = 0.0480 \approx \boxed{0.048}.\]</span> Matches the lecture’s <span class="math inline">\(0.048\)</span> (full-precision recomputation in the review log gives <span class="math inline">\(0.0481\)</span>).</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 6 — Finish the §29.13 comparison
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="i">
<li><p>Red branch (<span class="math inline">\(3\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(2\)</span> <span class="math inline">\(-\)</span>): <span class="math display">\[H = -\tfrac35\log_2\tfrac35 - \tfrac25\log_2\tfrac25 \approx 0.442 + 0.529 = \boxed{0.971}.\]</span> Blue branch (<span class="math inline">\(1\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(4\)</span> <span class="math inline">\(-\)</span>): <span class="math display">\[H = -\tfrac15\log_2\tfrac15 - \tfrac45\log_2\tfrac45 \approx 0.464 + 0.258 = \boxed{0.722}.\]</span></p></li>
<li><p>Weighted child entropy: <span class="math inline">\(\tfrac{5}{10}(0.971) + \tfrac{5}{10}(0.722) = 0.8465\)</span>. <span class="math display">\[IG(S, \text{colour}) = 0.971 - 0.8465 = \boxed{0.125} &lt; 0.420 = IG(S, \text{size}).\]</span></p></li>
<li><p>ID3 splits on the largest information gain → root attribute is <span class="math inline">\(\boxed{\text{size}}\)</span>.</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 7 — Why Gini beats misclassification for growing
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Parent: <span class="math inline">\(80\)</span> points, <span class="math inline">\(40\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(40\)</span> <span class="math inline">\(-\)</span>.</p>
<ol type="i">
<li>Misclassification error of a child <span class="math inline">\(= 1 - \max(p_+, p_-) = \tfrac{\min(n_+, n_-)}{n_{\text{child}}}\)</span>.</li>
</ol>
<ul>
<li>Split A: left <span class="math inline">\(\tfrac{10}{40} = 0.25\)</span>, right <span class="math inline">\(\tfrac{10}{40} = 0.25\)</span>; weighted: <span class="math inline">\(\tfrac{40}{80}(0.25) + \tfrac{40}{80}(0.25) = \boxed{0.25}\)</span>.</li>
<li>Split B: left <span class="math inline">\(\tfrac{20}{60} = \tfrac13\)</span>, right <span class="math inline">\(\tfrac{0}{20} = 0\)</span>; weighted: <span class="math inline">\(\tfrac{60}{80}\cdot\tfrac13 + \tfrac{20}{80}(0) = 0.25 + 0 = \boxed{0.25}\)</span>. Identical — misclassification cannot distinguish the splits.</li>
</ul>
<ol start="2" type="i">
<li>Gini of a child <span class="math inline">\(= 2p_+(1-p_+)\)</span> (binary case).</li>
</ol>
<ul>
<li>Split A: each child <span class="math inline">\(2\cdot\tfrac34\cdot\tfrac14 = 0.375\)</span>; weighted <span class="math inline">\(\boxed{0.375}\)</span>.</li>
<li>Split B: left <span class="math inline">\(2\cdot\tfrac13\cdot\tfrac23 = \tfrac49 \approx 0.444\)</span>, right <span class="math inline">\(0\)</span>; weighted: <span class="math inline">\(\tfrac{60}{80}\cdot\tfrac49 = \boxed{\tfrac13 \approx 0.333}\)</span>.</li>
</ul>
<ol start="3" type="i">
<li><p>Gini prefers <span class="math inline">\(\boxed{\text{split B}}\)</span> (<span class="math inline">\(0.333 &lt; 0.375\)</span>). It is the better split because its right child is perfectly pure (<span class="math inline">\(20\)</span> <span class="math inline">\(+\)</span>, <span class="math inline">\(0\)</span> <span class="math inline">\(-\)</span>) — the split has isolated a clean region, while split A leaves both children equally mixed.</p></li>
<li><p>This is the lecture’s point verbatim: Gini (and cross-entropy) are “more sensitive to the node probabilities” — they register the purity improvement in B’s right child, whereas the misclassification rate only cares about majority flips and scores both splits the same (§29.16(i)).</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 8 — Cost-complexity arithmetic
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(C(T) = \sum_i Q_i(T) + \alpha|T|\)</span>.</p>
<ol type="i">
<li><p><span class="math inline">\(\alpha = 1\)</span>: <span class="math inline">\(C(T_0) = 10 + 1\cdot 4 = \boxed{14}\)</span>; <span class="math inline">\(C(T) = 14 + 1\cdot 2 = \boxed{16}\)</span>. <span class="math inline">\(\boxed{T_0 \text{ wins}}\)</span> (keep the larger tree).</p></li>
<li><p><span class="math inline">\(\alpha = 3\)</span>: <span class="math inline">\(C(T_0) = 10 + 3\cdot 4 = \boxed{22}\)</span>; <span class="math inline">\(C(T) = 14 + 3\cdot 2 = \boxed{20}\)</span>. <span class="math inline">\(\boxed{T \text{ wins}}\)</span> (prune).</p></li>
<li><p>General rule (the lecture’s): <span class="math inline">\(\boxed{\text{larger } \alpha \Rightarrow \text{smaller trees}}\)</span> — <span class="math inline">\(\alpha\)</span> prices each leaf, so raising it makes complex trees too expensive to keep (§29.19).</p></li>
</ol>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./28-regularization.html" class="pagination-link" aria-label="28. Regularization: ridge and lasso">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">28. Regularization: ridge and lasso</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./30-naive-bayes.html" class="pagination-link" aria-label="30. Naive Bayes: generative vs discriminative models">
        <span class="nav-page-text"><span class="chapter-title">30. Naive Bayes: generative vs discriminative models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>