<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chapter 41: The artificial neuron and MLPs from scratch – Foundations to Deep Learning</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./42-backpropagation.html" rel="next">
<link href="./40-end-to-end-debugging.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-968ddd4980072ae063619731fc79ef1d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./41-neuron-mlp-scratch.html">Part VI — Bridge to Deep Learning</a></li><li class="breadcrumb-item"><a href="./41-neuron-mlp-scratch.html"><span class="chapter-title">Chapter 41: The artificial neuron and MLPs from scratch</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundations to Deep Learning</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Foundations to Deep Learning</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Mathematical Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-sets-functions-preliminaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 1 — Sets, functions, and mathematical preliminaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-vectors-and-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2. Vectors and matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-linear-systems-determinants-inverses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3. Linear systems, determinants, inverses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-vector-spaces-four-subspaces.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4. Vector spaces and the four fundamental subspaces</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-orthogonality-projections-least-squares.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5. Orthogonality, projections, least squares</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-eigenvalues-eigenvectors-diagonalization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6. Eigenvalues, eigenvectors, diagonalization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-svd-positive-definite.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7. SVD and positive definite matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-single-variable-calculus.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8. Single-variable calculus: continuity, differentiability, derivatives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-multivariable-calculus.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9. Multivariable calculus: partial derivatives, gradients, Taylor series</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-unconstrained-optimization-gradient-descent.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10. Unconstrained optimization and gradient descent</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-constrained-optimization-lagrange.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11. Constrained optimization: Lagrange multipliers, projected gradient descent</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-convex-sets-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12. Convex sets and convex functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-duality-kkt.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13. Duality and KKT conditions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Probability and Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-probability-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14. Probability basics: experiments, sample spaces, Bayes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-discrete-random-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15. Discrete random variables and key distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-continuous-random-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16. Continuous random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-joint-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17. Joint distributions: two random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-joint-continuous-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18. Joint continuous distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-random-vectors-multivariate-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19. Random vectors and the multivariate normal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-estimation-mle-map.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20. Estimation: MLE and Bayesian/MAP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-inequalities-clt.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21. Inequalities and the central limit theorem</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III — Machine Learning Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-what-is-ml.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22. What is ML: data, models, tasks; supervised vs unsupervised</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-linear-polynomial-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">23. Linear and polynomial regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-pca.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">24. PCA: variance maximization, eigendecomposition, kernel PCA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-gmm-em.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">25. GMMs and the EM algorithm</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV — Machine Learning Techniques</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-k-means.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26. K-means clustering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-kernel-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27. Kernel methods and kernel regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-regularization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28. Regularization: ridge and lasso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29-knn-trees.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">29. KNN and decision trees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-naive-bayes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30. Naive Bayes: generative vs discriminative models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-perceptron-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31. Perceptron and logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32-hard-margin-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 32: Hard-margin SVM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33-soft-margin-kernel-svm.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 33: Soft-margin SVM and the kernel trick</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34-ensembles.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 34: Ensembles — bagging, boosting, AdaBoost</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./35-loss-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 35: Loss functions for classification</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Part V — Machine Learning in Practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./36-numpy-pandas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 36: NumPy and Pandas for ML</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./37-sklearn-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 37: scikit-learn: regression workflows</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./38-sklearn-classification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 38: scikit-learn: classification workflows</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./39-model-evaluation-cv.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 39: Model evaluation, cross-validation, hyperparameter tuning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40-end-to-end-debugging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 40: End-to-end model training and debugging</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Part VI — Bridge to Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41-neuron-mlp-scratch.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Chapter 41: The artificial neuron and MLPs from scratch</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42-backpropagation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 42: Backpropagation, worked end-to-end</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43-optimization-neural-nets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 43: Optimization for neural nets — SGD variants, init, normalization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./44-cnns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 44: CNNs — convolution, pooling, transfer learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./45-rnns-sequences-vanishing-gradients.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 45: RNNs — sequences and vanishing gradients</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./46-attention-and-transformers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 46: Attention and the transformer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./47-generative-models-gans-diffusion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 47: Generative models: GANs and diffusion</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-neurons-two-steps" id="toc-the-neurons-two-steps" class="nav-link active" data-scroll-target="#the-neurons-two-steps">41.1 The neuron’s two steps</a></li>
  <li><a href="#the-lineage-a-calculator-a-learner-and-a-neuron" id="toc-the-lineage-a-calculator-a-learner-and-a-neuron" class="nav-link" data-scroll-target="#the-lineage-a-calculator-a-learner-and-a-neuron">41.2 The lineage: a calculator, a learner, and a neuron</a></li>
  <li><a href="#why-smooth-matters-differentiability-gradient-descent" id="toc-why-smooth-matters-differentiability-gradient-descent" class="nav-link" data-scroll-target="#why-smooth-matters-differentiability-gradient-descent">41.3 Why smooth matters: differentiability → gradient descent</a></li>
  <li><a href="#from-one-neuron-to-a-layer-the-two-vectorized-equations" id="toc-from-one-neuron-to-a-layer-the-two-vectorized-equations" class="nav-link" data-scroll-target="#from-one-neuron-to-a-layer-the-two-vectorized-equations">41.4 From one neuron to a layer: the two vectorized equations</a></li>
  <li><a href="#worked-example-one-layer-every-number-recomputed" id="toc-worked-example-one-layer-every-number-recomputed" class="nav-link" data-scroll-target="#worked-example-one-layer-every-number-recomputed">41.5 Worked example: one layer, every number recomputed</a></li>
  <li><a href="#why-depth-needs-non-linearity" id="toc-why-depth-needs-non-linearity" class="nav-link" data-scroll-target="#why-depth-needs-non-linearity">41.6 Why depth needs non-linearity</a></li>
  <li><a href="#activations-compared" id="toc-activations-compared" class="nav-link" data-scroll-target="#activations-compared">41.7 Activations compared</a></li>
  <li><a href="#xor-why-no-linear-model-can-do-it" id="toc-xor-why-no-linear-model-can-do-it" class="nav-link" data-scroll-target="#xor-why-no-linear-model-can-do-it">41.8 XOR: why no linear model can do it</a></li>
  <li><a href="#the-2-2-1-network-worked-by-hand" id="toc-the-2-2-1-network-worked-by-hand" class="nav-link" data-scroll-target="#the-2-2-1-network-worked-by-hand">41.9 The 2-2-1 network, worked by hand</a></li>
  <li><a href="#the-training-loop-in-numpy-the-whole-mlp-re-run" id="toc-the-training-loop-in-numpy-the-whole-mlp-re-run" class="nav-link" data-scroll-target="#the-training-loop-in-numpy-the-whole-mlp-re-run">41.10 The training loop in numpy: the whole MLP, re-run</a></li>
  <li><a href="#the-output-layer-loss-pairing" id="toc-the-output-layer-loss-pairing" class="nav-link" data-scroll-target="#the-output-layer-loss-pairing">41.11 The output layer + loss pairing</a></li>
  <li><a href="#the-contract-survives-sklearns-mlpclassifier-mlpregressor" id="toc-the-contract-survives-sklearns-mlpclassifier-mlpregressor" class="nav-link" data-scroll-target="#the-contract-survives-sklearns-mlpclassifier-mlpregressor">41.12 The contract survives: sklearn’s <code>MLPClassifier</code> / <code>MLPRegressor</code></a></li>
  <li><a href="#pytorch-tensors-in-the-same-loop-out" id="toc-pytorch-tensors-in-the-same-loop-out" class="nav-link" data-scroll-target="#pytorch-tensors-in-the-same-loop-out">41.13 PyTorch: tensors in, the same loop out</a></li>
  <li><a href="#four-traps-worth-knowing-the-courses-own-warnings" id="toc-four-traps-worth-knowing-the-courses-own-warnings" class="nav-link" data-scroll-target="#four-traps-worth-knowing-the-courses-own-warnings">41.14 Four traps worth knowing (the course’s own warnings)</a></li>
  <li><a href="#where-this-goes-next" id="toc-where-this-goes-next" class="nav-link" data-scroll-target="#where-this-goes-next">41.15 Where this goes next</a></li>
  <li><a href="#problem-set" id="toc-problem-set" class="nav-link" data-scroll-target="#problem-set">Problem set</a></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions">Solutions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./41-neuron-mlp-scratch.html">Part VI — Bridge to Deep Learning</a></li><li class="breadcrumb-item"><a href="./41-neuron-mlp-scratch.html"><span class="chapter-title">Chapter 41: The artificial neuron and MLPs from scratch</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Chapter 41: The artificial neuron and MLPs from scratch</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Part VI opens here. The shape of this chapter follows the GenAI Weeks 1–2 deck (“Introduction to ANN,” Balaji Srinivasan and Ganapathy Krishnamurthi), cross-checked against the MLT Week-12 ANN slides (Ashish Tendulkar) and the course’s own notebooks — the XOR lab, the PyTorch fundamentals, the PyTorch workflow, and the Fashion-MNIST classifier. One idea, fully worked: <strong>a neuron is a perceptron with a smooth activation, and an MLP is layers of such neurons trained by gradient descent.</strong> The from-scratch code in this chapter is new numpy written for this book — every number below was re-run here and is marked <strong>[verified-NumPy]</strong>. Notebook numbers are transcribed from the course material and marked <strong>[recorded]</strong> — torch is not installed on this machine, so no PyTorch line below was executed here.</p>
<p><strong>Notation.</strong> Per-example (the deck’s, column-vector) form is <span class="math inline">\(z^{[l]} = W^{[l]} a^{[l-1]} + b^{[l]}\)</span>, <span class="math inline">\(a^{[l]} = g(z^{[l]})\)</span>. Batch (the MLT slides’, and this book’s) form is <span class="math inline">\(Z^l = A^{l-1} W^l + b^l\)</span>, <span class="math inline">\(A^l = g(Z^l)\)</span>, with the book’s <span class="math inline">\((n, d)\)</span> convention — points as rows (§36.1). §41.4’s Note pins the two conventions to each other; mix them up and you get the transpose bug.</p>
<section id="the-neurons-two-steps" class="level2">
<h2 class="anchored" data-anchor-id="the-neurons-two-steps">41.1 The neuron’s two steps</h2>
<p>The MLT Week-12 slide writes the whole thing in two lines (its notation, single neuron, three inputs): <span class="math display">\[\boxed{z = w_1 a_1 + w_2 a_2 + w_3 a_3 + b, \qquad a = g(z)}.\]</span> i) <strong>Pre-activation:</strong> combine the inputs linearly — a weighted sum plus a bias, <span class="math inline">\(z = w^T a + b\)</span>. ii) <strong>Activation:</strong> pass the sum through a non-linearity <span class="math inline">\(g\)</span> — <span class="math inline">\(a = g(z)\)</span>.</p>
<p>The GenAI deck says the same thing in a bigger font: “This two-step ‘Linear Sum → Non-Linear Activation’ process is performed by <strong>every single neuron</strong> in a deep neural network.”</p>
<p><strong>Def (artificial neuron).</strong> A function of its inputs, parameterized by weights and a bias: linear combination first, smooth non-linearity second. Everything in this chapter — layers, the MLP, the forward pass — is this two-step process repeated.</p>
<p><strong>Basically, …</strong> “A neuron takes a bunch of numbers, multiplies each by a weight, adds them up plus a bias — that is the linear part — then bends the answer with a squashing function, the activation. Two moves, every neuron, every layer. That is the whole animal.”</p>
</section>
<section id="the-lineage-a-calculator-a-learner-and-a-neuron" class="level2">
<h2 class="anchored" data-anchor-id="the-lineage-a-calculator-a-learner-and-a-neuron">41.2 The lineage: a calculator, a learner, and a neuron</h2>
<p>The deck tells this as three slides, and they are worth knowing because they say exactly what changed at each step:</p>
<ol type="i">
<li><p><strong>The M-P neuron (a calculator, not a learner).</strong> “The M-P neuron was a fixed logic gate. It could compute, but it could not learn.” Its two lacks, in the deck’s words: <strong>no feature importance</strong> — “equally important features,” “missing piece: weights”; <strong>no automatic learning</strong> — “threshold <span class="math inline">\((\theta)\)</span> is fixed. Must be set manually.”</p></li>
<li><p><strong>The perceptron (a learner).</strong> Rosenblatt’s 1958 move was to <em>learn</em> the weights: <span class="math inline">\(\hat y = \mathrm{sign}(w^T \phi(x))\)</span> (§31.2). The deck’s strengths list: “It Learns! An automatic learning rule adjusts weights from data. Feature Importance: learns which inputs are more important via weights. Convergence Guarantee: if data is linearly separable, it’s guaranteed to find a solution.” Its two limits: <strong>the fatal flaw, linear separability only</strong> — “only problems where a single straight line (or hyperplane) can separate the classes can be solved”; and <strong>the harsh threshold</strong> — “the step function activation is not differentiable, preventing modern gradient-based training.”</p></li>
<li><p><strong>The artificial neuron.</strong> Take the perceptron’s weighted sum, keep the learned weights, and swap the step function for a <em>smooth</em> non-linearity — sigmoid, tanh, ReLU. Logistic regression (§31.8) was already this exact object wearing a statistics costume: <span class="math inline">\(h = \sigma(\theta^T x + \theta_0)\)</span> is a neuron with a sigmoid activation.</p></li>
</ol>
<p><strong>Basically, …</strong> “Three generations: the M-P neuron <em>computed</em> with hand-set weights (no learning). The perceptron <em>learned</em> the weights but could only draw straight walls, and its step function was too harsh to descend. The artificial neuron keeps the learned weighted sum, swaps in a smooth activation — and now gradient descent can train it.”</p>
</section>
<section id="why-smooth-matters-differentiability-gradient-descent" class="level2">
<h2 class="anchored" data-anchor-id="why-smooth-matters-differentiability-gradient-descent">41.3 Why smooth matters: differentiability → gradient descent</h2>
<p>The perceptron trained by its own bespoke rule — fix mistakes one at a time (§31.4) — because its loss had a kink at the boundary (§31.3’s Note: <span class="math inline">\(J(w)\)</span> is “not differentiable in <span class="math inline">\(w\)</span>”). The artificial neuron’s move is to make <em>everything</em> differentiable:</p>
<ul>
<li>The activation <span class="math inline">\(g\)</span> is smooth (or smooth enough — ReLU is smooth everywhere except a single corner, and gradient descent tolerates the corner).</li>
<li>The loss is smooth (cross-entropy, squared error — §41.11).</li>
<li>So the chain rule applies everywhere, gradients exist (§10.7’s multivariate machinery), and Chapter 10’s update <span class="math inline">\(\theta := \theta - \eta \nabla J\)</span> (§10.5) drives training.</li>
</ul>
<p>This is why the deck’s “harsh threshold” bullet is load-bearing: the <em>only</em> thing that kept the perceptron off the gradient-descent highway was a non-differentiable activation. Smooth it, and the whole machinery of Part I applies.</p>
<p><strong>Basically, …</strong> “Gradient descent needs a slope to walk down (§10.5). A step function has no slope — flat, then a cliff. A smooth activation has a slope everywhere, so the loss has a slope, so the gradient exists, so Chapter 10’s machinery trains the network. The smoothness is the ticket onto the highway.”</p>
</section>
<section id="from-one-neuron-to-a-layer-the-two-vectorized-equations" class="level2">
<h2 class="anchored" data-anchor-id="from-one-neuron-to-a-layer-the-two-vectorized-equations">41.4 From one neuron to a layer: the two vectorized equations</h2>
<p>One neuron at a time is “incredibly inefficient” (the deck), so a whole layer is computed at once — the vectorized form (§36.2’s discipline, now paying off). The deck’s two core equations, for a layer <span class="math inline">\(l\)</span>:</p>
<p><span class="math display">\[\boxed{z^{[l]} = W^{[l]} a^{[l-1]} + b^{[l]}}, \qquad \boxed{a^{[l]} = g\!\left(z^{[l]}\right)}.\]</span></p>
<p>The MLT slides write the same two equations for a whole batch at once — the form the code will use: <span class="math display">\[\boxed{Z^l = A^{l-1} W^l + b^l}, \qquad \boxed{A^l = g(Z^l)}, \qquad A^0 = X.\]</span> The parts, from the slides: i) <span class="math inline">\(a^{[l-1]}\)</span> (<span class="math inline">\(A^{l-1}\)</span>): activations from the previous layer — the input vector <span class="math inline">\(x\)</span> at <span class="math inline">\(l = 1\)</span>. ii) <span class="math inline">\(W^{[l]}\)</span> (<span class="math inline">\(W^l\)</span>): the weight matrix. <span class="math inline">\(W_{ij}\)</span> is the weight from neuron <span class="math inline">\(j\)</span> in layer <span class="math inline">\(l-1\)</span> to neuron <span class="math inline">\(i\)</span> in layer <span class="math inline">\(l\)</span> (deck’s index order). In the batch form, <span class="math inline">\(W^l\)</span> has size <span class="math inline">\(S_{l-1} \times S_l\)</span> — each neuron in layer <span class="math inline">\(l\)</span> gets <span class="math inline">\(S_{l-1}\)</span> incoming weights, and the layer holds <span class="math inline">\(S_{l-1} \times S_l\)</span> weights total (MLT slides). iii) <span class="math inline">\(b^{[l]}\)</span> (<span class="math inline">\(b^l\)</span>): one bias per neuron — a vector of length <span class="math inline">\(S_l\)</span>. iv) <span class="math inline">\(z^{[l]}\)</span> (<span class="math inline">\(Z^l\)</span>): pre-activations — the weighted sums. v) <span class="math inline">\(a^{[l]}\)</span> (<span class="math inline">\(A^l\)</span>): post-activations — <span class="math inline">\(g\)</span> applied element-wise in the hidden layers (MLT slides).</p>
<p><strong>Note (the transpose convention).</strong> The deck’s per-example form left-multiplies, <span class="math inline">\(W^{[l]} a^{[l-1]}\)</span> — its <span class="math inline">\(W\)</span> is <span class="math inline">\(S_l \times S_{l-1}\)</span>. The batch/MLT/code form right-multiplies rows, <span class="math inline">\(A^{l-1} W^l\)</span> — its <span class="math inline">\(W\)</span> is <span class="math inline">\(S_{l-1} \times S_l\)</span>. Same weights, transposed layout; pick the one that matches your data layout and don’t mix them. Everything below uses the batch form with the book’s <span class="math inline">\((n, d)\)</span> rows (§36.1). Shapes, for a layer with <span class="math inline">\(S_{l-1} = m\)</span> inputs and <span class="math inline">\(S_l\)</span> neurons on <span class="math inline">\(n\)</span> points: <span class="math display">\[A^{l-1}: n \times m, \quad W^l: m \times S_l, \quad b^l: (S_l,) \text{ broadcast across the rows (§36.3)}, \quad Z^l, A^l: n \times S_l.\]</span></p>
<p><strong>Def (MLP).</strong> “Simply a feedforward network with one or more hidden layers” (the deck). Information flows one direction — input to output, no loops (MLT slides). The layers are indexed <span class="math inline">\(0 \le l \le L\)</span>: layer <span class="math inline">\(0\)</span> is the input, layer <span class="math inline">\(L\)</span> the output, and <span class="math inline">\(L\)</span> itself is a hyperparameter. Layer sizes: <span class="math inline">\(S_0 = m\)</span> features; <span class="math inline">\(S_1, \dots, S_{L-1}\)</span> are the hidden-layer widths — hyperparameters; <span class="math inline">\(S_L = 1\)</span> for regression, <span class="math inline">\(S_L = k\)</span> for <span class="math inline">\(k\)</span>-class classification (MLT slides).</p>
</section>
<section id="worked-example-one-layer-every-number-recomputed" class="level2">
<h2 class="anchored" data-anchor-id="worked-example-one-layer-every-number-recomputed">41.5 Worked example: one layer, every number recomputed</h2>
<p>The deck’s worked example (slide 36/93): a hidden layer with <span class="math inline">\(3\)</span> neurons receiving input from <span class="math inline">\(2\)</span> features, ReLU activation. Every number recomputed here [verified-NumPy]:</p>
<p><strong>eg 1 (the deck’s 2→3 ReLU layer).</strong> <span class="math display">\[x = \begin{bmatrix} 0.5 \\ 1.0 \end{bmatrix}, \quad W = \begin{bmatrix} 0.2 &amp; 0.7 \\ -0.4 &amp; 0.1 \\ 0.9 &amp; -0.3 \end{bmatrix}, \quad b = \begin{bmatrix} 0.1 \\ 0.2 \\ -0.5 \end{bmatrix}.\]</span> Step 1 — weighted sum, <span class="math inline">\(z = Wx + b\)</span>: <span class="math display">\[\begin{align*}
z_1 &amp;= 0.2(0.5) + 0.7(1.0) + 0.1 = 0.1 + 0.7 + 0.1 = 0.9, \\
z_2 &amp;= -0.4(0.5) + 0.1(1.0) + 0.2 = -0.2 + 0.1 + 0.2 = 0.1, \\
z_3 &amp;= 0.9(0.5) + (-0.3)(1.0) + (-0.5) = 0.45 - 0.3 - 0.5 = -0.35.
\end{align*}\]</span> Step 2 — element-wise ReLU, <span class="math inline">\(a = \max(0, z)\)</span>: <span class="math display">\[a = \begin{bmatrix} \max(0, 0.9) \\ \max(0, 0.1) \\ \max(0, -0.35) \end{bmatrix} = \begin{bmatrix} 0.9 \\ 0.1 \\ 0 \end{bmatrix}.\]</span> The third neuron fires <span class="math inline">\(0\)</span> — a negative pre-activation killed by the threshold (§36.4’s <code>np.where</code> one-liner, in matrix form). The numpy re-run prints <code>z = [0.9  0.1 -0.35]</code>, <code>a = [0.9 0.1 0.]</code> — matching the slide [verified-NumPy].</p>
<p><strong>eg 2 (same layer, batch form, four points at once).</strong> The same <span class="math inline">\(W, b\)</span> applied to four rows, <span class="math inline">\(A^0 \in \mathbb{R}^{4 \times 2}\)</span>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.array([[<span class="fl">0.5</span>, <span class="fl">1.0</span>],</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>              [<span class="fl">0.0</span>, <span class="fl">0.0</span>],</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>              [<span class="op">-</span><span class="fl">1.0</span>, <span class="fl">2.0</span>],</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>              [<span class="fl">0.5</span>, <span class="fl">0.0</span>]])          <span class="co"># (4, 2): four points as rows</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Z <span class="op">=</span> X <span class="op">@</span> W.T <span class="op">+</span> b                      <span class="co"># (4, 2) @ (2, 3) -&gt; (4, 3)</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> np.maximum(<span class="dv">0</span>, Z)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The row-first convention means the deck’s per-example <span class="math inline">\(W\)</span> <span class="math inline">\((3 \times 2)\)</span> gets transposed in batch code (§41.4’s Note). One matrix multiply replaces four loops — and on a GPU, “computationally efficient and perfectly suited for GPUs” (the deck).</p>
</section>
<section id="why-depth-needs-non-linearity" class="level2">
<h2 class="anchored" data-anchor-id="why-depth-needs-non-linearity">41.6 Why depth needs non-linearity</h2>
<p>Two facts, in order:</p>
<p><strong>Fact 1 — stacking linear layers is useless.</strong> “Without a non-linear activation function, a deep network simply collapses into a single linear model, no matter how many layers it has” (the deck). Two layers without activation: <span class="math display">\[L_2(L_1(x)) = W_2(W_1 x + b_1) + b_2 = (W_2 W_1)\, x + (W_2 b_1 + b_2) = W' x + b'.\]</span> Just another linear function. “A 100-layer linear network has the same power as a 1-layer network.” The activation is what stops the collapse — with <span class="math inline">\(g\)</span>, the composition <span class="math inline">\(g(W_2\, g(W_1 x + b_1) + b_2)\)</span> “cannot be simplified,” which “allows the network to learn arbitrarily complex, ‘wiggly’ functions.”</p>
<p><strong>Fact 2 — the perceptron’s fatal flaw needs depth to fix.</strong> The deck’s MLP slide states it plainly: “A single Perceptron fails on non-linear data (like XOR)” — “cannot be separated by one line.” The hidden layer is “an automatic feature engineer”: “it learns to transform the data into a new representation,” and “in this new space, the data becomes linearly separable.” The output layer then draws the (single) straight wall in <em>that</em> space.</p>
<p><strong>Basically, …</strong> “Depth without the bend is a lie: a hundred linear layers fold down into one (<span class="math inline">\(W'x + b'\)</span>). The activation is the ingredient that makes stacking <em>do</em> something — each bent layer re-represents the data, and the last layer separates what the earlier layers arranged.”</p>
</section>
<section id="activations-compared" class="level2">
<h2 class="anchored" data-anchor-id="activations-compared">41.7 Activations compared</h2>
<p>The MLT slides’ three hidden-layer activations, plus the deck’s notes on when each breaks:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(g(z)\)</span></th>
<th>Formula</th>
<th>Range</th>
<th>Why it helps</th>
<th>Why it hurts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sigmoid</td>
<td><span class="math inline">\(\sigma(z) = \dfrac{1}{1 + e^{-z}}\)</span></td>
<td><span class="math inline">\((0, 1)\)</span></td>
<td>“Firing rate” reading; probabilities out (§31.8)</td>
<td><strong>Vanishing gradients</strong>: “flat at both ends… gradient near zero for large inputs, effectively stops learning”; not zero-centered — “outputs always positive, which can slow down learning”</td>
</tr>
<tr class="even">
<td>Tanh</td>
<td><span class="math inline">\(\tanh(z) = \dfrac{e^{z} - e^{-z}}{e^{z} + e^{-z}}\)</span></td>
<td><span class="math inline">\((-1, 1)\)</span></td>
<td>Zero-centered — “helps center the data for the next layer, often speeding up convergence”</td>
<td>Same vanishing-gradient flattening — “difficult to use in very deep networks”</td>
</tr>
<tr class="odd">
<td>ReLU</td>
<td><span class="math inline">\(\max(0, z)\)</span></td>
<td><span class="math inline">\([0, \infty)\)</span></td>
<td>“Computationally efficient: very fast to compute (just a threshold)”; “no vanishing gradient (for <span class="math inline">\(z &gt; 0\)</span>)” — constant slope <span class="math inline">\(1\)</span> carries the signal deep; sparsity from the zeros</td>
<td><strong>Dying ReLU</strong>: “if a neuron’s weights are updated such that its pre-activation <span class="math inline">\(z\)</span> is always negative, it will always output <span class="math inline">\(0\)</span>… and can never recover”</td>
</tr>
</tbody>
</table>
<p>The ReLU family fixes the dying problem with a small slope on the negative side — the deck’s Leaky ReLU: <span class="math display">\[f(z) = \begin{cases} z, &amp; z &gt; 0, \\ \alpha z, &amp; z \le 0, \end{cases} \qquad \text{($\alpha$ small, e.g. $0.01$).}\]</span> The deck’s practical guide, verbatim in spirit: hidden layers — “start with ReLU. Most common, fastest, and usually works”; for dying neurons “switch to Leaky ReLU or Parametric ReLU”; “for Transformer-based models, consider GELU or Swish.” The output layer is task-dependent (§41.11): binary classification → sigmoid; multiclass → softmax (§31.12); regression → none (linear/identity).</p>
<!-- Original matplotlib illustration drawn for this chapter (not reused from any URL): sigmoid, tanh, ReLU curves — the flat ends that cause vanishing gradients, against ReLU's constant positive slope -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/41-activations.png" class="img-fluid figure-img"></p>
<figcaption>Three activation curves side by side: sigmoid rising 0 to 1 with flat ends, tanh rising -1 to 1 with flat ends, ReLU flat at 0 then a straight line with slope 1.</figcaption>
</figure>
</div>
<p><strong>Basically, …</strong> “Sigmoid and tanh are S-bends — nice for probabilities, but their flat tails choke the gradient in deep stacks. ReLU is a corner: free slope on the right, zero on the left — fast, and the signal survives depth. Its price is neurons that can die (always negative); Leaky ReLU gives them a trickle.”</p>
</section>
<section id="xor-why-no-linear-model-can-do-it" class="level2">
<h2 class="anchored" data-anchor-id="xor-why-no-linear-model-can-do-it">41.8 XOR: why no linear model can do it</h2>
<p>The deck’s proof (and the XOR notebook’s §2.2) — write out what a linear model must do to the four XOR corners and watch it contradict itself:</p>
<p><strong>eg 3 (the proof).</strong> XOR: <span class="math inline">\((0,0)\!\to\!0\)</span>, <span class="math inline">\((0,1)\!\to\!1\)</span>, <span class="math inline">\((1,0)\!\to\!1\)</span>, <span class="math inline">\((1,1)\!\to\!0\)</span>. Suppose <span class="math inline">\(f(x_1, x_2) = w_1 x_1 + w_2 x_2 + b\)</span> fits all four: <span class="math display">\[\begin{align*}
f(0,0) = b &amp;\approx 0, \\
f(0,1) = w_2 + b &amp;\approx 1, \\
f(1,0) = w_1 + b &amp;\approx 1, \\
f(1,1) = w_1 + w_2 + b &amp;\approx 0.
\end{align*}\]</span> The first gives <span class="math inline">\(b \approx 0\)</span>; the second then gives <span class="math inline">\(w_2 \approx 1\)</span>; the third gives <span class="math inline">\(w_1 \approx 1\)</span>. The fourth then demands <span class="math inline">\(1 + 1 + 0 \approx 0\)</span> — a contradiction. No straight line (hyperplane) separates the corners. The notebook adds the history: “In 1969, Minsky and Papert proved that single-layer perceptrons cannot solve XOR,” and XOR became the “Hello World” of neural networks.</p>
<!-- Original matplotlib illustration drawn for this chapter (not reused from any URL): the four XOR points with corner labels, with two candidate separating lines shown failing — each line strands a same-label pair apart -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/41-xor.png" class="img-fluid figure-img"></p>
<figcaption>Scatter plot of the four XOR points with labels 0, 0, 1, 1 at the corners of the unit square; two dashed candidate lines each leave opposite-corner same-label points on the wrong side.</figcaption>
</figure>
</div>
<p><strong>Basically, …</strong> “Four corners of a square, opposite corners share a label. Any straight wall you draw puts a mismatched pair on the same side. Four equations, three unknowns — the fourth always contradicts. That is the whole reason hidden layers exist.”</p>
</section>
<section id="the-2-2-1-network-worked-by-hand" class="level2">
<h2 class="anchored" data-anchor-id="the-2-2-1-network-worked-by-hand">41.9 The 2-2-1 network, worked by hand</h2>
<p>The course’s XOR notebook builds a 2-2-1 network — 2 inputs, 2 hidden neurons, 1 output, sigmoid everywhere — and walks one full forward pass by hand for input <span class="math inline">\((1, 0)\)</span> (target <span class="math inline">\(y = 1\)</span>, since <span class="math inline">\(\mathrm{XOR}(1,0) = 1\)</span>). The setup, from the notebook’s code:</p>
<p><span class="math display">\[W_1 = \begin{bmatrix} 1.0 &amp; -1.0 \\ 1.0 &amp; -1.0 \end{bmatrix}, \quad b_1 = \begin{bmatrix} 0.0 \\ 1.0 \end{bmatrix}, \quad W_2 = \begin{bmatrix} 2.0 \\ -1.0 \end{bmatrix}, \quad b_2 = \begin{bmatrix} -1.0 \end{bmatrix}.\]</span></p>
<p><strong>eg 4 (one forward pass, the notebook’s numbers, every step recomputed).</strong> Input <span class="math inline">\(x_1 = 1\)</span>, <span class="math inline">\(x_2 = 0\)</span>. Hidden pre-activations: <span class="math display">\[z_{h1} = 1.0(1) + 1.0(0) + 0.0 = 1.0, \qquad z_{h2} = (-1.0)(1) + (-1.0)(0) + 1.0 = 0.0.\]</span> Sigmoid activations (<span class="math inline">\(\sigma(1) = 1/(1 + e^{-1}) = 1/1.36788 \approx 0.7311\)</span>): <span class="math display">\[h_1 = \sigma(1.0) \approx 0.7311, \qquad h_2 = \sigma(0.0) = 0.5.\]</span> Output pre-activation and prediction: <span class="math display">\[z_o = 2.0(0.7311) + (-1.0)(0.5) + (-1.0) = 1.4622 - 0.5 - 1.0 = -0.0379,\]</span> <span class="math display">\[\hat y = \sigma(-0.0379) = \frac{1}{1 + e^{0.0379}} \approx 0.4905.\]</span> Binary cross-entropy (§41.11) with <span class="math inline">\(y = 1\)</span>: <span class="math display">\[L = -\big[1 \cdot \log(0.4905) + 0\big] = 0.7123.\]</span> The numpy re-run prints <code>z1 = [1. 0.], h1 = [0.7311 0.5], z3 = -0.0379, yhat = 0.4905, loss = 0.7123</code> — the notebook’s <span class="math inline">\(0.491\)</span> and <span class="math inline">\(0.712\)</span> [verified-NumPy].</p>
<p><strong>Basically, …</strong> “This is §41.4’s two equations, twice: <span class="math inline">\(X \to\)</span> hidden (<span class="math inline">\(Z^1 = XW^1 + b^1\)</span>, sigmoid) <span class="math inline">\(\to\)</span> output (<span class="math inline">\(Z^2 = A^1W^2 + b^2\)</span>, sigmoid). The prediction <span class="math inline">\(0.4905\)</span> is barely below a coin flip — this untrained net is guessing — and the loss <span class="math inline">\(0.7123\)</span> measures exactly how far that guess sits from the true <span class="math inline">\(1\)</span>.”</p>
</section>
<section id="the-training-loop-in-numpy-the-whole-mlp-re-run" class="level2">
<h2 class="anchored" data-anchor-id="the-training-loop-in-numpy-the-whole-mlp-re-run">41.10 The training loop in numpy: the whole MLP, re-run</h2>
<p>The notebook’s <code>XORNeuralNetwork</code> class is the complete machine: forward (the two equations), binary cross-entropy, backward (one chain-rule step per layer — Chapter 42 derives every line), and gradient-descent weight updates (§10.5). Written here from scratch in the same shape, trained full-batch on all four XOR points, seed fixed (§36.6):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> sigmoid(z):</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>np.clip(z, <span class="op">-</span><span class="dv">500</span>, <span class="dv">500</span>)))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> MLP221:</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, seed<span class="op">=</span><span class="dv">42</span>, scale<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>        rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.W1 <span class="op">=</span> rng.standard_normal((<span class="dv">2</span>, <span class="dv">2</span>)) <span class="op">*</span> scale   <span class="co"># S0=2 -&gt; S1=2</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.b1 <span class="op">=</span> rng.standard_normal(<span class="dv">2</span>) <span class="op">*</span> scale</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.W2 <span class="op">=</span> rng.standard_normal((<span class="dv">2</span>, <span class="dv">1</span>)) <span class="op">*</span> scale   <span class="co"># S1=2 -&gt; S2=1</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.b2 <span class="op">=</span> rng.standard_normal(<span class="dv">1</span>) <span class="op">*</span> scale</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, X):</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.z1 <span class="op">=</span> X <span class="op">@</span> <span class="va">self</span>.W1 <span class="op">+</span> <span class="va">self</span>.b1        <span class="co"># (4,2) @ (2,2) -&gt; (4,2)</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.h1 <span class="op">=</span> sigmoid(<span class="va">self</span>.z1)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.z2 <span class="op">=</span> <span class="va">self</span>.h1 <span class="op">@</span> <span class="va">self</span>.W2 <span class="op">+</span> <span class="va">self</span>.b2   <span class="co"># (4,2) @ (2,1) -&gt; (4,1)</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.out <span class="op">=</span> sigmoid(<span class="va">self</span>.z2).ravel()</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.out</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> loss(<span class="va">self</span>, y, yhat):</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>        yhat <span class="op">=</span> np.clip(yhat, <span class="fl">1e-15</span>, <span class="dv">1</span> <span class="op">-</span> <span class="fl">1e-15</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="bu">float</span>(<span class="op">-</span>np.mean(y <span class="op">*</span> np.log(yhat) <span class="op">+</span> (<span class="dv">1</span> <span class="op">-</span> y) <span class="op">*</span> np.log(<span class="dv">1</span> <span class="op">-</span> yhat)))</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> backward(<span class="va">self</span>, X, y):                  <span class="co"># sigmoid + BCE: dL/dz2 = out - y</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>        m <span class="op">=</span> X.shape[<span class="dv">0</span>]</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>        dz2 <span class="op">=</span> (<span class="va">self</span>.out <span class="op">-</span> y).reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="op">/</span> m</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>        dW2 <span class="op">=</span> <span class="va">self</span>.h1.T <span class="op">@</span> dz2</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>        db2 <span class="op">=</span> dz2.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>        dh1 <span class="op">=</span> dz2 <span class="op">@</span> <span class="va">self</span>.W2.T</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>        dz1 <span class="op">=</span> dh1 <span class="op">*</span> <span class="va">self</span>.h1 <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> <span class="va">self</span>.h1)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>        dW1 <span class="op">=</span> X.T <span class="op">@</span> dz1</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>        db1 <span class="op">=</span> dz1.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> dW1, db1, dW2, db2</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> step(<span class="va">self</span>, grads, lr):                 <span class="co"># theta := theta - lr * grad</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.W1 <span class="op">-=</span> lr <span class="op">*</span> grads[<span class="dv">0</span>]<span class="op">;</span> <span class="va">self</span>.b1 <span class="op">-=</span> lr <span class="op">*</span> grads[<span class="dv">1</span>]</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.W2 <span class="op">-=</span> lr <span class="op">*</span> grads[<span class="dv">2</span>]<span class="op">;</span> <span class="va">self</span>.b2 <span class="op">-=</span> lr <span class="op">*</span> grads[<span class="dv">3</span>]</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.array([[<span class="dv">0</span>,<span class="dv">0</span>],[<span class="dv">0</span>,<span class="dv">1</span>],[<span class="dv">1</span>,<span class="dv">0</span>],[<span class="dv">1</span>,<span class="dv">1</span>]], dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> np.array([<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>], dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>mlp <span class="op">=</span> MLP221(seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1000</span>):</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>    pred <span class="op">=</span> mlp.forward(X)</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>    mlp.step(mlp.backward(X, y), lr<span class="op">=</span><span class="fl">5.0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>eg 5 (the actual run — every number below is the session’s own output).</strong> The trace, epoch 0 / every 100 / last:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>epoch</th>
<th>loss</th>
<th>predictions (four corners)</th>
<th>accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.693751</td>
<td>[0.489 0.486 0.493 0.491]</td>
<td>50%</td>
</tr>
<tr class="even">
<td>100</td>
<td>0.609766</td>
<td>[0.466 0.723 0.392 0.424]</td>
<td>75%</td>
</tr>
<tr class="odd">
<td>200</td>
<td>0.030062</td>
<td>[0.029 0.976 0.959 0.024]</td>
<td>100%</td>
</tr>
<tr class="even">
<td>300</td>
<td>0.011829</td>
<td>[0.011 0.99 0.984 0.01 ]</td>
<td>100%</td>
</tr>
<tr class="odd">
<td>999</td>
<td>0.002181</td>
<td>[0.002 0.998 0.997 0.002]</td>
<td>100%</td>
</tr>
</tbody>
</table>
<p>Final: <code>[0.0021, 0.9981, 0.9971, 0.0018]</code> → binary <code>[0, 1, 1, 0]</code>, loss <span class="math inline">\(0.002178\)</span> [verified-NumPy]. Three readings: i) <strong>Epoch 0 starts at loss <span class="math inline">\(\approx 0.693\)</span>.</strong> Not a coincidence: with untrained weights outputting <span class="math inline">\(\approx 0.5\)</span> everywhere, <span class="math inline">\(-\log(0.5) = 0.6931\)</span> — §35.6’s logistic loss at margin <span class="math inline">\(0\)</span>. ii) <strong>Epoch 100 is honest about the grind.</strong> Accuracy says 75%, but the <span class="math inline">\((1,0)\)</span> corner predicts <span class="math inline">\(0.392\)</span> — still below the <span class="math inline">\(0.5\)</span> wall. The network “looks close” while one corner is firmly wrong; the loss (<span class="math inline">\(0.6098\)</span>, barely moved) tells the truer story. iii) <strong>Epoch 200 is the phase change.</strong> Loss collapses to <span class="math inline">\(0.03\)</span> and every corner is confident — the hidden layer found the XOR representation. §31.10’s warning applies at the tail: the loss keeps shrinking toward <span class="math inline">\(0\)</span> without ever reaching it, because sigmoid only saturates at <span class="math inline">\(0/1\)</span> with infinite weights — accuracy is already perfect, the weights keep inflating.</p>
<p><strong>Basically, …</strong> “Forward: the two equations, twice. Loss: how wrong. Backward: how each weight caused it (Chapter 42). Step: nudge every weight downhill (§10.5). Repeat 1000 times and four bent neurons solve what one straight wall never could — the loss trace shows the exact moment it clicks.”</p>
</section>
<section id="the-output-layer-loss-pairing" class="level2">
<h2 class="anchored" data-anchor-id="the-output-layer-loss-pairing">41.11 The output layer + loss pairing</h2>
<p>The MLT slides make the output layer <em>task-dependent</em>: same forward equations, but the last layer’s activation <span class="math inline">\(g\)</span> and the loss <span class="math inline">\(L\)</span> are chosen as a pair. The deck’s practical guide agrees (sigmoid binary, softmax multiclass, linear regression). Three pairings:</p>
<p><strong>i) Regression — identity output, squared error.</strong> Output layer: <span class="math inline">\(S_L = 1\)</span>, <span class="math inline">\(g(z) = z\)</span> (the slides: “the activation function in the final layer for regression is just the identity function”), <span class="math inline">\(\hat y = A^L\)</span> an <span class="math inline">\(n \times 1\)</span> column. Loss (the slides’ form): <span class="math display">\[\boxed{L(y, \hat y) = \tfrac{1}{2}\,(\hat y - y)^T(\hat y - y)},\]</span> “In Numpy: <code>L = 0.5 * np.sum((y_hat - y) * (y_hat - y))</code>” (the slides, verbatim). The <span class="math inline">\(1/2\)</span> is a convenience that cancels the derivative’s <span class="math inline">\(2\)</span>.</p>
<p><strong>ii) Binary classification — sigmoid output, cross-entropy.</strong> <span class="math inline">\(S_L = 1\)</span>, <span class="math inline">\(g = \sigma\)</span> (§31.8), loss the NLL (§31.9): <span class="math display">\[\boxed{L_{\mathrm{nll}}(g, y) = -\big(y \log g + (1 - y)\log(1 - g)\big)},\]</span> “penalizes the model for being confident and wrong” (the deck). The worked number from §41.9’s hand calculation: <span class="math inline">\(g = 0.4905\)</span>, <span class="math inline">\(y = 1\)</span> → <span class="math inline">\(L = -\log(0.4905) = 0.7123\)</span> [verified-NumPy]. The cleanest fact in the chapter lives here — §31.10’s derivation: for sigmoid + cross-entropy, the gradient w.r.t. the pre-activation is just <span class="math display">\[\boxed{\frac{\partial L}{\partial z} = g - y} \quad \text{(prediction minus truth)},\]</span> the <span class="math inline">\(g(1-g)\)</span> from the sigmoid’s derivative canceling the denominator from the loss. This is the <code>dz2 = (self.out - y)</code> line in §41.10’s <code>backward</code>.</p>
<p><strong>iii) Multiclass classification — softmax output, categorical cross-entropy.</strong> Output layer: <span class="math inline">\(S_L = k\)</span> neurons, <span class="math inline">\(g = \mathrm{softmax}\)</span> (§31.12): <span class="math display">\[\mathrm{softmax}(z)_i = \frac{e^{z_i}}{\sum_{j=1}^{k} e^{z_j}}, \qquad \sum_i \hat y_i = 1,\]</span> so <span class="math inline">\(\hat Y\)</span> (an <span class="math inline">\(n \times k\)</span> matrix) is a probability distribution over the <span class="math inline">\(k\)</span> classes per row, and inference is <span class="math inline">\(\arg\max_c \hat y^c\)</span> (MLT slides). Labels <span class="math inline">\(Y\)</span> are one-hot, <span class="math inline">\(n \times k\)</span>. The slides’ matrix form: <span class="math display">\[\boxed{L(Y, \hat Y) = -\mathbf{1}_n^T\, (Y \odot \log \hat Y)\, \mathbf{1}_k}, \qquad \text{``In Numpy: } L = -\mathrm{np.sum}(Y * \mathrm{np.log}(Y\_hat))\text{''},\]</span> <span class="math inline">\(\odot\)</span> the element-wise product, <span class="math inline">\(\mathbf{1}_n^T M \mathbf{1}_k\)</span> the sum of all entries. The deck’s worked example (3 classes): true cat <span class="math inline">\([1, 0, 0]\)</span>; good prediction <span class="math inline">\([0.8, 0.1, 0.1]\)</span> → low loss; bad prediction <span class="math inline">\([0.1, 0.2, 0.7]\)</span> → high loss. This is §35.13’s landing point: “the MLT Week-12 slides close with neural networks trained by <strong>cross-entropy loss</strong> for classification” — the hand-annotated slide’s diagram shows a network’s <span class="math inline">\(\mathrm{sigmoid}\)</span> feeding “<span class="math inline">\(p(y \mid x)\)</span>” into a “Cross-Entropy Loss” box — “the logistic loss of §35.6, scaled up to deep networks.”</p>
<p><strong>Basically, …</strong> “The hidden layers are the model; the output layer is the task. Counting things: identity activation + squared error. Yes/no: sigmoid + cross-entropy. Pick-one-of-<span class="math inline">\(k\)</span>: softmax + cross-entropy over the one-hot labels. And the pairings are not arbitrary — sigmoid’s derivative cancels cross-entropy’s, leaving prediction-minus-truth.”</p>
</section>
<section id="the-contract-survives-sklearns-mlpclassifier-mlpregressor" class="level2">
<h2 class="anchored" data-anchor-id="the-contract-survives-sklearns-mlpclassifier-mlpregressor">41.12 The contract survives: sklearn’s <code>MLPClassifier</code> / <code>MLPRegressor</code></h2>
<p>The Week-12 practice-solution notebook runs both, and both honor the estimator contract of Chapters 37–38 (as §37.10(iii) and §38.11(iii) promised):</p>
<p><strong>eg 6 (classification, diabetes dataset, <code>Outcome</code> target).</strong> Pipeline: <code>StandardScaler</code> + <code>MLPClassifier(hidden_layer_sizes=(10,10,10), activation='relu', solver='sgd', alpha=1e-4, learning_rate_init=0.2, max_iter=500, random_state=1)</code>; 80:20 split, <code>random_state=1</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pipe.fit(X_train, y_train)     <span class="co"># learn the weights</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pipe.score(X_train, y_train)   <span class="co"># -&gt; 0.7915309446254072  [recorded]</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>pipe.score(X_test, y_test)     <span class="co"># -&gt; 0.7662337662337663  [recorded]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>hidden_layer_sizes=(10,10,10)</code> is three hidden layers of ten neurons each — an <span class="math inline">\(S_0\!-\!10\!-\!10\!-\!10\!-\!S_3\)</span> network in §41.4’s notation; <code>activation='relu'</code> is the hidden-layer <span class="math inline">\(g\)</span>; <code>solver='sgd'</code> the engine; <code>alpha</code> the L2 penalty (Chapter 28’s <span class="math inline">\(\lambda\)</span>); <code>max_iter=500</code> caps the epochs.</p>
<p><strong>eg 7 (regression).</strong> Pipeline: <code>StandardScaler</code> + <code>MLPRegressor(hidden_layer_sizes=(50,50,50), tol=1e-2, alpha=1e-4, solver='adam', learning_rate_init=0.1, max_iter=50, random_state=1)</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>pipe.score(X_train, y_train)   <span class="co"># -&gt; 0.999992602958679  [recorded]  (R^2)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>pipe.score(X_test, y_test)     <span class="co"># -&gt; 0.9999920781245708  [recorded]  (R^2)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The Week-12 note on this estimator: “trains using backpropagation… uses the square error as the loss function” (§37.10(iii)) — pairing (i) of §41.11, inside the same <code>fit</code>/<code>predict</code>/<code>score</code> contract. Neither snippet ran here (sklearn is not installed) — the numbers are the notebook’s printed outputs.</p>
<p><strong>Basically, …</strong> “sklearn’s neural nets are just §41.10’s class with the same three methods every estimator has had since Chapter 37: <code>fit</code> learns the weights, <code>predict</code> runs the forward pass, <code>score</code> reports the verdict. The inside is neurons; the contract is unchanged.”</p>
</section>
<section id="pytorch-tensors-in-the-same-loop-out" class="level2">
<h2 class="anchored" data-anchor-id="pytorch-tensors-in-the-same-loop-out">41.13 PyTorch: tensors in, the same loop out</h2>
<p>The course’s two PyTorch notebooks do one job each: <em>Fundamentals</em> — tensors as the data structure; <em>Workflow</em> — the training loop as the engine. Both transcribe here [recorded]; torch is not installed on this machine.</p>
<p><strong>Tensors</strong> (Fundamentals notebook): “the fundamental data structure” — vectors, matrices, and higher-rank arrays, all as one type. The working vocabulary, all transcribed from the notebook: - creation: <code>torch.tensor(...)</code>, <code>torch.zeros()</code>, <code>torch.ones()</code>, <code>torch.rand()</code>, <code>torch.arange()</code>; default dtype <code>float32</code> (a method like <code>.mean()</code> on an integer tensor errors — the notebook hits this); - the central distinction: <code>*</code> is element-wise, <code>torch.matmul</code> / <code>@</code> is matrix multiplication — the notebook’s line: “the difference between element-wise multiplication and matrix multiplication is the addition of values” (§2.10’s rule, in code); - shape tools: <code>reshape</code>, <code>view</code> (shares the underlying data — changing the view changes the original), <code>squeeze</code>/<code>unsqueeze</code>, <code>permute</code> (also a view), indexing <code>x[:, 0]</code>, <code>x.argmax()</code>; - NumPy interop: <code>torch.from_numpy(array)</code> (keeps the <code>float64</code> dtype), and <code>.numpy()</code> back — the §36.1 world and the tensor world sharing memory.</p>
<p><strong>The MLP as an <code>nn.Module</code></strong> (Fashion-MNIST notebook — a 784→128→64→10 classifier, the two-core-equations of §41.4 as objects):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> FashionMLP(nn.Module):                          <span class="co"># [recorded]</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Architecture: 784 -&gt; 128 -&gt; 64 -&gt; 10</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">       - Input: Flattened 28x28 images (784 features)</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">       - Hidden layers: ReLU activation for non-linearity</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">       - Output: 10 class probabilities (softmax applied in loss function)"""</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, input_size<span class="op">=</span><span class="dv">784</span>, hidden1_size<span class="op">=</span><span class="dv">128</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                 hidden2_size<span class="op">=</span><span class="dv">64</span>, num_classes<span class="op">=</span><span class="dv">10</span>):</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>(FashionMLP, <span class="va">self</span>).<span class="fu">__init__</span>()</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.flatten <span class="op">=</span> nn.Flatten()                     <span class="co"># (B,1,28,28) -&gt; (B,784)</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.hidden1 <span class="op">=</span> nn.Linear(input_size, hidden1_size)  <span class="co"># 784 -&gt; 128</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.hidden2 <span class="op">=</span> nn.Linear(hidden1_size, hidden2_size)<span class="co"># 128 -&gt; 64</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.output  <span class="op">=</span> nn.Linear(hidden2_size, num_classes) <span class="co"># 64 -&gt; 10</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.relu <span class="op">=</span> nn.ReLU()</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.dropout <span class="op">=</span> nn.Dropout(p<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):                                <span class="co"># the forward pass</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> <span class="va">self</span>.flatten(x)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> <span class="va">self</span>.hidden1(x)<span class="op">;</span> x <span class="op">=</span> <span class="va">self</span>.relu(x)<span class="op">;</span> x <span class="op">=</span> <span class="va">self</span>.dropout(x)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> <span class="va">self</span>.hidden2(x)<span class="op">;</span> x <span class="op">=</span> <span class="va">self</span>.relu(x)<span class="op">;</span> x <span class="op">=</span> <span class="va">self</span>.dropout(x)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.output(x)                            <span class="co"># logits</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>nn.Linear</code> <em>is</em> one row of §41.4: <span class="math inline">\(Z = AW + b\)</span> with <span class="math inline">\(W, b\)</span> as learnable parameters. The training configuration the notebook chooses: <code>nn.CrossEntropyLoss()</code> (pairing (iii) of §41.11 — “combines” softmax with the loss), Adam at <code>lr=0.001</code> with <code>weight_decay=1e-4</code> (L2, Chapter 28), 10 epochs.</p>
<p><strong>The five-step training loop</strong> (Workflow notebook, transcribed verbatim):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(epochs):                       <span class="co"># [recorded]</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    model_0.train()                               <span class="co"># training mode</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> model_0(X_train)                     <span class="co"># 1. forward pass</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> loss_fn(y_pred, y_train)               <span class="co"># 2. loss</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    optimizer.zero_grad()                         <span class="co"># 3. zero accumulated grads</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    loss.backward()                               <span class="co"># 4. backprop (chain rule)</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    optimizer.step()                              <span class="co"># 5. theta := theta - lr*grad</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Each step maps onto this chapter’s machine: 1 = §41.4’s two equations; 2 = §41.11’s loss; 3–4 = the chain rule (Chapter 42 — §41.10’s <code>backward</code>, automated); 5 = §10.5’s update (the perceptron’s era ended, gradient descent is the engine now). The workflow notebook also keeps §40.4’s discipline: train and test phases are <em>separate</em> — “assesses model performance on test data without parameter updates… prevents information leakage” — and ends with <code>state_dict()</code> save/load, the learned weights as a portable artifact.</p>
<p><strong>Basically, …</strong> “PyTorch changes the notation, not the machine. A tensor is an ndarray that knows about gradients (§36.1’s world, extended). <code>nn.Linear</code> is §41.4’s layer as an object. The training loop is §41.10’s loop with the backward step automated. If you understand the numpy version, the PyTorch version is just the same five steps wearing nicer syntax.”</p>
</section>
<section id="four-traps-worth-knowing-the-courses-own-warnings" class="level2">
<h2 class="anchored" data-anchor-id="four-traps-worth-knowing-the-courses-own-warnings">41.14 Four traps worth knowing (the course’s own warnings)</h2>
<p><strong>i) Zero-init symmetry.</strong> “Why did we not initialize all parameters to zero?” (MLT slides). Because “since the incoming weights are the same for all neurons in a layer, there is nothing to differentiate between two neurons. This symmetry means that they will evolve identically and will not learn different things.” So: “setting all weights to a constant value, especially 0, is a bad idea for neural networks” — the slides sample <span class="math inline">\(\theta \sim \mathcal{N}(0, 1)\)</span> (the MLP class in §41.10 seeds <span class="math inline">\(\mathcal{N}(0, 0.5^2)\)</span> for the same reason; §36.6 on seeding).</p>
<p><strong>ii) Parameter count → overfitting.</strong> The MLT slides’ MNIST example, <span class="math inline">\(784 \to 50 \to 10\)</span>: weights <span class="math inline">\(784 \cdot 50 = 39{,}200\)</span> plus <span class="math inline">\(50\)</span> biases plus <span class="math inline">\(50 \cdot 10 = 500\)</span> plus <span class="math inline">\(10\)</span> — “number of parameters = <span class="math inline">\((39200 + 50) + (500 + 10) = 39{,}760\)</span>” (the slides’ arithmetic, rechecked). “With just 1 hidden layer, we have a model with nearly 40,000 parameters… Neural networks are thus prone to overfitting.” The slides’ two fixes: L1/L2 regularization and <strong>dropout</strong> — “in each iteration of GD, randomly choose half the neurons in the hidden layer and ‘drop’ them ‘out’ of the network… at inference, use the full network, but halve the outgoing weights.” The slides’ distinction: “L1/L2 regularization: modifies the loss function. Dropout: modifies the network.”</p>
<p><strong>iii) The loss is not the 0/1 you care about.</strong> Chapter 35’s trade (§35.9) rides along: cross-entropy and squared error are <em>surrogates</em> — smooth stand-ins optimized so that the true objective (accuracy, the 0/1 loss of §35.1) comes along for the ride.</p>
<p><strong>iv) Local minima, and why nobody panics.</strong> The hand-annotated Week-12 slide’s bottom line, quoted whole: the network “converges to <strong>local minima</strong>” — but “typically works very well in practice, especially for unstructured data.” §10.9’s promises stand: gradient descent walks downhill; nobody guarantees the bottom of the whole landscape.</p>
</section>
<section id="where-this-goes-next" class="level2">
<h2 class="anchored" data-anchor-id="where-this-goes-next">41.15 Where this goes next</h2>
<ol type="i">
<li><p><strong>Backpropagation, end to end (Chapter 42).</strong> The one piece this chapter borrowed without deriving: §41.10’s <code>backward</code> — how <span class="math inline">\(\partial L/\partial z\)</span> flows from the output layer back through every weight. The course’s XOR notebook hand-computes the full backward pass for the same 2-2-1 net (§41.9’s numbers: <span class="math inline">\(\partial L/\partial z_3 = -0.509\)</span>, hidden deltas <span class="math inline">\(-0.200\)</span> and <span class="math inline">\(0.127\)</span>, one weight update at <span class="math inline">\(\alpha = 0.1\)</span>); the GenAI deck derives it generally on a computational graph (“any mathematical expression can be decomposed into a graph of basic operations”). Chapter 42 is both, fully worked.</p></li>
<li><p><strong>Initialization and optimization (Chapter 43).</strong> §41.14(i)’s symmetry trap is the entry point: <em>how</em> to sample the initial weights, why scale matters for deep stacks, and the optimizers (SGD variants, Adam) the notebooks already name.</p></li>
<li><p><strong>The Part VI arc.</strong> CNNs, RNNs, attention (Chapters 44–46) keep §41.4’s two equations and change what a “layer” computes; the debugging discipline of Chapter 40 rides along whole — “debugging a neural net starts with the same playbook: shapes first, then scale, then shuffle, then the leak audit” (§40.5(i)).</p></li>
</ol>
</section>
<section id="problem-set" class="level2">
<h2 class="anchored" data-anchor-id="problem-set">Problem set</h2>
<ol type="1">
<li><strong>Neuron arithmetic.</strong> A neuron takes <span class="math inline">\(a = (2, -1, 0.5)\)</span>, <span class="math inline">\(w = (0.4, 0.8, -0.6)\)</span>, <span class="math inline">\(b = 0.1\)</span>. (i) Compute the pre-activation <span class="math inline">\(z\)</span>. (ii) Compute the post-activation for <span class="math inline">\(g = \sigma\)</span> (to 3 s.f.) and for <span class="math inline">\(g = \mathrm{ReLU}\)</span>. (iii) Which activation would the deck’s §41.7 guide recommend if this neuron lived in a hidden layer, and why in one line?</li>
<li><strong>Layer shapes.</strong> An MLP has layer sizes <span class="math inline">\(S = [4, 6, 6, 3]\)</span> (input <span class="math inline">\(m = 4\)</span>, two hidden layers, <span class="math inline">\(k = 3\)</span> output) and a batch of <span class="math inline">\(n = 32\)</span> points. (i) Give the shape of each <span class="math inline">\(W^l\)</span> and <span class="math inline">\(b^l\)</span> in the batch convention (<span class="math inline">\(Z^l = A^{l-1}W^l + b^l\)</span>). (ii) Count the total parameters (weights + biases); recheck against the MLT slides’ <span class="math inline">\(784\!-\!50\!-\!10\)</span> arithmetic (<span class="math inline">\(39{,}760\)</span>). (iii) Write the shape chain for <span class="math inline">\(Z^2\)</span> and <span class="math inline">\(A^2\)</span> explicitly.</li>
<li><strong>The transpose convention.</strong> The deck’s per-example slide gives <span class="math inline">\(x = [0.5, 1.0]^T\)</span>, <span class="math inline">\(W = \begin{bmatrix} 0.2 &amp; 0.7 \\ -0.4 &amp; 0.1 \\ 0.9 &amp; -0.3 \end{bmatrix}\)</span>, and computes <span class="math inline">\(z = Wx + b\)</span>. (i) Explain in one line why batch code uses <code>Z = X @ W.T + b</code> instead of <code>X @ W + b</code> for this <span class="math inline">\(W\)</span>. (ii) For the batch form, give <span class="math inline">\(W\)</span>’s shape and the row of <span class="math inline">\(Z\)</span> corresponding to <span class="math inline">\(x = (0.5, 1.0)\)</span>. (iii) Name the debugging chapter-section this convention clash would violate if read backwards.</li>
<li><strong>XOR proof, re-derived.</strong> (i) Reproduce §41.8’s contradiction for a linear model <span class="math inline">\(f(x_1,x_2) = w_1x_1 + w_2x_2 + b\)</span> on the four XOR corners. (ii) In two lines, explain why this proof also kills any <em>stacked</em> linear network (use §41.6’s collapse). (iii) Give one sentence saying what the hidden layer must do so the output layer can succeed (the deck’s “automatic feature engineer” line).</li>
<li><strong>A new ReLU layer.</strong> <span class="math inline">\(x = (1, -2)\)</span>, <span class="math inline">\(W = \begin{bmatrix} 0.5 &amp; -0.5 \\ 1.0 &amp; 2.0 \\ -1.0 &amp; 0.25 \end{bmatrix}\)</span>, <span class="math inline">\(b = (0, 0.5, -1)\)</span>. (i) Compute <span class="math inline">\(z = Wx + b\)</span> by hand. (ii) Apply ReLU element-wise. (iii) Which neurons fired, which died, and what does the dying one contribute to the next layer?</li>
<li><strong>Loss pairing.</strong> (i) Binary case: prediction <span class="math inline">\(g = 0.2\)</span>, true <span class="math inline">\(y = 1\)</span> — compute the cross-entropy loss; then compute it again for <span class="math inline">\(g = 0.8\)</span> and compare. (ii) Multiclass case: <span class="math inline">\(Y = [0, 1, 0]\)</span>, <span class="math inline">\(\hat Y = [0.2, 0.7, 0.1]\)</span> — compute the categorical cross-entropy. (iii) Regression case: <span class="math inline">\(y = (1, 2, 3)\)</span>, <span class="math inline">\(\hat y = (1.5, 2.5, 2)\)</span> — compute the slides’ <span class="math inline">\(L = \tfrac12 (\hat y - y)^T(\hat y - y)\)</span>.</li>
<li><strong>The <span class="math inline">\((g-y)\)</span> simplification.</strong> (i) For sigmoid output + cross-entropy, verify <span class="math inline">\(\partial L/\partial z = g - y\)</span> numerically at <span class="math inline">\(g = 0.4905\)</span>, <span class="math inline">\(y = 1\)</span> using §31.10’s two-step chain (<span class="math inline">\(\partial L/\partial g\)</span> then <span class="math inline">\(dg/dz\)</span>). (ii) In the §41.10 class, point at the exact line this simplification produces. (iii) In one line, say what Chapter 42 must derive when the hidden layer’s <span class="math inline">\(g\)</span> is <em>not</em> paired with its loss.</li>
<li><strong>Map the two loops.</strong> (i) Match each of the PyTorch workflow’s five steps (forward, loss, <code>zero_grad</code>, <code>backward</code>, <code>step</code>) to a method or line in §41.10’s numpy class. (ii) Which step does the notebook’s version do <em>by hand</em> that PyTorch automates? (iii) The workflow notebook runs the test phase without parameter updates — name the §40.4 suspect this discipline prevents.</li>
<li><strong>Zero-init symmetry.</strong> Two hidden neurons start with <em>identical</em> incoming weights and bias. (i) In two lines, show their pre-activations stay equal for the same input, so their outputs and gradient updates stay equal forever. (ii) State the fix the MLT slides prescribe (distribution and one-line reason). (iii) §41.10’s class uses <code>rng.standard_normal((2,2)) * 0.5</code> — name the two choices (distribution, seed) and what each buys.</li>
<li><strong>The sklearn face.</strong> (i) Read eg 6’s constructor: what do <code>hidden_layer_sizes</code>, <code>activation</code>, <code>solver</code>, <code>alpha</code>, <code>max_iter</code> each mean, in §41.4/§41.7/Chapter 28 terms? (ii) eg 7’s <code>score</code> returns <span class="math inline">\(R^2\)</span> — which §41.11 pairing does this estimator use, and how do you know from the Week-12 note? (iii) In one line each: what do <code>fit</code>, <code>predict</code>, and <code>score</code> compute for <code>MLPClassifier</code>?</li>
</ol>
</section>
<section id="solutions" class="level2">
<h2 class="anchored" data-anchor-id="solutions">Solutions</h2>
<p>Attempt each problem first, then click a problem to reveal its worked solution.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 1 — Neuron arithmetic.** (i) <span class="math inline">\(z = 0.4(2) + 0.8(-1) + (-0.6)(0.5) + 0.1 = 0.8 - 0.8 - 0.3 + 0.1 = -0.2\)</span>. (ii) <span class="math inline">\(\sigma(-0.2) = 1/(1 + e^{0.2}) = 1/2.2214 \approx 0.450\)</span>; <span class="math inline">\(\mathrm{ReLU}(-0.2) = 0\)</span>. (iii) ReLU — the deck’s guide: “start with ReLU. Most common, fastest, and usually works”; sigmoid in a hidden layer would invite vanishing gradients for no probabilistic payoff.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1. Neuron arithmetic.</strong> (i) <span class="math inline">\(z = 0.4(2) + 0.8(-1) + (-0.6)(0.5) + 0.1 = 0.8 - 0.8 - 0.3 + 0.1 = -0.2\)</span>. (ii) <span class="math inline">\(\sigma(-0.2) = 1/(1 + e^{0.2}) = 1/2.2214 \approx 0.450\)</span>; <span class="math inline">\(\mathrm{ReLU}(-0.2) = 0\)</span>. (iii) ReLU — the deck’s guide: “start with ReLU. Most common, fastest, and usually works”; sigmoid in a hidden layer would invite vanishing gradients for no probabilistic payoff.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 2 — Layer shapes.** (i) <span class="math inline">\(W^1: 4 \times 6\)</span>, <span class="math inline">\(b^1: (6,)\)</span>; <span class="math inline">\(W^2: 6 \times 6\)</span>, <span class="math inline">\(b^2: (6,)\)</span>; <span class="math inline">\(W^3: 6 \times 3\)</span>, <span class="math inline">\(b^3: (3,)\)</span>. (ii) <span class="math inline">\(4\cdot6+6 = 30\)</span>, <span class="math inline">\(6\cdot6+6 = 42\)</span>, <span class="math inline">\(6\cdot3+3 = 21\)</span>; total <span class="math inline">\(93\)</span>. The slides’ check: <span class="math inline">\(784\cdot50+50 = 39{,}250\)</span>, <span class="math inline">\(50\cdot10+10 = 510\)</span>, total <span class="math inline">\(39{,}760\)</span>. (iii) <span class="math inline">\(Z^2 = A^1 W^2 + b^2\)</span>: <span class="math inline">\((32 \times 6)(6 \times 6) \to (32 \times 6)\)</span>, bias broadcast down the rows; <span class="math inline">\(A^2 = g(Z^2)\)</span> is <span class="math inline">\((32 \times 6)\)</span>.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>2. Layer shapes.</strong> (i) <span class="math inline">\(W^1: 4 \times 6\)</span>, <span class="math inline">\(b^1: (6,)\)</span>; <span class="math inline">\(W^2: 6 \times 6\)</span>, <span class="math inline">\(b^2: (6,)\)</span>; <span class="math inline">\(W^3: 6 \times 3\)</span>, <span class="math inline">\(b^3: (3,)\)</span>. (ii) <span class="math inline">\(4\cdot6+6 = 30\)</span>, <span class="math inline">\(6\cdot6+6 = 42\)</span>, <span class="math inline">\(6\cdot3+3 = 21\)</span>; total <span class="math inline">\(93\)</span>. The slides’ check: <span class="math inline">\(784\cdot50+50 = 39{,}250\)</span>, <span class="math inline">\(50\cdot10+10 = 510\)</span>, total <span class="math inline">\(39{,}760\)</span>. (iii) <span class="math inline">\(Z^2 = A^1 W^2 + b^2\)</span>: <span class="math inline">\((32 \times 6)(6 \times 6) \to (32 \times 6)\)</span>, bias broadcast down the rows; <span class="math inline">\(A^2 = g(Z^2)\)</span> is <span class="math inline">\((32 \times 6)\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 3 — The transpose convention.** (i) The deck’s <span class="math inline">\(W\)</span> is <span class="math inline">\(3 \times 2\)</span> because it left-multiplies a <span class="math inline">\(2 \times 1\)</span> column vector; a batch row is <span class="math inline">\(1 \times 2\)</span> and right-multiplies, so it needs the <span class="math inline">\(2 \times 3\)</span> layout — <span class="math inline">\(W^T\)</span>. (ii) The batch <span class="math inline">\(W\)</span> is <span class="math inline">\(2 \times 3\)</span> (<span class="math inline">\(W_{deck}^T\)</span>); the row for <span class="math inline">\(x = (0.5, 1.0)\)</span> is <span class="math inline">\(z = [0.9,\ 0.1,\ -0.35]\)</span> (§41.5’s eg 1). (iii) §36.1’s Note — the <span class="math inline">\((d,n)\)</span>-vs-<span class="math inline">\((n,d)\)</span> convention clash, “the single most common shape bug in ML code.”
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>3. The transpose convention.</strong> (i) The deck’s <span class="math inline">\(W\)</span> is <span class="math inline">\(3 \times 2\)</span> because it left-multiplies a <span class="math inline">\(2 \times 1\)</span> column vector; a batch row is <span class="math inline">\(1 \times 2\)</span> and right-multiplies, so it needs the <span class="math inline">\(2 \times 3\)</span> layout — <span class="math inline">\(W^T\)</span>. (ii) The batch <span class="math inline">\(W\)</span> is <span class="math inline">\(2 \times 3\)</span> (<span class="math inline">\(W_{deck}^T\)</span>); the row for <span class="math inline">\(x = (0.5, 1.0)\)</span> is <span class="math inline">\(z = [0.9,\ 0.1,\ -0.35]\)</span> (§41.5’s eg 1). (iii) §36.1’s Note — the <span class="math inline">\((d,n)\)</span>-vs-<span class="math inline">\((n,d)\)</span> convention clash, “the single most common shape bug in ML code.”</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 4 — XOR proof, re-derived.** (i) §41.8’s eg 3: <span class="math inline">\(b \approx 0\)</span>, <span class="math inline">\(w_2 \approx 1\)</span>, <span class="math inline">\(w_1 \approx 1\)</span> force <span class="math inline">\(f(1,1) \approx 2 \ne 0\)</span> — contradiction. (ii) A stacked linear network is still one linear function, <span class="math inline">\(W'x + b'\)</span> (§41.6), so the same four equations give the same contradiction. (iii) The hidden layer must transform the data into a representation in which the corners are linearly separable — “an automatic feature engineer.”
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>4. XOR proof, re-derived.</strong> (i) §41.8’s eg 3: <span class="math inline">\(b \approx 0\)</span>, <span class="math inline">\(w_2 \approx 1\)</span>, <span class="math inline">\(w_1 \approx 1\)</span> force <span class="math inline">\(f(1,1) \approx 2 \ne 0\)</span> — contradiction. (ii) A stacked linear network is still one linear function, <span class="math inline">\(W'x + b'\)</span> (§41.6), so the same four equations give the same contradiction. (iii) The hidden layer must transform the data into a representation in which the corners are linearly separable — “an automatic feature engineer.”</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 5 — A new ReLU layer.** (i) <span class="math inline">\(z_1 = 0.5(1) + (-0.5)(-2) + 0 = 1.5\)</span>; <span class="math inline">\(z_2 = 1.0(1) + 2.0(-2) + 0.5 = -2.5\)</span>; <span class="math inline">\(z_3 = -1.0(1) + 0.25(-2) - 1 = -2.5\)</span>. (ii) <span class="math inline">\(a = [1.5,\ 0,\ 0]\)</span>. (iii) Only neuron 1 fired; 2 and 3 died. A dead neuron contributes <span class="math inline">\(0\)</span> times its outgoing weights to the next layer — nothing. That is ReLU’s sparsity working as intended at one neuron, and the dying-ReLU pathology if the death is permanent (§41.7).
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>5. A new ReLU layer.</strong> (i) <span class="math inline">\(z_1 = 0.5(1) + (-0.5)(-2) + 0 = 1.5\)</span>; <span class="math inline">\(z_2 = 1.0(1) + 2.0(-2) + 0.5 = -2.5\)</span>; <span class="math inline">\(z_3 = -1.0(1) + 0.25(-2) - 1 = -2.5\)</span>. (ii) <span class="math inline">\(a = [1.5,\ 0,\ 0]\)</span>. (iii) Only neuron 1 fired; 2 and 3 died. A dead neuron contributes <span class="math inline">\(0\)</span> times its outgoing weights to the next layer — nothing. That is ReLU’s sparsity working as intended at one neuron, and the dying-ReLU pathology if the death is permanent (§41.7).</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 6 — Loss pairing.** (i) <span class="math inline">\(g = 0.2\)</span>: <span class="math inline">\(L = -\log 0.2 = 1.6094\)</span>; <span class="math inline">\(g = 0.8\)</span>: <span class="math inline">\(L = -\log 0.8 = 0.2231\)</span>. The wrong-confident guess costs <span class="math inline">\(7.2\times\)</span> the right-confident one — cross-entropy “penalizes the model for being confident and wrong.” (ii) <span class="math inline">\(L = -\log 0.7 = 0.3567\)</span> — only the true class’s probability enters, via the one-hot product. (iii) <span class="math inline">\(\hat y - y = (0.5, 0.5, -1)\)</span>, squared length <span class="math inline">\(0.25 + 0.25 + 1 = 1.5\)</span>, <span class="math inline">\(L = 1.5/2 = 0.75\)</span>.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>6. Loss pairing.</strong> (i) <span class="math inline">\(g = 0.2\)</span>: <span class="math inline">\(L = -\log 0.2 = 1.6094\)</span>; <span class="math inline">\(g = 0.8\)</span>: <span class="math inline">\(L = -\log 0.8 = 0.2231\)</span>. The wrong-confident guess costs <span class="math inline">\(7.2\times\)</span> the right-confident one — cross-entropy “penalizes the model for being confident and wrong.” (ii) <span class="math inline">\(L = -\log 0.7 = 0.3567\)</span> — only the true class’s probability enters, via the one-hot product. (iii) <span class="math inline">\(\hat y - y = (0.5, 0.5, -1)\)</span>, squared length <span class="math inline">\(0.25 + 0.25 + 1 = 1.5\)</span>, <span class="math inline">\(L = 1.5/2 = 0.75\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 7 — The <span class="math inline">\((g-y)\)</span> simplification.** (i) <span class="math inline">\(\partial L/\partial g = (g - y)/(g(1-g)) = (-0.5095)/(0.24991) = -2.0387\)</span>; <span class="math inline">\(dg/dz = g(1-g) = 0.24991\)</span>; product <span class="math inline">\(-0.5095 = g - y\)</span> — §31.10’s cancellation, numerically confirmed. (ii) <code>dz2 = (self.out - y).reshape(-1, 1) / m</code> in <code>MLP221.backward</code>. (iii) Chapter 42 must derive the general backward pass — the error deltas <span class="math inline">\(\delta^l\)</span> for every layer and how they chain through each activation — of which this is the output-layer special case.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>7. The <span class="math inline">\((g-y)\)</span> simplification.</strong> (i) <span class="math inline">\(\partial L/\partial g = (g - y)/(g(1-g)) = (-0.5095)/(0.24991) = -2.0387\)</span>; <span class="math inline">\(dg/dz = g(1-g) = 0.24991\)</span>; product <span class="math inline">\(-0.5095 = g - y\)</span> — §31.10’s cancellation, numerically confirmed. (ii) <code>dz2 = (self.out - y).reshape(-1, 1) / m</code> in <code>MLP221.backward</code>. (iii) Chapter 42 must derive the general backward pass — the error deltas <span class="math inline">\(\delta^l\)</span> for every layer and how they chain through each activation — of which this is the output-layer special case.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 8 — Map the two loops.** (i) forward → <code>MLP221.forward</code> (the two equations, both layers); loss → <code>MLP221.loss</code> (binary cross-entropy); <code>zero_grad</code> → no analogue — the numpy code computes fresh gradients each call, nothing accumulates; backward → <code>MLP221.backward</code> (the hand-derived chain rule); step → <code>MLP221.step</code> (<span class="math inline">\(\theta := \theta - \eta\,\nabla J\)</span>). (ii) The backward step: PyTorch’s autograd computes the chain rule automatically; the notebook and §41.10 derive it by hand. (iii) §40.4’s suspect (iii) — the test set spent more than once: updates on test data would fit the model to the evaluation set, breaking §39.6’s spend-once doctrine.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>8. Map the two loops.</strong> (i) forward → <code>MLP221.forward</code> (the two equations, both layers); loss → <code>MLP221.loss</code> (binary cross-entropy); <code>zero_grad</code> → no analogue — the numpy code computes fresh gradients each call, nothing accumulates; backward → <code>MLP221.backward</code> (the hand-derived chain rule); step → <code>MLP221.step</code> (<span class="math inline">\(\theta := \theta - \eta\,\nabla J\)</span>). (ii) The backward step: PyTorch’s autograd computes the chain rule automatically; the notebook and §41.10 derive it by hand. (iii) §40.4’s suspect (iii) — the test set spent more than once: updates on test data would fit the model to the evaluation set, breaking §39.6’s spend-once doctrine.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 9 — Zero-init symmetry.** (i) Identical weights and bias, same input → identical pre-activation <span class="math inline">\(z\)</span>, identical activation <span class="math inline">\(g(z)\)</span>. The gradients are the same deterministic functions of these identical quantities, so the updates are identical — the two neurons evolve identically, forever. (ii) Sample <span class="math inline">\(\theta \sim \mathcal{N}(0, 1)\)</span> (the MLT slides): random weights break the symmetry, so neurons learn different features. (iii) <code>default_rng(42)</code> is the seeded, reproducible RNG (§36.6); <code>standard_normal * 0.5</code> is the notebook’s Gaussian-with-small-scale choice — randomness for symmetry-breaking, small so sigmoid starts in its linear-ish region, not saturated.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>9. Zero-init symmetry.</strong> (i) Identical weights and bias, same input → identical pre-activation <span class="math inline">\(z\)</span>, identical activation <span class="math inline">\(g(z)\)</span>. The gradients are the same deterministic functions of these identical quantities, so the updates are identical — the two neurons evolve identically, forever. (ii) Sample <span class="math inline">\(\theta \sim \mathcal{N}(0, 1)\)</span> (the MLT slides): random weights break the symmetry, so neurons learn different features. (iii) <code>default_rng(42)</code> is the seeded, reproducible RNG (§36.6); <code>standard_normal * 0.5</code> is the notebook’s Gaussian-with-small-scale choice — randomness for symmetry-breaking, small so sigmoid starts in its linear-ish region, not saturated.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution 10 — The sklearn face.** (i) <code>hidden_layer_sizes=(10,10,10)</code>: three hidden layers, 10 neurons each (<span class="math inline">\(S_1 = S_2 = S_3 = 10\)</span>). <code>activation='relu'</code>: the hidden-layer <span class="math inline">\(g\)</span> (§41.7). <code>solver='sgd'</code>: stochastic-gradient-descent engine. <code>alpha=1e-4</code>: the L2 penalty (Chapter 28’s <span class="math inline">\(\lambda\)</span>). <code>max_iter=500</code>: the epoch cap. (ii) Pairing (i) of §41.11 — identity output + squared error: the Week-12 note says <code>MLPRegressor</code> “uses the square error as the loss function,” and its <code>score</code> is <span class="math inline">\(R^2\)</span>, the regression score (§37.5). (iii) <code>fit</code> learns all <span class="math inline">\(W^l, b^l\)</span> from the training set (backprop + SGD); <code>predict</code> runs the forward pass and returns labels (threshold at <span class="math inline">\(0.5\)</span> / argmax); <code>score</code> returns accuracy on the supplied set.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>10. The sklearn face.</strong> (i) <code>hidden_layer_sizes=(10,10,10)</code>: three hidden layers, 10 neurons each (<span class="math inline">\(S_1 = S_2 = S_3 = 10\)</span>). <code>activation='relu'</code>: the hidden-layer <span class="math inline">\(g\)</span> (§41.7). <code>solver='sgd'</code>: stochastic-gradient-descent engine. <code>alpha=1e-4</code>: the L2 penalty (Chapter 28’s <span class="math inline">\(\lambda\)</span>). <code>max_iter=500</code>: the epoch cap. (ii) Pairing (i) of §41.11 — identity output + squared error: the Week-12 note says <code>MLPRegressor</code> “uses the square error as the loss function,” and its <code>score</code> is <span class="math inline">\(R^2\)</span>, the regression score (§37.5). (iii) <code>fit</code> learns all <span class="math inline">\(W^l, b^l\)</span> from the training set (backprop + SGD); <code>predict</code> runs the forward pass and returns labels (threshold at <span class="math inline">\(0.5\)</span> / argmax); <code>score</code> returns accuracy on the supplied set.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./40-end-to-end-debugging.html" class="pagination-link" aria-label="Chapter 40: End-to-end model training and debugging">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Chapter 40: End-to-end model training and debugging</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./42-backpropagation.html" class="pagination-link" aria-label="Chapter 42: Backpropagation, worked end-to-end">
        <span class="nav-page-text"><span class="chapter-title">Chapter 42: Backpropagation, worked end-to-end</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>